# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/tti
    REF boost-${VERSION}
    SHA512 4c8d3fb4118873dd1b3b5edfad399c8196b979dbea28bc46af6907377a70c381b40eec5b176f79a752936c72675f46ef0175bd01bc0562c59ee79678f9cb4e85
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
