# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/tti
    REF boost-${VERSION}
    SHA512 5e1845d35e716bd529fad38b34ad59601a19ce3f95498d24de76d421e9c70417492e2acad2930cc27f20cb339cf1c7406fe6495a846797029d5b26335f27f52a
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
