option(VCPKG_ENABLE_SET_TARGET_PROPERTIES "Enables override of the cmake function set_target_properties." ON)
mark_as_advanced(VCPKG_ENABLE_SET_TARGET_PROPERTIES)
CMAKE_DEPENDENT_OPTION(VCPKG_ENABLE_SET_TARGET_PROPERTIES_EXTERNAL_OVERRIDE "Tells VCPKG to use _set_target_properties instead of set_target_properties." OFF "NOT VCPKG_ENABLE_SET_TARGET_PROPERTIES" OFF)
mark_as_advanced(VCPKG_ENABLE_SET_TARGET_PROPERTIES_EXTERNAL_OVERRIDE)

function(vcpkg_set_target_properties)
    list(FIND ARGV PROPERTIES _vcpkg_properties_pos)
    list(SUBLIST ARGV 0 ${_vcpkg_properties_pos} _vcpkg_target_sublist)
    math(EXPR _vcpkg_target_index_key "${_vcpkg_properties_pos}+1")
    vcpkg_msg(STATUS "set_target_properties" "ARGS: ${ARGV}")
    vcpkg_msg(STATUS "set_target_properties" "PROPERTIES Index: ${_vcpkg_properties_pos}")
    vcpkg_msg(STATUS "set_target_properties" "TARGETS: ${_vcpkg_target_sublist}")
    #Properties are key-value pairs and must be passed one by one since they are allowed to contain empty elements!
    while("${_vcpkg_target_index_key}" LESS "${ARGC}")
        math(EXPR _vcpkg_target_args_index_val "${_vcpkg_target_index_key}+1")
        vcpkg_msg(STATUS "set_target_properties" "Property: ARGV${_vcpkg_target_index_key}: ${ARGV${_vcpkg_target_index_key}}")
        vcpkg_msg(STATUS "set_target_properties" "Value: ARGV${_vcpkg_target_args_index_val}: ${ARGV${_vcpkg_target_args_index_val}}")
        set_property(TARGET ${_vcpkg_target_sublist} PROPERTY "${ARGV${_vcpkg_target_index_key}}" "${ARGV${_vcpkg_target_args_index_val}}")
        #if(VCPKG_ENABLE_SET_TARGET_PROPERTIES OR VCPKG_ENABLE_SET_TARGET_PROPERTIES_EXTERNAL_OVERRIDE)
        #    _set_target_properties(${_vcpkg_target_sublist} PROPERTIES "${ARGV${_vcpkg_target_index_key}}" "${ARGV${_vcpkg_target_args_index_val}}")
        #else()
        #    set_target_properties(${_vcpkg_target_sublist} PROPERTIES "${ARGV${_vcpkg_target_args_index}}" "${ARGV${_vcpkg_target_args_index_val}}")
        #endif()
        math(EXPR _vcpkg_target_index_key "${_vcpkg_target_args_index_val}+1")
    endwhile()
    #checks moved to set_property
endfunction()

if(VCPKG_ENABLE_SET_TARGET_PROPERTIES)
    function(set_target_properties)
        if(DEFINED _vcpkg_set_target_properties_guard)
            vcpkg_msg(FATAL_ERROR "set_target_properties" "INFINIT LOOP DETECT. Guard _vcpkg_set_target_properties_guard. Did you supply your own set_target_properties override? \n \
                                    If yes: please set VCPKG_ENABLE_SET_TARGET_PROPERTIES off and call vcpkg_set_target_properties if you want to have vcpkg corrected behavior. \n \
                                    If no: please open an issue on GITHUB describe the fail case!" ALWAYS)
        else()
            set(_vcpkg_set_target_properties_guard ON)
        endif()

        list(FIND ARGV PROPERTIES _vcpkg_set_target_properties_index)
        list(SUBLIST ARGV 0 ${_vcpkg_set_target_properties_index} _vcpkg_set_target_properties_sublist)
        math(EXPR _vcpkg_set_target_properties_index_key "${_vcpkg_set_target_properties_index}+1")
        #vcpkg_msg(STATUS "set_target_properties" "ARGC: ${ARGC} ARGS: ${ARGV}")
        #vcpkg_msg(STATUS "set_target_properties" "PROPERTIES Index: ${_vcpkg_set_target_properties_index}")
        #vcpkg_msg(STATUS "set_target_properties" "TARGETS: ${vcpkg_set_target_properties_sublist}")
        #Properties are key-value pairs and must be passed one by one since they are allowed to contain empty elements!
        while("${_vcpkg_set_target_properties_index_key}" LESS "${ARGC}")
            math(EXPR _vcpkg_set_target_properties_index_val "${_vcpkg_set_target_properties_index_key}+1")
            #vcpkg_msg(STATUS "set_target_properties" "Key: ARGV${_vcpkg_set_target_properties_index_key}: ${ARGV${_vcpkg_set_target_properties_index_key}}")
            #vcpkg_msg(STATUS "set_target_properties" "Value: ARGV${_vcpkg_set_target_properties_index_val}: ${ARGV${_vcpkg_set_target_properties_index_val}}")
            vcpkg_set_target_properties(${_vcpkg_set_target_properties_sublist} PROPERTIES "${ARGV${_vcpkg_set_target_properties_index_key}}" "${ARGV${_vcpkg_set_target_properties_index_val}}")
            math(EXPR _vcpkg_set_target_properties_index_key "${_vcpkg_set_target_properties_index_val}+1")
        endwhile()

        unset(_vcpkg_set_target_properties_guard)
    endfunction()
endif()