# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/phoenix
    REF boost-1.75.0
    SHA512 e888960ee154d73f9eb5d5d97d681aa5a8bba7295ab2150d80a316ab6c8aaf66efb3187ac618d59ad21aa0459b29ce68dcd106d5f6242b7db2ec3d61c92fa107
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
