# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/type_traits
    REF boost-${VERSION}
    SHA512 3d0163fc99691e181c97f830a96b28e03e89209120bbba818795c18bc426cf90e91994925df15bcf48e75c26c253973a49af299f028a4ee71b824fcb212edc31
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
