# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/align
    REF boost-${VERSION}
    SHA512 ebe074938ba8eed72c88dc03194ec578ff478a74bfedd5eaf4b57051e8e2b9b2180261b1a6c575b8dab29047e695c679f3f28a853a005bc3936b024188e51368
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
