# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/tuple
    REF boost-1.76.0
    SHA512 22c40d1c9f63cd22d0b632d81b15b30767273be019afe4ae8030cd9ac740e84f50e2db202b62448e9aa44bad2d8f0a3102e54cf1648b414ab7e30814c9da6219
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
