include(FindPackageHandleStandardArgs)
include(SelectLibraryConfigurations)

find_path(SPATIALITE_INCLUDE_DIR NAMES spatialite.h HINTS ${CURRENT_INSTALLED_DIR}/include)

find_library(SPATIALITE_LIBRARY_DEBUG NAMES spatialite_d spatialite_i_d spatialite NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug" NO_DEFAULT_PATH REQUIRED)
find_library(SPATIALITE_LIBRARY_RELEASE NAMES spatialite_i spatialite NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" NO_DEFAULT_PATH REQUIRED)

select_library_configurations(SPATIALITE)

set(SPATIALITE_INCLUDE_DIRS ${SPATIALITE_INCLUDE_DIR})
set(SPATIALITE_LIBRARIES ${SPATIALITE_LIBRARY})
