diff --git a/Makefile.msc b/Makefile.msc
index 901131d..00f0568 100644
--- a/Makefile.msc
+++ b/Makefile.msc
@@ -10,7 +10,7 @@
 CC = cl
 LD = link
 AR = lib
-CFLAGS = /MD /O2 -I. -Icommon
+CFLAGS = $(CL_FLAGS) -I. -Icommon
 LDFLAGS =
 
 STATIC_LIB = libdeflatestatic.lib
@@ -60,6 +60,14 @@ gunzip.exe:gzip.exe
 	copy $** $@
 
 clean:
-	-del *.dll *.exe *.exp libdeflate.lib libdeflatestatic.lib gzip.lib \
-		lib\*.obj lib\*\*.obj lib\*.dllobj lib\*\*.dllobj \
-		programs\*.obj 2>nul
+	-del /s /q *.dll *.exe *.exp libdeflate.lib libdeflatestatic.lib gzip.lib \
+		lib\*.obj lib\*.dllobj \
+		programs\*.obj
+
+install: all
+	-xcopy /i /y "gzip.exe" "$(INSTALLDIR)/bin\"
+	-xcopy /i /y "gunzip.exe" "$(INSTALLDIR)/bin\"
+	-xcopy /i /y "$(SHARED_LIB)" "$(INSTALLDIR)/bin\"
+	-xcopy /i /y "$(STATIC_LIB)" "$(INSTALLDIR)/lib\"
+	-xcopy /i /y "$(IMPORT_LIB)" "$(INSTALLDIR)/lib\"
+	-xcopy /i /y "libdeflate.h" "$(INSTALLDIR)/include\"
