diff --git a/Makefile.msc b/Makefile.msc
index 901131d..f47cc6f 100644
--- a/Makefile.msc
+++ b/Makefile.msc
@@ -10,7 +10,7 @@
 CC = cl
 LD = link
 AR = lib
-CFLAGS = /MD /O2 -I. -Icommon
+CFLAGS = $(CL_FLAGS) -I. -Icommon
 LDFLAGS =
 
 STATIC_LIB = libdeflatestatic.lib
@@ -60,6 +60,6 @@ gunzip.exe:gzip.exe
 	copy $** $@
 
 clean:
-	-del *.dll *.exe *.exp libdeflate.lib libdeflatestatic.lib gzip.lib \
-		lib\*.obj lib\*\*.obj lib\*.dllobj lib\*\*.dllobj \
-		programs\*.obj 2>nul
+	-del /s /q *.dll *.exe *.exp libdeflate.lib libdeflatestatic.lib gzip.lib \
+		lib\*.obj lib\*.dllobj \
+		programs\*.obj >nul 2>&1
