function(vcpkg_replace_strings)
    cmake_parse_arguments(PARSE_ARGV 0 arg "" "" "IF_EXIST;FILES;REGEX_REPLACE;REPLACE")

    if(DEFINED arg_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION} was passed extra arguments: ${arg_UNPARSED_ARGUMENTS}")
    endif()

    if(NOT DEFINED arg_FILES AND NOT DEFINED arg_IF_EXIST)
        message(FATAL_ERROR "FILES or IF_EXIST must be specified")
    endif()

    foreach(param REPLACE "REGEX_REPLACE")
        list(LENGTH arg_${REPLACE} length)
        math(EXPR length_mod2 "${length} % 2")
        if(length_mod2 EQUAL 1)
            message(FATAL_ERROR "${param} must contain an even number of elements")
        endif()
    endforeach()

    function(_replace_in_file file)
        file(READ "${file}" file_contents)
        foreach(param REPLACE "REGEX_REPLACE")
            message(STATUS "param: ${arg_${param}}")
            if(NOT arg_${param})
                continue()
            endif()
            list(LENGTH "arg_${param}" length)
            math(EXPR length "${length} - 1")
            foreach(i RANGE 0 ${length} 2)
                list(GET "arg_${param}" ${i} from)
                math(EXPR i_plus_one "${i} + 1")
                list(GET "arg_${param}" ${i_plus_one} to)
                string(REPLACE "_" ";" param "${param}")
                string(${param} "${from}" "${to}" file_contents "${file_contents}")
            endforeach()
        endforeach()
        file(WRITE "${file}" "${file_contents}")
    endfunction()
    
    foreach(file IN LISTS arg_FILES)
        if(NOT EXISTS "${file}")
            message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION} was passed a non-existing path: ${file}")
        endif()
        _replace_in_file("${file}")
    endforeach()

    foreach(file IN LISTS arg_IF_EXIST)
        if(EXISTS "${file}")
            _replace_in_file("${file}")
        endif()
    endforeach()

endfunction()
