function(vcpkg_remove_empty_dirs dir)
    file(GLOB entries "${dir}/*")
    file(GLOB not_removed LIST_DIRECTORIES false "${dir}/*")
    list(REMOVE_ITEM entries ${not_removed})
    foreach(entry IN LISTS entries)
        vcpkg_remove_empty_dirs("${entry}")
        if(EXISTS "${entry}")
            set(not_removed "${entry}")
        endif()
    endforeach()
    if(not_removed STREQUAL "")
        file(REMOVE_RECURSE "${dir}")
    endif()
endfunction()
