# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/compatibility
    REF boost-1.69.0
    SHA512 2bac082f818b9138c529089751aea29d3848b90ee213ca58639667b3ffb8fa93235d4d5b3bc248f36dfa8fe79a30fc1f4628adc2637f09df1e0fac7b45e0a893
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
