message(WARNING "find_package(CoinUtils) is deprecated. Use pkg-config instead.")
find_package(PkgConfig QUIET)
if(NOT PKG_CONFIG_FOUND AND "@VCPKG_CROSSCOMPILING@")
    find_program(PKG_CONFIG_EXECUTABLE NAMES pkgconf PATH_SUFFIXES "../@HOST_TRIPLET@/tools/pkgconf")
    include(CMakeFindDependencyMacro)
    find_dependency(PkgConfig)
endif()
pkg_check_modules(Z_VCPKG_COINUTILS coinutils IMPORTED_TARGET)
set(CoinUtils_FOUND "${Z_VCPKG_COINUTILS_FOUND}")
if(CoinUtils_FOUND AND NOT TARGET Coin::CoinUtils)
    add_library(Coin::CoinUtils INTERFACE IMPORTED)
    set_target_properties(Coin::CoinUtils PROPERTIES INTERFACE_LINK_LIBRARIES PkgConfig::Z_VCPKG_COINUTILS)
endif()
