message(WARNING "find_package(CoinUtils) is deprecated. Use pkg-config instead.")
include(CMakeFindDependencyMacro)
find_dependency(PkgConfig)
pkg_check_modules(Z_VCPKG_COINUTILS coinutils IMPORTED_TARGET)
set(CoinUtils_FOUND "${Z_VCPKG_COINUTILS_FOUND}")
if(CoinUtils_FOUND AND NOT TARGET Coin::CoinUtils)
    add_library(Coin::CoinUtils INTERFACE IMPORTED)
    set_target_properties(Coin::CoinUtils PROPERTIES INTERFACE_LINK_LIBRARIES PkgConfig::Z_VCPKG_COINUTILS)
endif()
