include(FindPackageHandleStandardArgs)
include(SelectLibraryConfigurations)
include(CMakeFindDependencyMacro)

find_path(LIBIDN2_INCLUDE_DIR NAMES idn2.h PATHS ${CURRENT_INSTALLED_DIR}/include NO_DEFAULT_PATH)

find_library(LIBIDN2_LIBRARY_DEBUG NAMES libidn2 idn2 NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug" NO_DEFAULT_PATH REQUIRED)
find_library(LIBIDN2_LIBRARY_RELEASE NAMES libidn2 idn2 NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" NO_DEFAULT_PATH REQUIRED)

select_library_configurations(LIBIDN2)

find_dependency(Iconv)

set(LIBIDN2_INCLUDE_DIRS ${LIBIDN2_INCLUDE_DIR} ${Iconv_INCLUDE_DIRS})
set(LIBIDN2_LIBRARIES ${LIBIDN2_LIBRARY} ${Iconv_LIBRARIES})
