vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO libtcod/libtcod
    REF ${VERSION}
    SHA512 e10d6d83e6057336efcc3f2a45dd7d2e287217c3c42f99f594a357668bac89dd8a235d8498d879168418c3b5fc1a3cb5ae2c9e0acadf4e3f95e247da3ab4de40
    HEAD_REF main
)

vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
        "png" LIBTCOD_LODEPNG
        "sdl" LIBTCOD_SDL3
        "threads" LIBTCOD_THREADS
        "unicode" LIBTCOD_UTF8PROC
        "zlib" LIBTCOD_ZLIB
    INVERTED_FEATURES
        "png" CMAKE_DISABLE_FIND_PACKAGE_lodepng-c
        "sdl" CMAKE_DISABLE_FIND_PACKAGE_SDL3
        "threads" CMAKE_DISABLE_FIND_PACKAGE_Threads
        "unicode" CMAKE_DISABLE_FIND_PACKAGE_utf8proc
        "zlib" CMAKE_DISABLE_FIND_PACKAGE_ZLIB
)

vcpkg_cmake_configure(
    SOURCE_PATH ${SOURCE_PATH}
    OPTIONS
        ${FEATURE_OPTIONS}
        -DCMAKE_INSTALL_INCLUDEDIR=${CURRENT_PACKAGES_DIR}/include
        -DFETCHCONTENT_FULLY_DISCONNECTED=ON
        -DCMAKE_REQUIRE_FIND_PACKAGE_lodepng-c=ON
        -DCMAKE_REQUIRE_FIND_PACKAGE_Stb=ON
        -DCMAKE_REQUIRE_FIND_PACKAGE_SDL3=ON
        -DCMAKE_REQUIRE_FIND_PACKAGE_utf8proc=ON
        -DCMAKE_REQUIRE_FIND_PACKAGE_ZLIB=ON
    MAYBE_UNUSED_VARIABLES
        CMAKE_DISABLE_FIND_PACKAGE_SDL3
        CMAKE_DISABLE_FIND_PACKAGE_Threads
        CMAKE_DISABLE_FIND_PACKAGE_ZLIB
        CMAKE_DISABLE_FIND_PACKAGE_lodepng-c
        CMAKE_DISABLE_FIND_PACKAGE_utf8proc
        CMAKE_REQUIRE_FIND_PACKAGE_SDL3
        CMAKE_REQUIRE_FIND_PACKAGE_ZLIB
        CMAKE_REQUIRE_FIND_PACKAGE_lodepng-c
        CMAKE_REQUIRE_FIND_PACKAGE_utf8proc
)

vcpkg_cmake_install()

vcpkg_copy_pdbs()

vcpkg_cmake_config_fixup()

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")
