set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME iOS)
set(VCPKG_OSX_ARCHITECTURES arm64)

set(VCPKG_CMAKE_OSX_ARCHITECTURES arm64)

set(VCPKG_ENV_PASSTHROUGH_UNTRACKED VCPKG_ROOT)

set(VCPKG_BUILD_TYPE debug)
