set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

set(VCPKG_POST_BUILD_SCRIPTS "${SCRIPTS}/cmake/z_vcpkg_fixup_rpath.cmake")
