include(FindPackageHandleStandardArgs)
include(SelectLibraryConfigurations)

find_path(FREEIMAGE_INCLUDE_DIR FreeImage.h)

find_library(FREEIMAGE_LIBRARY_DEBUG NAMES FreeImaged libFreeImaged NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug" NO_DEFAULT_PATH REQUIRED)
find_library(FREEIMAGE_LIBRARY_RELEASE NAMES FreeImage libFreeImage NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" NO_DEFAULT_PATH REQUIRED)
find_library(FREEIMAGEPLUS_LIBRARY_DEBUG NAMES FreeImagePlusd libFreeImagePlusd NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug" NO_DEFAULT_PATH REQUIRED)
find_library(FREEIMAGEPLUS_LIBRARY_RELEASE NAMES FreeImagePlus libFreeImagePlus NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" NO_DEFAULT_PATH REQUIRED)

select_library_configurations(FREEIMAGE)
select_library_configurations(FREEIMAGEPLUS)

set(FREEIMAGE_INCLUDE_DIRS ${FREEIMAGE_INCLUDE_DIR})
set(FREEIMAGE_LIBRARIES ${FREEIMAGE_LIBRARY} ${FREEIMAGEPLUS_LIBRARY})