include(FindPackageHandleStandardArgs)
include(SelectLibraryConfigurations)

find_path(EVPP_INCLUDE_DIR libevent.h PATH_SUFFIXES evpp)
get_filename_component(EVPP_INCLUDE_DIR ${EVPP_INCLUDE_DIR} DIRECTORY)

find_library(EVPP_LIBRARY_DEBUG NAMES evpp_static libevpp_static NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug" NO_DEFAULT_PATH REQUIRED)
find_library(EVPP_LIBRARY_RELEASE NAMES evpp_static libevpp_static NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" NO_DEFAULT_PATH REQUIRED)
find_library(EVMC_LIBRARY_DEBUG NAMES evmc_static libevmc_static NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug" NO_DEFAULT_PATH REQUIRED)
find_library(EVMC_LIBRARY_RELEASE NAMES evmc_static libevmc_static NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" NO_DEFAULT_PATH REQUIRED)
find_library(EVNSQ_LIBRARY_DEBUG NAMES evnsq_static libevnsq_static NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug" NO_DEFAULT_PATH REQUIRED)
find_library(EVNSQ_LIBRARY_RELEASE NAMES evnsq_static libevnsq_static NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" NO_DEFAULT_PATH REQUIRED)
find_library(EVPPLITE_LIBRARY_DEBUG NAMES evpp_lite_static libevpp_lite_static NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug" NO_DEFAULT_PATH REQUIRED)
find_library(EVPPLITE_LIBRARY_RELEASE NAMES evpp_lite_static libevpp_lite_static NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" NO_DEFAULT_PATH REQUIRED)

select_library_configurations(EVPP)
select_library_configurations(EVMC)
select_library_configurations(EVNSQ)
select_library_configurations(EVPPLITE)

set(EVPP_INCLUDE_DIRS ${EVPP_INCLUDE_DIR})
set(EVPP_LIBRARIES ${EVPP_LIBRARY} ${EVMC_LIBRARY} ${EVNSQ_LIBRARY} ${EVPPLITE_LIBRARY})