vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO vsg-dev/vsgPoints
    REF "v${VERSION}"
    SHA512 ca9fd8f54e13f0f64ef46d9d3ddd7bae5e95f879c9c3a9b4da8f101e4292711e20d7e31f11c1911fc0f066654b0ef63eec69b28ccf3eaeaa4c5ccb8be307c36b
    HEAD_REF master
)
file(WRITE "${SOURCE_PATH}/applications/CMakeLists.txt" "# skipped by vcpkg\n")

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
)

vcpkg_cmake_install()
vcpkg_cmake_config_fixup(
    PACKAGE_NAME vsgPoints
    CONFIG_PATH lib/cmake/vsgPoints
)
vcpkg_copy_pdbs()

vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/share/vsgpoints/vsgPointsConfig.cmake"
    "#generated by cmake, do not change" [[
include(CMakeFindDependencyMacro)
find_dependency(vsg)
find_dependency(vsgxchange)
]])

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE.md")
