# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/stl_interfaces
    REF boost-${VERSION}
    SHA512 b6dc2db015e3586647ec0d5f11366fd76d0e313ab178ef89360b962ea9f0d9e2930f850b7a66ae3d6796254f1466170c6f9765a4b17d1c55a468246b30e6aa58
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
