# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/stl_interfaces
    REF boost-${VERSION}
    SHA512 c55428152fe69d7046d0c2a8c22c90c60cfc08f196312b85a9969686075455353129986cabf8d5a26c1cbc73f6ffd5ae65f6b75ad3de728145e34a37b57da6e8
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
