if("disable-nagles" IN_LIST FEATURES)
    add_compile_definitions(TGBOT_DISABLE_NAGLES_ALGORITHM)
endif()
if("expand-read" IN_LIST FEATURES)
    add_compile_definitions(TGBOT_CHANGE_READ_BUFFER_SIZE)
endif()
if("expand-socket" IN_LIST FEATURES)
    add_compile_definitions(TGBOT_CHANGE_SOCKET_BUFFER_SIZE)
endif()
