if(NOT WIN32)
    set(VCPKG_CMAKE_PREFIX_PATH_BACKUP "${CMAKE_PREFIX_PATH}")
    set(VCPKG_CMAKE_LIBRARY_PATH_BACKUP "${CMAKE_LIBRARY_PATH}")

    # Remove vcpkg paths.
    list(FILTER CMAKE_PREFIX_PATH EXCLUDE REGEX "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}")
    list(FILTER CMAKE_LIBRARY_PATH EXCLUDE REGEX "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}")

    if(DEFINED CMAKE_FIND_USE_INSTALL_PREFIX)
        set(VCPKG_BACKUP_CMAKE_FIND_USE_INSTALL_PREFIX "${CMAKE_FIND_USE_INSTALL_PREFIX}")
    endif()
    set(CMAKE_FIND_USE_INSTALL_PREFIX OFF)
    _find_package(${ARGS})
    if(DEFINED VCPKG_BACKUP_CMAKE_FIND_USE_INSTALL_PREFIX)
        set(CMAKE_FIND_USE_INSTALL_PREFIX "${VCPKG_BACKUP_CMAKE_FIND_USE_INSTALL_PREFIX}")
        unset(VCPKG_BACKUP_CMAKE_FIND_USE_INSTALL_PREFIX)
    else()
        unset(CMAKE_FIND_USE_INSTALL_PREFIX)
    endif()

    #Restore
    set(CMAKE_PREFIX_PATH "${VCPKG_CMAKE_PREFIX_PATH_BACKUP}")
    set(CMAKE_LIBRARY_PATH "${VCPKG_CMAKE_LIBRARY_PATH_BACKUP}")
    unset(VCPKG_CMAKE_PREFIX_PATH_BACKUP)
    unset(VCPKG_CMAKE_LIBRARY_PATH_BACKUP)
else()
    _find_package(${ARGS})
endif()

