if(NOT WIN32)
    set(VCPKG_CMAKE_PREFIX_PATH_BACKUP "${CMAKE_PREFIX_PATH}")
    set(VCPKG_CMAKE_LIBRARY_PATH_BACKUP "${CMAKE_LIBRARY_PATH}")

    # Remove vcpkg paths.
    list(FILTER CMAKE_PREFIX_PATH EXCLUDE REGEX "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}")
    list(FILTER CMAKE_LIBRARY_PATH EXCLUDE REGEX "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}")

    _find_package(${ARGS})

    #Restore
    set(CMAKE_PREFIX_PATH "${VCPKG_CMAKE_PREFIX_PATH_BACKUP}")
    set(CMAKE_LIBRARY_PATH "${VCPKG_CMAKE_LIBRARY_PATH_BACKUP}")
    unset(VCPKG_CMAKE_PREFIX_PATH_BACKUP)
    unset(VCPKG_CMAKE_LIBRARY_PATH_BACKUP)
else()
    _find_package(${ARGS})
endif()

