_find_package(unofficial-GIF CONFIG REQUIRED)

get_filename_component(GIF_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}" PATH)
get_filename_component(GIF_INCLUDE_DIRS "${GIF_INCLUDE_DIRS}" PATH)

set(GIF_FOUND TRUE)
set(GIF_INCLUDE_DIRS "${GIF_INCLUDE_DIRS}/include")
set(GIF_LIBRARIES GIF::GIF)
set(GIF_VERSION @GIFLIB_VERSION@)
