# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/smart_ptr
    REF boost-1.78.0
    SHA512 96f5d910dae54441d8d85ffab6a3dc3711ebb69325152a16185822e95be683548575f8074b13b64123da5ec6ca666ca33f26984c931fd642b8c9373ed682181e
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
