set(PYTHON3_VERSION "@VERSION@")
set(PYTHON3_VERSION_MAJOR "@PYTHON_VERSION_MAJOR@")
set(PYTHON3_VERSION_MINOR "@PYTHON_VERSION_MINOR@")
set(PYTHON3_INCLUDE "include/python${PYTHON3_VERSION_MAJOR}.${PYTHON3_VERSION_MINOR}")
set(PYTHON3_ALLOW_EXTENSIONS "@PYTHON_ALLOW_EXTENSIONS@")
set(site_base "")
if(VCPKG_TARGET_IS_WINDOWS)
  set(site_base "tools/python${PYTHON3_VERSION_MAJOR}/Lib")
else()
  set(site_base "lib/python${PYTHON3_VERSION_MAJOR}.${PYTHON3_VERSION_MINOR}")
endif()
set(PYTHON3_SITE "${site_base}/site-packages")

function(error_if_python3_cannot_have_shared_extensions)
  if(NOT PYTHON3_ALLOW_EXTENSIONS AND VCPKG_TARGET_IS_WINDOWS)
    message(FATAL_ERROR "Dynamic python3 extensions on Windows can only be build against a dynamic python3 library!")
  endif()
endfunction()
