_find_package(${ARGS})
if(TARGET X11:X11 AND TARGET X11::xcb)
    target_link_libraries(X11::X11 INTERFACE X11:xcb)
endif()
if(TARGET X11::xcb)
    if(TARGET X11::Xdmcp)
        target_link_libraries(X11::xcb INTERFACE X11::Xdmcp)
    endif()
    if(TARGET X11::Xau)
        target_link_libraries(X11::xcb INTERFACE X11::Xau)
    endif()
endif()
