vcpkg_download_distfile(ARCHIVE
	# The official URL shuts down every night for maintainance, using package from Citic Futures 
    URLS "https://www.citicsf.com/Static/download/soft/%E7%9C%8B%E7%A9%BF%E5%BC%8F%E6%B5%8B%E8%AF%95/CTP%E7%9C%8B%E7%A9%BF%E5%BC%8F_API/traderap_6.3.15i.rar"
    FILENAME "traderap_6.3.15i.rar"
    SHA512 a79668cb3769ad2f79555e3bc57d7a7ac42b44c5e707756f11033091302bdae41cde1fd2288b4743af8b0a7e74fc2047b5fc88db8756f796ac5a22b327d3c899    
)

vcpkg_extract_source_archive_ex(
    OUT_SOURCE_PATH UNPACK_PATH
    ARCHIVE ${ARCHIVE}
)

if(${TARGET_TRIPLET} STREQUAL "x86-windows")
    set(ARCH_ARCHIVE "6.3.15_20190220_tradeapi_se_windows.zip")
    set(ARCH_ARCHIVE_DATACOLLECT "6.3.15_20190220_clientdll_windows.zip")
elseif(${TARGET_TRIPLET} STREQUAL "x64-windows")
    set(ARCH_ARCHIVE "6.3.15_20190220_tradeapi64_se_windows.zip")
    set(ARCH_ARCHIVE_DATACOLLECT "6.3.15_20190220_clientdll64_windows.zip")
elseif(${TARGET_TRIPLET} STREQUAL "x64-linux")
    set(ARCH_ARCHIVE "v6.3.15_20190220_api_clientdatacollectdll_linux64.tar")
    set(ARCH_ARCHIVE_DATACOLLECT "6.3.15_20190220_clientdll_windows.zip")
else()
    message(FATAL_ERROR "${TARGET_TRIPLET} is not supported" )
endif()

vcpkg_extract_source_archive_ex(
    OUT_SOURCE_PATH SOURCE_PATH
    ARCHIVE "${UNPACK_PATH}/${ARCH_ARCHIVE}"
)

file(INSTALL ${SOURCE_PATH}/ DESTINATION ${CURRENT_PACKAGES_DIR}/include FILES_MATCHING PATTERN "*.h")

if(${VCPKG_TARGET_IS_WINDOWS})
    file(INSTALL ${SOURCE_PATH}/ DESTINATION ${CURRENT_PACKAGES_DIR}/lib FILES_MATCHING PATTERN "*.lib")
    file(INSTALL ${SOURCE_PATH}/ DESTINATION ${CURRENT_PACKAGES_DIR}/bin FILES_MATCHING PATTERN "*.dll")
    file(INSTALL ${SOURCE_PATH}/ DESTINATION ${CURRENT_PACKAGES_DIR}/Debug/lib FILES_MATCHING PATTERN "*.lib")
    file(INSTALL ${SOURCE_PATH}/ DESTINATION ${CURRENT_PACKAGES_DIR}/Debug/bin FILES_MATCHING PATTERN "*.dll")
elseif(${VCPKG_TARGET_IS_LINUX})
    file(INSTALL ${SOURCE_PATH}/ DESTINATION ${CURRENT_PACKAGES_DIR}/lib FILES_MATCHING PATTERN "*.so")
    file(INSTALL ${SOURCE_PATH}/ DESTINATION ${CURRENT_PACKAGES_DIR}/Debug/lib FILES_MATCHING PATTERN "*.so")
endif()

file(INSTALL ${SOURCE_PATH}/ DESTINATION ${CURRENT_PACKAGES_DIR}/share FILES_MATCHING PATTERN "*.xml")
file(INSTALL ${SOURCE_PATH}/ DESTINATION ${CURRENT_PACKAGES_DIR}/share FILES_MATCHING PATTERN "*.dtd")

if("datacollect" IN_LIST FEATURES)
    vcpkg_extract_source_archive_ex(
        OUT_SOURCE_PATH SOURCE_PATH_DATACOLLECT
        ARCHIVE "${UNPACK_PATH}/${ARCH_ARCHIVE_DATACOLLECT}"
    )
    file(INSTALL ${SOURCE_PATH_DATACOLLECT}/ DESTINATION ${CURRENT_PACKAGES_DIR}/include FILES_MATCHING PATTERN "*.h")

    if(${VCPKG_TARGET_IS_WINDOWS})
        file(INSTALL ${SOURCE_PATH_DATACOLLECT}/ DESTINATION ${CURRENT_PACKAGES_DIR}/lib FILES_MATCHING PATTERN "*.lib")
        file(INSTALL ${SOURCE_PATH_DATACOLLECT}/ DESTINATION ${CURRENT_PACKAGES_DIR}/bin FILES_MATCHING PATTERN "*.dll")
        file(INSTALL ${SOURCE_PATH_DATACOLLECT}/ DESTINATION ${CURRENT_PACKAGES_DIR}/Debug/lib FILES_MATCHING PATTERN "*.lib")
        file(INSTALL ${SOURCE_PATH_DATACOLLECT}/ DESTINATION ${CURRENT_PACKAGES_DIR}/Debug/bin FILES_MATCHING PATTERN "*.dll")
    elseif(${VCPKG_TARGET_IS_LINUX})
        file(INSTALL ${SOURCE_PATH_DATACOLLECT}/ DESTINATION ${CURRENT_PACKAGES_DIR}/lib FILES_MATCHING PATTERN "*.so")
        file(INSTALL ${SOURCE_PATH_DATACOLLECT}/ DESTINATION ${CURRENT_PACKAGES_DIR}/Debug/lib FILES_MATCHING PATTERN "*.so")
    endif()
    
endif()

file(WRITE ${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright "Copyright By Shanghai Futures Information Technology Co.,Ltd")
