# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/interval
    REF boost-1.80.0.beta1
    SHA512 599f1b0cd291627228b56abf6df98083d0fbbba8c14bb2b1978b74a62024831ec78347abfd2b249bcf57cb3735a7d1081130c16215c09aa93b955936e34cb957
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
