# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/serialization
    REF boost-${VERSION}
    SHA512 7bf9632023cac688a5064addce811b230b6fd946e68822525fe63fb3a0652c590b30ad7e00f158eec438daf727a5c014621aced748a8539b3311a50b28947f96
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
