# This file is a shell script that caches the results of configure
ac_cv_c_bigendian=${ac_cv_c_bigendian=no}
ac_cv_c_compiler_gnu=${ac_cv_c_compiler_gnu=yes}
ac_cv_c_flexmember=${ac_cv_c_flexmember=yes}
ac_cv_c_restrict=${ac_cv_c_restrict=__restrict__}
ac_cv_c_undeclared_builtin_options=${ac_cv_c_undeclared_builtin_options='none needed'}
ac_cv_c_vararrays=${ac_cv_c_vararrays=yes}
ac_cv_cxx_compiler_gnu=${ac_cv_cxx_compiler_gnu=yes}
ac_cv_exeext=${ac_cv_exeext=.exe}
ac_cv_func__NSGetExecutablePath=${ac_cv_func__NSGetExecutablePath=no}
ac_cv_func___fpurge=${ac_cv_func___fpurge=no}
ac_cv_func___freading=${ac_cv_func___freading=no}
ac_cv_func___fsetlocking=${ac_cv_func___fsetlocking=no}
ac_cv_func___secure_getenv=${ac_cv_func___secure_getenv=no}
ac_cv_func___xpg_strerror_r=${ac_cv_func___xpg_strerror_r=no}
ac_cv_func__chsize=${ac_cv_func__chsize=yes}
ac_cv_func__fseeki64=${ac_cv_func__fseeki64=yes}
ac_cv_func__set_invalid_parameter_handler=${ac_cv_func__set_invalid_parameter_handler=yes}
ac_cv_func_alloca_works=${ac_cv_func_alloca_works=yes}
ac_cv_func_asprintf=${ac_cv_func_asprintf=yes}
ac_cv_func_atexit=${ac_cv_func_atexit=yes}
ac_cv_func_btowc=${ac_cv_func_btowc=yes}
ac_cv_func_canonicalize_file_name=${ac_cv_func_canonicalize_file_name=no}
ac_cv_func_catgets=${ac_cv_func_catgets=no}
ac_cv_func_chown=${ac_cv_func_chown=no}
ac_cv_func_clock_getres=${ac_cv_func_clock_getres=yes}
ac_cv_func_clock_gettime=${ac_cv_func_clock_gettime=yes}
ac_cv_func_clock_settime=${ac_cv_func_clock_settime=yes}
ac_cv_func_close_range=${ac_cv_func_close_range=no}
ac_cv_func_closedir=${ac_cv_func_closedir=yes}
ac_cv_func_confstr=${ac_cv_func_confstr=no}
ac_cv_func_dirfd=${ac_cv_func_dirfd=no}
ac_cv_func_duplocale=${ac_cv_func_duplocale=no}
ac_cv_func_eaccess=${ac_cv_func_eaccess=no}
ac_cv_func_explicit_bzero=${ac_cv_func_explicit_bzero=no}
ac_cv_func_explicit_memset=${ac_cv_func_explicit_memset=no}
ac_cv_func_faccessat=${ac_cv_func_faccessat=no}
ac_cv_func_fchdir=${ac_cv_func_fchdir=no}
ac_cv_func_fchmod=${ac_cv_func_fchmod=no}
ac_cv_func_fcntl=${ac_cv_func_fcntl=no}
ac_cv_func_fdopendir=${ac_cv_func_fdopendir=no}
ac_cv_func_flockfile=${ac_cv_func_flockfile=no}
ac_cv_func_fnmatch=${ac_cv_func_fnmatch=no}
ac_cv_func_fpurge=${ac_cv_func_fpurge=no}
ac_cv_func_freelocale=${ac_cv_func_freelocale=no}
ac_cv_func_fstatat=${ac_cv_func_fstatat=no}
ac_cv_func_fsync=${ac_cv_func_fsync=no}
ac_cv_func_ftruncate=${ac_cv_func_ftruncate=yes}
ac_cv_func_funlockfile=${ac_cv_func_funlockfile=no}
ac_cv_func_futimens=${ac_cv_func_futimens=no}
ac_cv_func_futimes=${ac_cv_func_futimes=no}
ac_cv_func_futimesat=${ac_cv_func_futimesat=no}
ac_cv_func_getaddrinfo=${ac_cv_func_getaddrinfo=no}
ac_cv_func_getcwd=${ac_cv_func_getcwd=yes}
ac_cv_func_getdelim=${ac_cv_func_getdelim=no}
ac_cv_func_getdtablesize=${ac_cv_func_getdtablesize=no}
ac_cv_func_getegid=${ac_cv_func_getegid=no}
ac_cv_func_geteuid=${ac_cv_func_geteuid=no}
ac_cv_func_getexecname=${ac_cv_func_getexecname=no}
ac_cv_func_getgid=${ac_cv_func_getgid=no}
ac_cv_func_gethostbyname=${ac_cv_func_gethostbyname=no}
ac_cv_func_gethostname=${ac_cv_func_gethostname=no}
ac_cv_func_getline=${ac_cv_func_getline=no}
ac_cv_func_getopt_long_only=${ac_cv_func_getopt_long_only=yes}
ac_cv_func_getpagesize=${ac_cv_func_getpagesize=yes}
ac_cv_func_getppriv=${ac_cv_func_getppriv=no}
ac_cv_func_getprogname=${ac_cv_func_getprogname=no}
ac_cv_func_getrandom=${ac_cv_func_getrandom=no}
ac_cv_func_getrlimit=${ac_cv_func_getrlimit=no}
ac_cv_func_getsid=${ac_cv_func_getsid=no}
ac_cv_func_gettimeofday=${ac_cv_func_gettimeofday=yes}
ac_cv_func_getuid=${ac_cv_func_getuid=no}
ac_cv_func_inet_ntop=${ac_cv_func_inet_ntop=no}
ac_cv_func_isascii=${ac_cv_func_isascii=yes}
ac_cv_func_isblank=${ac_cv_func_isblank=yes}
ac_cv_func_issetugid=${ac_cv_func_issetugid=no}
ac_cv_func_iswblank=${ac_cv_func_iswblank=yes}
ac_cv_func_iswcntrl=${ac_cv_func_iswcntrl=yes}
ac_cv_func_iswctype=${ac_cv_func_iswctype=yes}
ac_cv_func_localtime=${ac_cv_func_localtime=yes}
ac_cv_func_lstat=${ac_cv_func_lstat=no}
ac_cv_func_lutimes=${ac_cv_func_lutimes=no}
ac_cv_func_malloc_0_nonnull=${ac_cv_func_malloc_0_nonnull=yes}
ac_cv_func_mbrlen=${ac_cv_func_mbrlen=yes}
ac_cv_func_mbrtowc=${ac_cv_func_mbrtowc=yes}
ac_cv_func_mbsinit=${ac_cv_func_mbsinit=yes}
ac_cv_func_mbslen=${ac_cv_func_mbslen=no}
ac_cv_func_mbsrtowcs=${ac_cv_func_mbsrtowcs=yes}
ac_cv_func_mbtowc=${ac_cv_func_mbtowc=yes}
ac_cv_func_memmove=${ac_cv_func_memmove=yes}
ac_cv_func_mempcpy=${ac_cv_func_mempcpy=yes}
ac_cv_func_memrchr=${ac_cv_func_memrchr=no}
ac_cv_func_memset=${ac_cv_func_memset=yes}
ac_cv_func_memset_s=${ac_cv_func_memset_s=no}
ac_cv_func_mkdtemp=${ac_cv_func_mkdtemp=no}
ac_cv_func_mmap=${ac_cv_func_mmap=no}
ac_cv_func_mmap_fixed_mapped=${ac_cv_func_mmap_fixed_mapped=no}
ac_cv_func_mprotect=${ac_cv_func_mprotect=yes}
ac_cv_func_mquery=${ac_cv_func_mquery=no}
ac_cv_func_munmap=${ac_cv_func_munmap=no}
ac_cv_func_newlocale=${ac_cv_func_newlocale=no}
ac_cv_func_nl_langinfo=${ac_cv_func_nl_langinfo=no}
ac_cv_func_obstack=${ac_cv_func_obstack=no}
ac_cv_func_openat=${ac_cv_func_openat=no}
ac_cv_func_opendir=${ac_cv_func_opendir=yes}
ac_cv_func_pathconf=${ac_cv_func_pathconf=no}
ac_cv_func_pipe2=${ac_cv_func_pipe2=no}
ac_cv_func_pipe=${ac_cv_func_pipe=no}
ac_cv_func_posix_spawn=${ac_cv_func_posix_spawn=no}
ac_cv_func_posix_spawn_file_actions_addchdir=${ac_cv_func_posix_spawn_file_actions_addchdir=no}
ac_cv_func_posix_spawn_file_actions_addchdir_np=${ac_cv_func_posix_spawn_file_actions_addchdir_np=no}
ac_cv_func_pstat_getprocvm=${ac_cv_func_pstat_getprocvm=no}
ac_cv_func_pthread_sigmask=${ac_cv_func_pthread_sigmask=no}
ac_cv_func_putenv=${ac_cv_func_putenv=yes}
ac_cv_func_raise=${ac_cv_func_raise=yes}
ac_cv_func_rawmemchr=${ac_cv_func_rawmemchr=no}
ac_cv_func_readdir=${ac_cv_func_readdir=yes}
ac_cv_func_readlink=${ac_cv_func_readlink=no}
ac_cv_func_readlinkat=${ac_cv_func_readlinkat=no}
ac_cv_func_realloc_0_nonnull=${ac_cv_func_realloc_0_nonnull=yes}
ac_cv_func_reallocarray=${ac_cv_func_reallocarray=no}
ac_cv_func_realpath=${ac_cv_func_realpath=no}
ac_cv_func_rewinddir=${ac_cv_func_rewinddir=yes}
ac_cv_func_sched_setparam=${ac_cv_func_sched_setparam=no}
ac_cv_func_sched_setscheduler=${ac_cv_func_sched_setscheduler=yes}
ac_cv_func_secure_getenv=${ac_cv_func_secure_getenv=no}
ac_cv_func_select=${ac_cv_func_select=no}
ac_cv_func_setdtablesize=${ac_cv_func_setdtablesize=no}
ac_cv_func_setegid=${ac_cv_func_setegid=no}
ac_cv_func_setenv=${ac_cv_func_setenv=no}
ac_cv_func_seteuid=${ac_cv_func_seteuid=no}
ac_cv_func_setlocale=${ac_cv_func_setlocale=yes}
ac_cv_func_setrlimit=${ac_cv_func_setrlimit=no}
ac_cv_func_shutdown=${ac_cv_func_shutdown=no}
ac_cv_func_sigaction=${ac_cv_func_sigaction=no}
ac_cv_func_sigaltstack=${ac_cv_func_sigaltstack=no}
ac_cv_func_siginterrupt=${ac_cv_func_siginterrupt=no}
ac_cv_func_sleep=${ac_cv_func_sleep=yes}
ac_cv_func_snprintf=${ac_cv_func_snprintf=yes}
ac_cv_func_stat=${ac_cv_func_stat=yes}
ac_cv_func_stpcpy=${ac_cv_func_stpcpy=no}
ac_cv_func_stpncpy=${ac_cv_func_stpncpy=no}
ac_cv_func_strcasecmp=${ac_cv_func_strcasecmp=yes}
ac_cv_func_strchrnul=${ac_cv_func_strchrnul=no}
ac_cv_func_strcspn=${ac_cv_func_strcspn=yes}
ac_cv_func_strerror_r=${ac_cv_func_strerror_r=no}
ac_cv_func_strerror_r_char_p=${ac_cv_func_strerror_r_char_p=no}
ac_cv_func_strftime=${ac_cv_func_strftime=yes}
ac_cv_func_strnlen=${ac_cv_func_strnlen=yes}
ac_cv_func_strnlen_working=${ac_cv_func_strnlen_working=yes}
ac_cv_func_strpbrk=${ac_cv_func_strpbrk=yes}
ac_cv_func_strtol=${ac_cv_func_strtol=yes}
ac_cv_func_strtoul=${ac_cv_func_strtoul=yes}
ac_cv_func_symlink=${ac_cv_func_symlink=no}
ac_cv_func_tcdrain=${ac_cv_func_tcdrain=no}
ac_cv_func_tcgetattr=${ac_cv_func_tcgetattr=no}
ac_cv_func_tsearch=${ac_cv_func_tsearch=yes}
ac_cv_func_unsetenv=${ac_cv_func_unsetenv=no}
ac_cv_func_uselocale=${ac_cv_func_uselocale=no}
ac_cv_func_usleep=${ac_cv_func_usleep=yes}
ac_cv_func_utimensat=${ac_cv_func_utimensat=no}
ac_cv_func_vasnprintf=${ac_cv_func_vasnprintf=no}
ac_cv_func_vasprintf=${ac_cv_func_vasprintf=yes}
ac_cv_func_vfork=${ac_cv_func_vfork=no}
ac_cv_func_vsnprintf=${ac_cv_func_vsnprintf=yes}
ac_cv_func_waitid=${ac_cv_func_waitid=no}
ac_cv_func_wcrtomb=${ac_cv_func_wcrtomb=yes}
ac_cv_func_wcslen=${ac_cv_func_wcslen=yes}
ac_cv_func_wcsnlen=${ac_cv_func_wcsnlen=yes}
ac_cv_func_wctob=${ac_cv_func_wctob=yes}
ac_cv_func_wcwidth=${ac_cv_func_wcwidth=no}
ac_cv_func_wmempcpy=${ac_cv_func_wmempcpy=yes}
ac_cv_func_wprintf=${ac_cv_func_wprintf=yes}
ac_cv_gnu_library_2=${ac_cv_gnu_library_2=no}
ac_cv_have_decl___argv=${ac_cv_have_decl___argv=yes}
ac_cv_have_decl__fseeki64=${ac_cv_have_decl__fseeki64=yes}
ac_cv_have_decl__putenv=${ac_cv_have_decl__putenv=yes}
ac_cv_have_decl__snprintf=${ac_cv_have_decl__snprintf=yes}
ac_cv_have_decl__snwprintf=${ac_cv_have_decl__snwprintf=yes}
ac_cv_have_decl_alarm=${ac_cv_have_decl_alarm=no}
ac_cv_have_decl_clearerr_unlocked=${ac_cv_have_decl_clearerr_unlocked=no}
ac_cv_have_decl_dirfd=${ac_cv_have_decl_dirfd=no}
ac_cv_have_decl_ecvt=${ac_cv_have_decl_ecvt=yes}
ac_cv_have_decl_execvpe=${ac_cv_have_decl_execvpe=yes}
ac_cv_have_decl_fchdir=${ac_cv_have_decl_fchdir=no}
ac_cv_have_decl_fcloseall=${ac_cv_have_decl_fcloseall=yes}
ac_cv_have_decl_fcvt=${ac_cv_have_decl_fcvt=yes}
ac_cv_have_decl_fdopendir=${ac_cv_have_decl_fdopendir=no}
ac_cv_have_decl_feof_unlocked=${ac_cv_have_decl_feof_unlocked=no}
ac_cv_have_decl_ferror_unlocked=${ac_cv_have_decl_ferror_unlocked=no}
ac_cv_have_decl_fflush_unlocked=${ac_cv_have_decl_fflush_unlocked=no}
ac_cv_have_decl_fgets_unlocked=${ac_cv_have_decl_fgets_unlocked=no}
ac_cv_have_decl_fpurge=${ac_cv_have_decl_fpurge=no}
ac_cv_have_decl_fputc_unlocked=${ac_cv_have_decl_fputc_unlocked=no}
ac_cv_have_decl_fputs_unlocked=${ac_cv_have_decl_fputs_unlocked=no}
ac_cv_have_decl_fread_unlocked=${ac_cv_have_decl_fread_unlocked=no}
ac_cv_have_decl_frexpl=${ac_cv_have_decl_frexpl=yes}
ac_cv_have_decl_fseeko=${ac_cv_have_decl_fseeko=yes}
ac_cv_have_decl_ftello=${ac_cv_have_decl_ftello=yes}
ac_cv_have_decl_fwrite_unlocked=${ac_cv_have_decl_fwrite_unlocked=no}
ac_cv_have_decl_gcvt=${ac_cv_have_decl_gcvt=yes}
ac_cv_have_decl_getc_unlocked=${ac_cv_have_decl_getc_unlocked=no}
ac_cv_have_decl_getchar_unlocked=${ac_cv_have_decl_getchar_unlocked=no}
ac_cv_have_decl_getcwd=${ac_cv_have_decl_getcwd=yes}
ac_cv_have_decl_getdelim=${ac_cv_have_decl_getdelim=no}
ac_cv_have_decl_getdtablesize=${ac_cv_have_decl_getdtablesize=no}
ac_cv_have_decl_getline=${ac_cv_have_decl_getline=no}
ac_cv_have_decl_getpagesize=${ac_cv_have_decl_getpagesize=no}
ac_cv_have_decl_isblank=${ac_cv_have_decl_isblank=yes}
ac_cv_have_decl_isinf=${ac_cv_have_decl_isinf=yes}
ac_cv_have_decl_iswblank=${ac_cv_have_decl_iswblank=yes}
ac_cv_have_decl_ldexpl=${ac_cv_have_decl_ldexpl=yes}
ac_cv_have_decl_mbswidth=${ac_cv_have_decl_mbswidth=no}
ac_cv_have_decl_memrchr=${ac_cv_have_decl_memrchr=no}
ac_cv_have_decl_posix_spawn=${ac_cv_have_decl_posix_spawn=no}
ac_cv_have_decl_program_invocation_name=${ac_cv_have_decl_program_invocation_name=no}
ac_cv_have_decl_program_invocation_short_name=${ac_cv_have_decl_program_invocation_short_name=no}
ac_cv_have_decl_putc_unlocked=${ac_cv_have_decl_putc_unlocked=no}
ac_cv_have_decl_putchar_unlocked=${ac_cv_have_decl_putchar_unlocked=no}
ac_cv_have_decl_setenv=${ac_cv_have_decl_setenv=no}
ac_cv_have_decl_sleep=${ac_cv_have_decl_sleep=yes}
ac_cv_have_decl_snprintf=${ac_cv_have_decl_snprintf=yes}
ac_cv_have_decl_stpncpy=${ac_cv_have_decl_stpncpy=no}
ac_cv_have_decl_strdup=${ac_cv_have_decl_strdup=yes}
ac_cv_have_decl_strerror_r=${ac_cv_have_decl_strerror_r=no}
ac_cv_have_decl_strnlen=${ac_cv_have_decl_strnlen=yes}
ac_cv_have_decl_unsetenv=${ac_cv_have_decl_unsetenv=no}
ac_cv_have_decl_vsnprintf=${ac_cv_have_decl_vsnprintf=yes}
ac_cv_have_decl_wcsdup=${ac_cv_have_decl_wcsdup=yes}
ac_cv_have_decl_wcwidth=${ac_cv_have_decl_wcwidth=no}
ac_cv_header_arpa_inet_h=${ac_cv_header_arpa_inet_h=no}
ac_cv_header_arpa_nameser_h=${ac_cv_header_arpa_nameser_h=no}
ac_cv_header_bcrypt_h=${ac_cv_header_bcrypt_h=yes}
ac_cv_header_byteswap_h=${ac_cv_header_byteswap_h=no}
ac_cv_header_crtdefs_h=${ac_cv_header_crtdefs_h=yes}
ac_cv_header_ctype_h=${ac_cv_header_ctype_h=yes}
ac_cv_header_dirent_h=${ac_cv_header_dirent_h=yes}
ac_cv_header_dl_h=${ac_cv_header_dl_h=no}
ac_cv_header_dlfcn_h=${ac_cv_header_dlfcn_h=no}
ac_cv_header_errno_h=${ac_cv_header_errno_h=yes}
ac_cv_header_fcntl_h=${ac_cv_header_fcntl_h=yes}
ac_cv_header_features_h=${ac_cv_header_features_h=no}
ac_cv_header_float_h=${ac_cv_header_float_h=yes}
ac_cv_header_fnmatch_h=${ac_cv_header_fnmatch_h=no}
ac_cv_header_getopt_h=${ac_cv_header_getopt_h=yes}
ac_cv_header_iconv_h=${ac_cv_header_iconv_h=yes}
ac_cv_header_inttypes_h=${ac_cv_header_inttypes_h=yes}
ac_cv_header_langinfo_h=${ac_cv_header_langinfo_h=no}
ac_cv_header_libintl_h=${ac_cv_header_libintl_h=yes}
ac_cv_header_libxml2_libxml_xmlexports_h=${ac_cv_header_libxml2_libxml_xmlexports_h=yes}
ac_cv_header_libxml2_libxml_xmlversion_h=${ac_cv_header_libxml2_libxml_xmlversion_h=no}
ac_cv_header_limits_h=${ac_cv_header_limits_h=yes}
ac_cv_header_mach_o_dyld_h=${ac_cv_header_mach_o_dyld_h=no}
ac_cv_header_malloc_h=${ac_cv_header_malloc_h=yes}
ac_cv_header_math_h=${ac_cv_header_math_h=yes}
ac_cv_header_minix_config_h=${ac_cv_header_minix_config_h=no}
ac_cv_header_netdb_h=${ac_cv_header_netdb_h=no}
ac_cv_header_netinet_in_h=${ac_cv_header_netinet_in_h=no}
ac_cv_header_paths_h=${ac_cv_header_paths_h=no}
ac_cv_header_priv_h=${ac_cv_header_priv_h=no}
ac_cv_header_pthread_h=${ac_cv_header_pthread_h=yes}
ac_cv_header_pwd_h=${ac_cv_header_pwd_h=no}
ac_cv_header_resolv_h=${ac_cv_header_resolv_h=no}
ac_cv_header_sched_h=${ac_cv_header_sched_h=yes}
ac_cv_header_sdkddkver_h=${ac_cv_header_sdkddkver_h=yes}
ac_cv_header_search_h=${ac_cv_header_search_h=yes}
ac_cv_header_semaphore_h=${ac_cv_header_semaphore_h=yes}
ac_cv_header_signal_h=${ac_cv_header_signal_h=yes}
ac_cv_header_spawn_h=${ac_cv_header_spawn_h=no}
ac_cv_header_stat_broken=${ac_cv_header_stat_broken=no}
ac_cv_header_stdbool_h=${ac_cv_header_stdbool_h=no}
ac_cv_header_stddef_h=${ac_cv_header_stddef_h=yes}
ac_cv_header_stdint_h=${ac_cv_header_stdint_h=yes}
ac_cv_header_stdio_ext_h=${ac_cv_header_stdio_ext_h=no}
ac_cv_header_stdio_h=${ac_cv_header_stdio_h=yes}
ac_cv_header_stdlib_h=${ac_cv_header_stdlib_h=yes}
ac_cv_header_string_h=${ac_cv_header_string_h=yes}
ac_cv_header_strings_h=${ac_cv_header_strings_h=yes}
ac_cv_header_sys_cdefs_h=${ac_cv_header_sys_cdefs_h=yes}
ac_cv_header_sys_ioctl_h=${ac_cv_header_sys_ioctl_h=no}
ac_cv_header_sys_mman_h=${ac_cv_header_sys_mman_h=no}
ac_cv_header_sys_param_h=${ac_cv_header_sys_param_h=yes}
ac_cv_header_sys_random_h=${ac_cv_header_sys_random_h=no}
ac_cv_header_sys_select_h=${ac_cv_header_sys_select_h=no}
ac_cv_header_sys_single_threaded_h=${ac_cv_header_sys_single_threaded_h=no}
ac_cv_header_sys_socket_h=${ac_cv_header_sys_socket_h=no}
ac_cv_header_sys_stat_h=${ac_cv_header_sys_stat_h=yes}
ac_cv_header_sys_time_h=${ac_cv_header_sys_time_h=yes}
ac_cv_header_sys_types_h=${ac_cv_header_sys_types_h=yes}
ac_cv_header_sys_uio_h=${ac_cv_header_sys_uio_h=no}
ac_cv_header_sys_wait_h=${ac_cv_header_sys_wait_h=no}
ac_cv_header_threads_h=${ac_cv_header_threads_h=no}
ac_cv_header_time_h=${ac_cv_header_time_h=yes}
ac_cv_header_unistd_h=${ac_cv_header_unistd_h=yes}
ac_cv_header_utime_h=${ac_cv_header_utime_h=yes}
ac_cv_header_wchar_h=${ac_cv_header_wchar_h=yes}
ac_cv_header_wctype_h=${ac_cv_header_wctype_h=yes}
ac_cv_header_winsock2_h=${ac_cv_header_winsock2_h=yes}
ac_cv_header_ws2tcpip_h=${ac_cv_header_ws2tcpip_h=yes}
ac_cv_header_xlocale_h=${ac_cv_header_xlocale_h=no}
ac_cv_lib_error_at_line=${ac_cv_lib_error_at_line=no}
ac_cv_lib_pthread_pthread_kill=${ac_cv_lib_pthread_pthread_kill=yes}
ac_cv_member_struct_lconv_decimal_point=${ac_cv_member_struct_lconv_decimal_point=yes}
ac_cv_member_struct_sockaddr_storage_ss_family=${ac_cv_member_struct_sockaddr_storage_ss_family=yes}
ac_cv_member_struct_stat_st_atim_st__tim_tv_nsec=${ac_cv_member_struct_stat_st_atim_st__tim_tv_nsec=no}
ac_cv_member_struct_stat_st_atim_tv_nsec=${ac_cv_member_struct_stat_st_atim_tv_nsec=no}
ac_cv_member_struct_stat_st_atimensec=${ac_cv_member_struct_stat_st_atimensec=no}
ac_cv_member_struct_stat_st_atimespec_tv_nsec=${ac_cv_member_struct_stat_st_atimespec_tv_nsec=no}
ac_cv_member_struct_stat_st_birthtim_tv_nsec=${ac_cv_member_struct_stat_st_birthtim_tv_nsec=no}
ac_cv_member_struct_stat_st_birthtimensec=${ac_cv_member_struct_stat_st_birthtimensec=no}
ac_cv_member_struct_stat_st_birthtimespec_tv_nsec=${ac_cv_member_struct_stat_st_birthtimespec_tv_nsec=no}
ac_cv_safe_to_define___extensions__=${ac_cv_safe_to_define___extensions__=yes}
ac_cv_search_clock_gettime=${ac_cv_search_clock_gettime='none required'}
ac_cv_search_nanosleep=${ac_cv_search_nanosleep='none required'}
ac_cv_search_posix_spawn=${ac_cv_search_posix_spawn=no}
ac_cv_should_define__xopen_source=${ac_cv_should_define__xopen_source=no}
ac_cv_sys_file_offset_bits=${ac_cv_sys_file_offset_bits=64}
ac_cv_sys_largefile_CC=${ac_cv_sys_largefile_CC=no}
ac_cv_sys_largefile_source=${ac_cv_sys_largefile_source=no}
ac_cv_sys_long_file_names=${ac_cv_sys_long_file_names=yes}
ac_cv_type__Bool=${ac_cv_type__Bool=yes}
ac_cv_type_long_long_int=${ac_cv_type_long_long_int=yes}
ac_cv_type_mbstate_t=${ac_cv_type_mbstate_t=yes}
ac_cv_type_mode_t=${ac_cv_type_mode_t=yes}
ac_cv_type_nlink_t=${ac_cv_type_nlink_t=no}
ac_cv_type_off_t=${ac_cv_type_off_t=yes}
ac_cv_type_pid_t=${ac_cv_type_pid_t=yes}
ac_cv_type_pthread_rwlock_t=${ac_cv_type_pthread_rwlock_t=yes}
ac_cv_type_pthread_spinlock_t=${ac_cv_type_pthread_spinlock_t=yes}
ac_cv_type_pthread_t=${ac_cv_type_pthread_t=yes}
ac_cv_type_ptrdiff_t=${ac_cv_type_ptrdiff_t=yes}
ac_cv_type_sa_family_t=${ac_cv_type_sa_family_t=no}
ac_cv_type_sig_atomic_t=${ac_cv_type_sig_atomic_t=yes}
ac_cv_type_sighandler_t=${ac_cv_type_sighandler_t=no}
ac_cv_type_siginfo_t=${ac_cv_type_siginfo_t=no}
ac_cv_type_sigset_t=${ac_cv_type_sigset_t=no}
ac_cv_type_size_t=${ac_cv_type_size_t=yes}
ac_cv_type_socklen_t=${ac_cv_type_socklen_t=yes}
ac_cv_type_struct_sched_param=${ac_cv_type_struct_sched_param=yes}
ac_cv_type_struct_sockaddr_storage=${ac_cv_type_struct_sockaddr_storage=yes}
ac_cv_type_uid_t=${ac_cv_type_uid_t=no}
ac_cv_type_unsigned_long_long_int=${ac_cv_type_unsigned_long_long_int=yes}
ac_cv_type_useconds_t=${ac_cv_type_useconds_t=yes}
ac_cv_type_volatile_sig_atomic_t=${ac_cv_type_volatile_sig_atomic_t=yes}
ac_cv_working_alloca_h=${ac_cv_working_alloca_h=no}
acl_cv_hardcode_direct=${acl_cv_hardcode_direct=no}
acl_cv_hardcode_libdir_flag_spec=${acl_cv_hardcode_libdir_flag_spec='-L$libdir'}
acl_cv_hardcode_libdir_separator=${acl_cv_hardcode_libdir_separator=}
acl_cv_hardcode_minus_L=${acl_cv_hardcode_minus_L=no}
acl_cv_libdirstems=${acl_cv_libdirstems=lib,lib,lib}
acl_cv_libext=${acl_cv_libext=a}
acl_cv_libname_spec=${acl_cv_libname_spec='lib$name'}
acl_cv_libpath=${acl_cv_libpath=PATH}
acl_cv_library_names_spec=${acl_cv_library_names_spec='$libname.dll.a $libname.lib'}
acl_cv_prog_gnu_ld=${acl_cv_prog_gnu_ld=yes}
acl_cv_rpath=${acl_cv_rpath=done}
acl_cv_shlibext=${acl_cv_shlibext=dll}
acl_cv_shlibpath_var=${acl_cv_shlibpath_var=PATH}
acl_cv_wl=${acl_cv_wl=-Wl,}
am_cv_CC_dependencies_compiler_type=${am_cv_CC_dependencies_compiler_type=none}
am_cv_CXX_dependencies_compiler_type=${am_cv_CXX_dependencies_compiler_type=none}
am_cv_func_iconv=${am_cv_func_iconv=yes}
am_cv_func_iconv_works=${am_cv_func_iconv_works=yes}
am_cv_func_working_getline=${am_cv_func_working_getline=no}
am_cv_langinfo_codeset=${am_cv_langinfo_codeset=no}
am_cv_lib_iconv=${am_cv_lib_iconv=yes}
am_cv_make_support_nested_variables=${am_cv_make_support_nested_variables=yes}
am_cv_prog_cc_c_o=${am_cv_prog_cc_c_o=yes}
am_cv_prog_tar_ustar=${am_cv_prog_tar_ustar=gnutar}
gl_cv___builtin_expect=${gl_cv___builtin_expect=yes}
gl_cv_c_amsterdam_compiler=${gl_cv_c_amsterdam_compiler=no}
gl_cv_c_cplusplus=${gl_cv_c_cplusplus=no}
gl_cv_c_multiarch=${gl_cv_c_multiarch=no}
gl_cv_cc_double_expbit0=${gl_cv_cc_double_expbit0='word 1 bit 20'}
gl_cv_cc_float_expbit0=${gl_cv_cc_float_expbit0='word 0 bit 23'}
gl_cv_cc_long_double_expbit0=${gl_cv_cc_long_double_expbit0='word 2 bit 0'}
gl_cv_cc_vis_werror=${gl_cv_cc_vis_werror=yes}
gl_cv_cc_visibility=${gl_cv_cc_visibility=yes}
gl_cv_cc_wallow=${gl_cv_cc_wallow=-Wno-error}
gl_cv_compiler_check_decl_option=${gl_cv_compiler_check_decl_option=none}
gl_cv_compiler_clang=${gl_cv_compiler_clang=no}
gl_cv_const_PTHREAD_CREATE_DETACHED=${gl_cv_const_PTHREAD_CREATE_DETACHED=yes}
gl_cv_const_PTHREAD_MUTEX_RECURSIVE=${gl_cv_const_PTHREAD_MUTEX_RECURSIVE=yes}
gl_cv_const_PTHREAD_MUTEX_ROBUST=${gl_cv_const_PTHREAD_MUTEX_ROBUST=no}
gl_cv_const_PTHREAD_PROCESS_SHARED=${gl_cv_const_PTHREAD_PROCESS_SHARED=yes}
gl_cv_cxx_wallow=${gl_cv_cxx_wallow=-Wno-error}
gl_cv_decl_HOST_NAME_MAX=${gl_cv_decl_HOST_NAME_MAX=256}
gl_cv_decl_null_works=${gl_cv_decl_null_works=yes}
gl_cv_double_slash_root=${gl_cv_double_slash_root=yes}
gl_cv_elf=${gl_cv_elf=no}
gl_cv_func_btowc_eof=${gl_cv_func_btowc_eof=yes}
gl_cv_func_btowc_nul=${gl_cv_func_btowc_nul=yes}
gl_cv_func_copy_file_range=${gl_cv_func_copy_file_range=no}
gl_cv_func_dirfd_macro=${gl_cv_func_dirfd_macro=no}
gl_cv_func_fabs_no_libm=${gl_cv_func_fabs_no_libm=yes}
gl_cv_func_fflush_stdin=${gl_cv_func_fflush_stdin=no}
gl_cv_func_fopen_mode_e=${gl_cv_func_fopen_mode_e=no}
gl_cv_func_fopen_mode_x=${gl_cv_func_fopen_mode_x=no}
gl_cv_func_fopen_slash=${gl_cv_func_fopen_slash='guessing no'}
gl_cv_func_free_preserves_errno=${gl_cv_func_free_preserves_errno=no}
gl_cv_func_frexp_no_libm=${gl_cv_func_frexp_no_libm=yes}
gl_cv_func_frexpl_no_libm=${gl_cv_func_frexpl_no_libm=yes}
gl_cv_func_fseeko=${gl_cv_func_fseeko=yes}
gl_cv_func_ftello=${gl_cv_func_ftello=yes}
gl_cv_func_ftello_works=${gl_cv_func_ftello_works=yes}
gl_cv_func_getcwd_path_max=${gl_cv_func_getcwd_path_max=yes}
gl_cv_func_getcwd_posix_signature=${gl_cv_func_getcwd_posix_signature=no}
gl_cv_func_getpagesize=${gl_cv_func_getpagesize=yes}
gl_cv_func_gettimeofday_posix_signature=${gl_cv_func_gettimeofday_posix_signature=yes}
gl_cv_func_isinfl_works=${gl_cv_func_isinfl_works=yes}
gl_cv_func_isnand_no_libm=${gl_cv_func_isnand_no_libm=yes}
gl_cv_func_isnanf_no_libm=${gl_cv_func_isnanf_no_libm=yes}
gl_cv_func_isnanf_works=${gl_cv_func_isnanf_works=yes}
gl_cv_func_isnanl_no_libm=${gl_cv_func_isnanl_no_libm=yes}
gl_cv_func_isnanl_works=${gl_cv_func_isnanl_works=yes}
gl_cv_func_iswcntrl_works=${gl_cv_func_iswcntrl_works=yes}
gl_cv_func_itold_works=${gl_cv_func_itold_works=yes}
gl_cv_func_ldexp_no_libm=${gl_cv_func_ldexp_no_libm=yes}
gl_cv_func_ldexpl_no_libm=${gl_cv_func_ldexpl_no_libm=yes}
gl_cv_func_ldexpl_works=${gl_cv_func_ldexpl_works=yes}
gl_cv_func_log10_works=${gl_cv_func_log10_works=yes}
gl_cv_func_lseek_pipe=${gl_cv_func_lseek_pipe=no}
gl_cv_func_lstat_dereferences_slashed_symlink=${gl_cv_func_lstat_dereferences_slashed_symlink=no}
gl_cv_func_malloc_0_nonnull=${gl_cv_func_malloc_0_nonnull=1}
gl_cv_func_malloc_posix=${gl_cv_func_malloc_posix=no}
gl_cv_func_mbrtowc_C_locale_sans_EILSEQ=${gl_cv_func_mbrtowc_C_locale_sans_EILSEQ=yes}
gl_cv_func_mbrtowc_empty_input=${gl_cv_func_mbrtowc_empty_input=yes}
gl_cv_func_mbrtowc_incomplete_state=${gl_cv_func_mbrtowc_incomplete_state='guessing yes'}
gl_cv_func_mbrtowc_nul_retval=${gl_cv_func_mbrtowc_nul_retval='guessing yes'}
gl_cv_func_mbrtowc_null_arg1=${gl_cv_func_mbrtowc_null_arg1='guessing yes'}
gl_cv_func_mbrtowc_null_arg2=${gl_cv_func_mbrtowc_null_arg2='guessing yes'}
gl_cv_func_mbrtowc_retval=${gl_cv_func_mbrtowc_retval=no}
gl_cv_func_mbrtowc_sanitycheck=${gl_cv_func_mbrtowc_sanitycheck='guessing yes'}
gl_cv_func_memchr_works=${gl_cv_func_memchr_works=yes}
gl_cv_func_mkdir_trailing_dot_works=${gl_cv_func_mkdir_trailing_dot_works=no}
gl_cv_func_open_directory_works=${gl_cv_func_open_directory_works=no}
gl_cv_func_perror_works=${gl_cv_func_perror_works=yes}
gl_cv_func_posix_spawn_file_actions_addclose_works=${gl_cv_func_posix_spawn_file_actions_addclose_works=no}
gl_cv_func_posix_spawn_file_actions_adddup2_works=${gl_cv_func_posix_spawn_file_actions_adddup2_works=no}
gl_cv_func_posix_spawn_file_actions_addopen_works=${gl_cv_func_posix_spawn_file_actions_addopen_works=no}
gl_cv_func_pow_no_libm=${gl_cv_func_pow_no_libm=yes}
gl_cv_func_printf_attribute_flavor=${gl_cv_func_printf_attribute_flavor=gnu}
gl_cv_func_printf_directive_n=${gl_cv_func_printf_directive_n=no}
gl_cv_func_printf_enomem=${gl_cv_func_printf_enomem='guessing no'}
gl_cv_func_printf_flag_leftadjust=${gl_cv_func_printf_flag_leftadjust=yes}
gl_cv_func_pthread_sigmask_macro=${gl_cv_func_pthread_sigmask_macro=yes}
gl_cv_func_re_compile_pattern_working=${gl_cv_func_re_compile_pattern_working=no}
gl_cv_func_realpath_works=${gl_cv_func_realpath_works=no}
gl_cv_func_rmdir_works=${gl_cv_func_rmdir_works=no}
gl_cv_func_setlocale_null_all_mtsafe=${gl_cv_func_setlocale_null_all_mtsafe=yes}
gl_cv_func_setlocale_null_one_mtsafe=${gl_cv_func_setlocale_null_one_mtsafe=yes}
gl_cv_func_signbit=${gl_cv_func_signbit=yes}
gl_cv_func_signbit_builtins=${gl_cv_func_signbit_builtins=yes}
gl_cv_func_sleep_works=${gl_cv_func_sleep_works=no}
gl_cv_func_snprintf_posix=${gl_cv_func_snprintf_posix=no}
gl_cv_func_snprintf_size1=${gl_cv_func_snprintf_size1=yes}
gl_cv_func_snprintf_usable=${gl_cv_func_snprintf_usable=no}
gl_cv_func_strerror_0_works=${gl_cv_func_strerror_0_works=yes}
gl_cv_func_strstr_linear=${gl_cv_func_strstr_linear=no}
gl_cv_func_strstr_works_always=${gl_cv_func_strstr_works_always=yes}
gl_cv_func_strtol_works=${gl_cv_func_strtol_works=no}
gl_cv_func_strtoul_works=${gl_cv_func_strtoul_works=no}
gl_cv_func_svid_putenv=${gl_cv_func_svid_putenv=no}
gl_cv_func_timespec_get=${gl_cv_func_timespec_get=no}
gl_cv_func_ungetc_works=${gl_cv_func_ungetc_works=yes}
gl_cv_func_unlink_honors_slashes=${gl_cv_func_unlink_honors_slashes=no}
gl_cv_func_unlink_parent_fails=${gl_cv_func_unlink_parent_fails='guessing yes'}
gl_cv_func_va_copy=${gl_cv_func_va_copy=yes}
gl_cv_func_vasprintf_posix=${gl_cv_func_vasprintf_posix=no}
gl_cv_func_vsnprintf_usable=${gl_cv_func_vsnprintf_usable=no}
gl_cv_func_vsnprintf_zerosize_c99=${gl_cv_func_vsnprintf_zerosize_c99=yes}
gl_cv_func_wcrtomb_retval=${gl_cv_func_wcrtomb_retval=yes}
gl_cv_func_wcrtomb_works=${gl_cv_func_wcrtomb_works=yes}
gl_cv_func_wctob_works=${gl_cv_func_wctob_works=no}
gl_cv_func_wcwidth_macro=${gl_cv_func_wcwidth_macro=no}
gl_cv_func_wmemchr=${gl_cv_func_wmemchr=yes}
gl_cv_func_working_utimes=${gl_cv_func_working_utimes=no}
gl_cv_func_wsastartup=${gl_cv_func_wsastartup=yes}
gl_cv_have_include_next=${gl_cv_have_include_next=yes}
gl_cv_have_unlimited_file_name_length=${gl_cv_have_unlimited_file_name_length=no}
gl_cv_header_errno_h_EMULTIHOP=${gl_cv_header_errno_h_EMULTIHOP=no}
gl_cv_header_errno_h_EOVERFLOW=${gl_cv_header_errno_h_EOVERFLOW=yes}
gl_cv_header_errno_h_complete=${gl_cv_header_errno_h_complete=no}
gl_cv_header_inttypes_h=${gl_cv_header_inttypes_h=yes}
gl_cv_header_limits_width=${gl_cv_header_limits_width=no}
gl_cv_header_locale_h_needs_xlocale_h=${gl_cv_header_locale_h_needs_xlocale_h=no}
gl_cv_header_locale_h_posix2001=${gl_cv_header_locale_h_posix2001=no}
gl_cv_header_locale_has_locale_t=${gl_cv_header_locale_has_locale_t=no}
gl_cv_header_math_huge_val_works=${gl_cv_header_math_huge_val_works=yes}
gl_cv_header_math_nan_works=${gl_cv_header_math_nan_works=yes}
gl_cv_header_netinet_in_h_selfcontained=${gl_cv_header_netinet_in_h_selfcontained=no}
gl_cv_header_signal_h_SIGPIPE=${gl_cv_header_signal_h_SIGPIPE=no}
gl_cv_header_stdint_h=${gl_cv_header_stdint_h=yes}
gl_cv_header_stdint_width=${gl_cv_header_stdint_width=no}
gl_cv_header_stdint_without_STDC_macros=${gl_cv_header_stdint_without_STDC_macros=yes}
gl_cv_header_sys_select_h_selfcontained=${gl_cv_header_sys_select_h_selfcontained=no}
gl_cv_header_sys_socket_h_selfcontained=${gl_cv_header_sys_socket_h_selfcontained=no}
gl_cv_header_working_fcntl_h=${gl_cv_header_working_fcntl_h=no}
gl_cv_header_working_stdalign_h=${gl_cv_header_working_stdalign_h=yes}
gl_cv_header_working_stdint_h=${gl_cv_header_working_stdint_h=yes}
gl_cv_iconv_nonconst=${gl_cv_iconv_nonconst=yes}
gl_cv_ld_autoimport=${gl_cv_ld_autoimport=no}
gl_cv_libcroco_force_included=${gl_cv_libcroco_force_included=yes}
gl_cv_libcroco_use_included=${gl_cv_libcroco_use_included=yes}
gl_cv_libglib_force_included=${gl_cv_libglib_force_included=yes}
gl_cv_libglib_use_included=${gl_cv_libglib_use_included=yes}
gl_cv_libxml_force_included=${gl_cv_libxml_force_included=yes}
gl_cv_libxml_use_included=${gl_cv_libxml_use_included=yes}
gl_cv_long_double_equals_double=${gl_cv_long_double_equals_double=no}
gl_cv_macro_O_CLOEXEC=${gl_cv_macro_O_CLOEXEC=no}
gl_cv_member_st_size_64=${gl_cv_member_st_size_64=no}
gl_cv_minmax_in_limits_h=${gl_cv_minmax_in_limits_h=no}
gl_cv_minmax_in_sys_param_h=${gl_cv_minmax_in_sys_param_h=no}
gl_cv_sys_struct_timeval=${gl_cv_sys_struct_timeval=yes}
gl_cv_sys_struct_timeval_tv_sec=${gl_cv_sys_struct_timeval_tv_sec=no}
gl_cv_termcap=${gl_cv_termcap='not found, consider installing GNU ncurses'}
gl_cv_terminfo=${gl_cv_terminfo='not found, consider installing GNU ncurses'}
gl_cv_terminfo_tparam=${gl_cv_terminfo_tparam=no}
gl_cv_terminfo_tparm=${gl_cv_terminfo_tparm=no}
gl_cv_test_INT32_MAX_LT_INTMAX_MAX=${gl_cv_test_INT32_MAX_LT_INTMAX_MAX=yes}
gl_cv_test_INT64_MAX_EQ_LONG_MAX=${gl_cv_test_INT64_MAX_EQ_LONG_MAX=no}
gl_cv_test_UINT32_MAX_LT_UINTMAX_MAX=${gl_cv_test_UINT32_MAX_LT_UINTMAX_MAX=yes}
gl_cv_test_UINT64_MAX_EQ_ULONG_MAX=${gl_cv_test_UINT64_MAX_EQ_ULONG_MAX=no}
gl_cv_time_h_has_TIME_UTC=${gl_cv_time_h_has_TIME_UTC=no}
gl_cv_type_max_align_t=${gl_cv_type_max_align_t=yes}
gl_cv_type_off_t_64=${gl_cv_type_off_t_64=yes}
gl_cv_type_sigset_t=${gl_cv_type_sigset_t=no}
gl_cv_type_time_t_y2038=${gl_cv_type_time_t_y2038=yes}
gl_cv_type_wctrans_t=${gl_cv_type_wctrans_t=yes}
gl_cv_type_wctype_t=${gl_cv_type_wctype_t=yes}
gl_cv_type_wint_t_large_enough=${gl_cv_type_wint_t_large_enough=no}
gl_cv_var_stdin_large_offset=${gl_cv_var_stdin_large_offset=yes}
gl_cv_w32_gethostname=${gl_cv_w32_gethostname=yes}
gt_cv_c_intmax_t=${gt_cv_c_intmax_t=yes}
gt_cv_c_wchar_t=${gt_cv_c_wchar_t=yes}
gt_cv_c_wint_t=${gt_cv_c_wint_t=yes}
gt_cv_func_CFLocaleCopyPreferredLanguages=${gt_cv_func_CFLocaleCopyPreferredLanguages=no}
gt_cv_func_CFPreferencesCopyAppValue=${gt_cv_func_CFPreferencesCopyAppValue=no}
gt_cv_func_gnugettext2_libc=${gt_cv_func_gnugettext2_libc=no}
gt_cv_func_gnugettext2_libintl=${gt_cv_func_gnugettext2_libintl=yes}
gt_cv_func_printf_posix=${gt_cv_func_printf_posix=no}
gt_cv_func_uselocale_works=${gt_cv_func_uselocale_works=no}
gt_cv_int_divbyzero_sigfpe=${gt_cv_int_divbyzero_sigfpe=yes}
gt_cv_siginfo_t=${gt_cv_siginfo_t=no}
gt_cv_socket_ipv6=${gt_cv_socket_ipv6=no}
gt_cv_ssize_t=${gt_cv_ssize_t=yes}
gt_cv_val_LC_MESSAGES=${gt_cv_val_LC_MESSAGES=no}
gt_cv_var_environ_declaration=${gt_cv_var_environ_declaration=yes}
nls_cv_force_use_gnu_gettext=${nls_cv_force_use_gnu_gettext=no}
nls_cv_use_gnu_gettext=${nls_cv_use_gnu_gettext=no}
