ac_cv_c_bigendian=${ac_cv_c_bigendian=no}
ac_cv_c_compiler_gnu=${ac_cv_c_compiler_gnu=no}
ac_cv_c_flexmember=${ac_cv_c_flexmember=yes}
ac_cv_c_restrict=${ac_cv_c_restrict=no}
ac_cv_c_undeclared_builtin_options=${ac_cv_c_undeclared_builtin_options='none needed'}
ac_cv_c_vararrays=${ac_cv_c_vararrays=no}
ac_cv_cxx_compiler_gnu=${ac_cv_cxx_compiler_gnu=no}
ac_cv_exeext=${ac_cv_exeext=.exe}
ac_cv_func__NSGetExecutablePath=${ac_cv_func__NSGetExecutablePath=no}
ac_cv_func___fpurge=${ac_cv_func___fpurge=no}
ac_cv_func___freading=${ac_cv_func___freading=no}
ac_cv_func___fsetlocking=${ac_cv_func___fsetlocking=no}
ac_cv_func___secure_getenv=${ac_cv_func___secure_getenv=no}
ac_cv_func___xpg_strerror_r=${ac_cv_func___xpg_strerror_r=no}
ac_cv_func__chsize=${ac_cv_func__chsize=yes}
ac_cv_func__fseeki64=${ac_cv_func__fseeki64=yes}
ac_cv_func__ftelli64=${ac_cv_func__ftelli64=yes}
ac_cv_func__set_invalid_parameter_handler=${ac_cv_func__set_invalid_parameter_handler=yes}
ac_cv_func_alloca_works=${ac_cv_func_alloca_works=yes}
ac_cv_func_asprintf=${ac_cv_func_asprintf=no}
ac_cv_func_atexit=${ac_cv_func_atexit=yes}
ac_cv_func_btowc=${ac_cv_func_btowc=yes}
ac_cv_func_canonicalize_file_name=${ac_cv_func_canonicalize_file_name=no}
ac_cv_func_catgets=${ac_cv_func_catgets=no}
ac_cv_func_chown=${ac_cv_func_chown=no}
ac_cv_func_clock_getres=${ac_cv_func_clock_getres=no}
ac_cv_func_clock_gettime=${ac_cv_func_clock_gettime=no}
ac_cv_func_clock_settime=${ac_cv_func_clock_settime=no}
ac_cv_func_close_range=${ac_cv_func_close_range=no}
ac_cv_func_closedir=${ac_cv_func_closedir=no}
ac_cv_func_confstr=${ac_cv_func_confstr=no}
ac_cv_func_dirfd=${ac_cv_func_dirfd=no}
ac_cv_func_duplocale=${ac_cv_func_duplocale=no}
ac_cv_func_eaccess=${ac_cv_func_eaccess=no}
ac_cv_func_explicit_bzero=${ac_cv_func_explicit_bzero=no}
ac_cv_func_explicit_memset=${ac_cv_func_explicit_memset=no}
ac_cv_func_faccessat=${ac_cv_func_faccessat=no}
ac_cv_func_fchdir=${ac_cv_func_fchdir=no}
ac_cv_func_fchmod=${ac_cv_func_fchmod=no}
ac_cv_func_fcntl=${ac_cv_func_fcntl=no}
ac_cv_func_fdopendir=${ac_cv_func_fdopendir=no}
ac_cv_func_flockfile=${ac_cv_func_flockfile=no}
ac_cv_func_fnmatch=${ac_cv_func_fnmatch=no}
ac_cv_func_fpurge=${ac_cv_func_fpurge=no}
ac_cv_func_freelocale=${ac_cv_func_freelocale=no}
ac_cv_func_fstatat=${ac_cv_func_fstatat=no}
ac_cv_func_fsync=${ac_cv_func_fsync=no}
ac_cv_func_ftruncate=${ac_cv_func_ftruncate=no}
ac_cv_func_funlockfile=${ac_cv_func_funlockfile=no}
ac_cv_func_futimens=${ac_cv_func_futimens=no}
ac_cv_func_futimes=${ac_cv_func_futimes=no}
ac_cv_func_futimesat=${ac_cv_func_futimesat=no}
ac_cv_func_getaddrinfo=${ac_cv_func_getaddrinfo=no}
ac_cv_func_getcwd=${ac_cv_func_getcwd=yes}
ac_cv_func_getdelim=${ac_cv_func_getdelim=no}
ac_cv_func_getdtablesize=${ac_cv_func_getdtablesize=no}
ac_cv_func_getegid=${ac_cv_func_getegid=no}
ac_cv_func_geteuid=${ac_cv_func_geteuid=no}
ac_cv_func_getexecname=${ac_cv_func_getexecname=no}
ac_cv_func_getgid=${ac_cv_func_getgid=no}
ac_cv_func_gethostbyname=${ac_cv_func_gethostbyname=no}
ac_cv_func_gethostname=${ac_cv_func_gethostname=no}
ac_cv_func_getline=${ac_cv_func_getline=no}
ac_cv_func_getpagesize=${ac_cv_func_getpagesize=no}
ac_cv_func_getppriv=${ac_cv_func_getppriv=no}
ac_cv_func_getprogname=${ac_cv_func_getprogname=no}
ac_cv_func_getrandom=${ac_cv_func_getrandom=no}
ac_cv_func_getrlimit=${ac_cv_func_getrlimit=no}
ac_cv_func_getsid=${ac_cv_func_getsid=no}
ac_cv_func_gettimeofday=${ac_cv_func_gettimeofday=no}
ac_cv_func_getuid=${ac_cv_func_getuid=no}
ac_cv_func_inet_ntop=${ac_cv_func_inet_ntop=no}
ac_cv_func_isascii=${ac_cv_func_isascii=no}
ac_cv_func_isblank=${ac_cv_func_isblank=yes}
ac_cv_func_issetugid=${ac_cv_func_issetugid=no}
ac_cv_func_iswblank=${ac_cv_func_iswblank=yes}
ac_cv_func_iswcntrl=${ac_cv_func_iswcntrl=yes}
ac_cv_func_iswctype=${ac_cv_func_iswctype=yes}
ac_cv_func_localtime=${ac_cv_func_localtime=yes}
ac_cv_func_lstat=${ac_cv_func_lstat=no}
ac_cv_func_lutimes=${ac_cv_func_lutimes=no}
ac_cv_func_malloc_0_nonnull=${ac_cv_func_malloc_0_nonnull=yes}
ac_cv_func_mbrlen=${ac_cv_func_mbrlen=yes}
ac_cv_func_mbrtowc=${ac_cv_func_mbrtowc=yes}
ac_cv_func_mbsinit=${ac_cv_func_mbsinit=no}
ac_cv_func_mbslen=${ac_cv_func_mbslen=no}
ac_cv_func_mbsrtowcs=${ac_cv_func_mbsrtowcs=yes}
ac_cv_func_mbtowc=${ac_cv_func_mbtowc=yes}
ac_cv_func_memmove=${ac_cv_func_memmove=yes}
ac_cv_func_mempcpy=${ac_cv_func_mempcpy=no}
ac_cv_func_memrchr=${ac_cv_func_memrchr=no}
ac_cv_func_memset=${ac_cv_func_memset=yes}
ac_cv_func_memset_s=${ac_cv_func_memset_s=no}
ac_cv_func_mkdtemp=${ac_cv_func_mkdtemp=no}
ac_cv_func_mmap=${ac_cv_func_mmap=no}
ac_cv_func_mmap_fixed_mapped=${ac_cv_func_mmap_fixed_mapped=no}
ac_cv_func_mprotect=${ac_cv_func_mprotect=no}
ac_cv_func_mquery=${ac_cv_func_mquery=no}
ac_cv_func_munmap=${ac_cv_func_munmap=no}
ac_cv_func_newlocale=${ac_cv_func_newlocale=no}
ac_cv_func_nl_langinfo=${ac_cv_func_nl_langinfo=no}
ac_cv_func_obstack=${ac_cv_func_obstack=no}
ac_cv_func_openat=${ac_cv_func_openat=no}
ac_cv_func_opendir=${ac_cv_func_opendir=no}
ac_cv_func_pathconf=${ac_cv_func_pathconf=no}
ac_cv_func_pipe2=${ac_cv_func_pipe2=no}
ac_cv_func_pipe=${ac_cv_func_pipe=no}
ac_cv_func_posix_spawn=${ac_cv_func_posix_spawn=no}
ac_cv_func_posix_spawn_file_actions_addchdir=${ac_cv_func_posix_spawn_file_actions_addchdir=no}
ac_cv_func_posix_spawn_file_actions_addchdir_np=${ac_cv_func_posix_spawn_file_actions_addchdir_np=no}
ac_cv_func_pstat_getprocvm=${ac_cv_func_pstat_getprocvm=no}
ac_cv_func_pthread_sigmask=${ac_cv_func_pthread_sigmask=no}
ac_cv_func_putenv=${ac_cv_func_putenv=yes}
ac_cv_func_raise=${ac_cv_func_raise=yes}
ac_cv_func_rawmemchr=${ac_cv_func_rawmemchr=no}
ac_cv_func_readdir=${ac_cv_func_readdir=no}
ac_cv_func_readlink=${ac_cv_func_readlink=no}
ac_cv_func_readlinkat=${ac_cv_func_readlinkat=no}
ac_cv_func_realloc_0_nonnull=${ac_cv_func_realloc_0_nonnull=yes}
ac_cv_func_reallocarray=${ac_cv_func_reallocarray=no}
ac_cv_func_realpath=${ac_cv_func_realpath=no}
ac_cv_func_rewinddir=${ac_cv_func_rewinddir=no}
ac_cv_func_sched_setparam=${ac_cv_func_sched_setparam=no}
ac_cv_func_sched_setscheduler=${ac_cv_func_sched_setscheduler=no}
ac_cv_func_secure_getenv=${ac_cv_func_secure_getenv=no}
ac_cv_func_select=${ac_cv_func_select=no}
ac_cv_func_setdtablesize=${ac_cv_func_setdtablesize=no}
ac_cv_func_setegid=${ac_cv_func_setegid=no}
ac_cv_func_setenv=${ac_cv_func_setenv=no}
ac_cv_func_seteuid=${ac_cv_func_seteuid=no}
ac_cv_func_setlocale=${ac_cv_func_setlocale=yes}
ac_cv_func_setrlimit=${ac_cv_func_setrlimit=no}
ac_cv_func_shutdown=${ac_cv_func_shutdown=no}
ac_cv_func_sigaction=${ac_cv_func_sigaction=no}
ac_cv_func_sigaltstack=${ac_cv_func_sigaltstack=no}
ac_cv_func_siginterrupt=${ac_cv_func_siginterrupt=no}
ac_cv_func_sleep=${ac_cv_func_sleep=no}
ac_cv_func_snprintf=${ac_cv_func_snprintf=no}
ac_cv_func_stat=${ac_cv_func_stat=yes}
ac_cv_func_stpcpy=${ac_cv_func_stpcpy=no}
ac_cv_func_stpncpy=${ac_cv_func_stpncpy=no}
ac_cv_func_strcasecmp=${ac_cv_func_strcasecmp=no}
ac_cv_func_strchrnul=${ac_cv_func_strchrnul=no}
ac_cv_func_strcspn=${ac_cv_func_strcspn=yes}
ac_cv_func_strerror_r=${ac_cv_func_strerror_r=no}
ac_cv_func_strerror_r_char_p=${ac_cv_func_strerror_r_char_p=no}
ac_cv_func_strftime=${ac_cv_func_strftime=yes}
ac_cv_func_strnlen=${ac_cv_func_strnlen=yes}
ac_cv_func_strnlen_working=${ac_cv_func_strnlen_working=yes}
ac_cv_func_strpbrk=${ac_cv_func_strpbrk=yes}
ac_cv_func_strtol=${ac_cv_func_strtol=yes}
ac_cv_func_strtoul=${ac_cv_func_strtoul=yes}
ac_cv_func_symlink=${ac_cv_func_symlink=no}
ac_cv_func_tcdrain=${ac_cv_func_tcdrain=no}
ac_cv_func_tcgetattr=${ac_cv_func_tcgetattr=no}
ac_cv_func_tsearch=${ac_cv_func_tsearch=no}
ac_cv_func_unsetenv=${ac_cv_func_unsetenv=no}
ac_cv_func_uselocale=${ac_cv_func_uselocale=no}
ac_cv_func_usleep=${ac_cv_func_usleep=no}
ac_cv_func_utimensat=${ac_cv_func_utimensat=no}
ac_cv_func_vasnprintf=${ac_cv_func_vasnprintf=no}
ac_cv_func_vasprintf=${ac_cv_func_vasprintf=no}
ac_cv_func_vfork=${ac_cv_func_vfork=no}
ac_cv_func_vsnprintf=${ac_cv_func_vsnprintf=no}
ac_cv_func_waitid=${ac_cv_func_waitid=no}
ac_cv_func_wcrtomb=${ac_cv_func_wcrtomb=yes}
ac_cv_func_wcslen=${ac_cv_func_wcslen=yes}
ac_cv_func_wcsnlen=${ac_cv_func_wcsnlen=yes}
ac_cv_func_wctob=${ac_cv_func_wctob=yes}
ac_cv_func_wcwidth=${ac_cv_func_wcwidth=no}
ac_cv_func_wmempcpy=${ac_cv_func_wmempcpy=no}
ac_cv_func_wprintf=${ac_cv_func_wprintf=no}
ac_cv_have_decl___argv=${ac_cv_have_decl___argv=yes}
ac_cv_have_decl__fseeki64=${ac_cv_have_decl__fseeki64=yes}
ac_cv_have_decl__putenv=${ac_cv_have_decl__putenv=yes}
ac_cv_have_decl__snprintf=${ac_cv_have_decl__snprintf=yes}
ac_cv_have_decl__snwprintf=${ac_cv_have_decl__snwprintf=yes}
ac_cv_have_decl_alarm=${ac_cv_have_decl_alarm=no}
ac_cv_have_decl_clearerr_unlocked=${ac_cv_have_decl_clearerr_unlocked=no}
ac_cv_have_decl_dirfd=${ac_cv_have_decl_dirfd=no}
ac_cv_have_decl_ecvt=${ac_cv_have_decl_ecvt=yes}
ac_cv_have_decl_execvpe=${ac_cv_have_decl_execvpe=no}
ac_cv_have_decl_fchdir=${ac_cv_have_decl_fchdir=no}
ac_cv_have_decl_fcloseall=${ac_cv_have_decl_fcloseall=yes}
ac_cv_have_decl_fcvt=${ac_cv_have_decl_fcvt=yes}
ac_cv_have_decl_fdopendir=${ac_cv_have_decl_fdopendir=no}
ac_cv_have_decl_feof_unlocked=${ac_cv_have_decl_feof_unlocked=no}
ac_cv_have_decl_ferror_unlocked=${ac_cv_have_decl_ferror_unlocked=no}
ac_cv_have_decl_fflush_unlocked=${ac_cv_have_decl_fflush_unlocked=no}
ac_cv_have_decl_fgets_unlocked=${ac_cv_have_decl_fgets_unlocked=no}
ac_cv_have_decl_fpurge=${ac_cv_have_decl_fpurge=no}
ac_cv_have_decl_fputc_unlocked=${ac_cv_have_decl_fputc_unlocked=no}
ac_cv_have_decl_fputs_unlocked=${ac_cv_have_decl_fputs_unlocked=no}
ac_cv_have_decl_fread_unlocked=${ac_cv_have_decl_fread_unlocked=no}
ac_cv_have_decl_frexpl=${ac_cv_have_decl_frexpl=yes}
ac_cv_have_decl_fseeko=${ac_cv_have_decl_fseeko=no}
ac_cv_have_decl_ftello=${ac_cv_have_decl_ftello=no}
ac_cv_have_decl_fwrite_unlocked=${ac_cv_have_decl_fwrite_unlocked=no}
ac_cv_have_decl_gcvt=${ac_cv_have_decl_gcvt=yes}
ac_cv_have_decl_getc_unlocked=${ac_cv_have_decl_getc_unlocked=no}
ac_cv_have_decl_getchar_unlocked=${ac_cv_have_decl_getchar_unlocked=no}
ac_cv_have_decl_getcwd=${ac_cv_have_decl_getcwd=no}
ac_cv_have_decl_getdelim=${ac_cv_have_decl_getdelim=no}
ac_cv_have_decl_getdtablesize=${ac_cv_have_decl_getdtablesize=no}
ac_cv_have_decl_getline=${ac_cv_have_decl_getline=no}
ac_cv_have_decl_getpagesize=${ac_cv_have_decl_getpagesize=no}
ac_cv_have_decl_inet_pton=${ac_cv_have_decl_inet_pton=yes}
ac_cv_have_decl_isblank=${ac_cv_have_decl_isblank=yes}
ac_cv_have_decl_isinf=${ac_cv_have_decl_isinf=yes}
ac_cv_have_decl_iswblank=${ac_cv_have_decl_iswblank=yes}
ac_cv_have_decl_ldexpl=${ac_cv_have_decl_ldexpl=yes}
ac_cv_have_decl_mbsinit=${ac_cv_have_decl_mbsinit=yes}
ac_cv_have_decl_mbswidth=${ac_cv_have_decl_mbswidth=no}
ac_cv_have_decl_memrchr=${ac_cv_have_decl_memrchr=no}
ac_cv_have_decl_posix_spawn=${ac_cv_have_decl_posix_spawn=no}
ac_cv_have_decl_program_invocation_name=${ac_cv_have_decl_program_invocation_name=no}
ac_cv_have_decl_program_invocation_short_name=${ac_cv_have_decl_program_invocation_short_name=no}
ac_cv_have_decl_putc_unlocked=${ac_cv_have_decl_putc_unlocked=no}
ac_cv_have_decl_putchar_unlocked=${ac_cv_have_decl_putchar_unlocked=no}
ac_cv_have_decl_setenv=${ac_cv_have_decl_setenv=no}
ac_cv_have_decl_sleep=${ac_cv_have_decl_sleep=no}
ac_cv_have_decl_snprintf=${ac_cv_have_decl_snprintf=yes}
ac_cv_have_decl_stpncpy=${ac_cv_have_decl_stpncpy=no}
ac_cv_have_decl_strdup=${ac_cv_have_decl_strdup=yes}
ac_cv_have_decl_strerror_r=${ac_cv_have_decl_strerror_r=no}
ac_cv_have_decl_strnlen=${ac_cv_have_decl_strnlen=yes}
ac_cv_have_decl_unsetenv=${ac_cv_have_decl_unsetenv=no}
ac_cv_have_decl_vsnprintf=${ac_cv_have_decl_vsnprintf=yes}
ac_cv_have_decl_wcsdup=${ac_cv_have_decl_wcsdup=yes}
ac_cv_have_decl_wcwidth=${ac_cv_have_decl_wcwidth=no}
ac_cv_header_OS_h=${ac_cv_header_OS_h=no}
ac_cv_header_arpa_inet_h=${ac_cv_header_arpa_inet_h=no}
ac_cv_header_arpa_nameser_h=${ac_cv_header_arpa_nameser_h=no}
ac_cv_header_bcrypt_h=${ac_cv_header_bcrypt_h=yes}
ac_cv_header_byteswap_h=${ac_cv_header_byteswap_h=no}
ac_cv_header_crtdefs_h=${ac_cv_header_crtdefs_h=yes}
ac_cv_header_ctype_h=${ac_cv_header_ctype_h=yes}
ac_cv_header_dirent_h=${ac_cv_header_dirent_h=no}
ac_cv_header_dl_h=${ac_cv_header_dl_h=no}
ac_cv_header_dlfcn_h=${ac_cv_header_dlfcn_h=no}
ac_cv_header_errno_h=${ac_cv_header_errno_h=yes}
ac_cv_header_fcntl_h=${ac_cv_header_fcntl_h=yes}
ac_cv_header_features_h=${ac_cv_header_features_h=no}
ac_cv_header_float_h=${ac_cv_header_float_h=yes}
ac_cv_header_fnmatch_h=${ac_cv_header_fnmatch_h=no}
ac_cv_header_getopt_h=${ac_cv_header_getopt_h=no}
ac_cv_header_iconv_h=${ac_cv_header_iconv_h=yes}
ac_cv_header_inttypes_h=${ac_cv_header_inttypes_h=yes}
ac_cv_header_langinfo_h=${ac_cv_header_langinfo_h=no}
ac_cv_header_libintl_h=${ac_cv_header_libintl_h=no}
ac_cv_header_libxml2_libxml_xmlexports_h=${ac_cv_header_libxml2_libxml_xmlexports_h=no}
ac_cv_header_libxml2_libxml_xmlversion_h=${ac_cv_header_libxml2_libxml_xmlversion_h=no}
ac_cv_header_limits_h=${ac_cv_header_limits_h=yes}
ac_cv_header_mach_o_dyld_h=${ac_cv_header_mach_o_dyld_h=no}
ac_cv_header_malloc_h=${ac_cv_header_malloc_h=yes}
ac_cv_header_math_h=${ac_cv_header_math_h=yes}
ac_cv_header_minix_config_h=${ac_cv_header_minix_config_h=no}
ac_cv_header_netdb_h=${ac_cv_header_netdb_h=no}
ac_cv_header_netinet_in_h=${ac_cv_header_netinet_in_h=no}
ac_cv_header_paths_h=${ac_cv_header_paths_h=no}
ac_cv_header_priv_h=${ac_cv_header_priv_h=no}
ac_cv_header_pthread_h=${ac_cv_header_pthread_h=no}
ac_cv_header_pwd_h=${ac_cv_header_pwd_h=no}
ac_cv_header_resolv_h=${ac_cv_header_resolv_h=no}
ac_cv_header_sched_h=${ac_cv_header_sched_h=no}
ac_cv_header_sdkddkver_h=${ac_cv_header_sdkddkver_h=yes}
ac_cv_header_search_h=${ac_cv_header_search_h=yes}
ac_cv_header_semaphore_h=${ac_cv_header_semaphore_h=no}
ac_cv_header_signal_h=${ac_cv_header_signal_h=yes}
ac_cv_header_spawn_h=${ac_cv_header_spawn_h=no}
ac_cv_header_stat_broken=${ac_cv_header_stat_broken=no}
ac_cv_header_stdbool_h=${ac_cv_header_stdbool_h=no}
ac_cv_header_stddef_h=${ac_cv_header_stddef_h=yes}
ac_cv_header_stdint_h=${ac_cv_header_stdint_h=yes}
ac_cv_header_stdio_ext_h=${ac_cv_header_stdio_ext_h=no}
ac_cv_header_stdio_h=${ac_cv_header_stdio_h=yes}
ac_cv_header_stdlib_h=${ac_cv_header_stdlib_h=yes}
ac_cv_header_string_h=${ac_cv_header_string_h=yes}
ac_cv_header_strings_h=${ac_cv_header_strings_h=no}
ac_cv_header_sys_cdefs_h=${ac_cv_header_sys_cdefs_h=no}
ac_cv_header_sys_ioctl_h=${ac_cv_header_sys_ioctl_h=no}
ac_cv_header_sys_mman_h=${ac_cv_header_sys_mman_h=no}
ac_cv_header_sys_param_h=${ac_cv_header_sys_param_h=no}
ac_cv_header_sys_random_h=${ac_cv_header_sys_random_h=no}
ac_cv_header_sys_select_h=${ac_cv_header_sys_select_h=no}
ac_cv_header_sys_single_threaded_h=${ac_cv_header_sys_single_threaded_h=no}
ac_cv_header_sys_socket_h=${ac_cv_header_sys_socket_h=no}
ac_cv_header_sys_stat_h=${ac_cv_header_sys_stat_h=yes}
ac_cv_header_sys_time_h=${ac_cv_header_sys_time_h=no}
ac_cv_header_sys_types_h=${ac_cv_header_sys_types_h=yes}
ac_cv_header_sys_uio_h=${ac_cv_header_sys_uio_h=no}
ac_cv_header_sys_wait_h=${ac_cv_header_sys_wait_h=no}
ac_cv_header_threads_h=${ac_cv_header_threads_h=no}
ac_cv_header_time_h=${ac_cv_header_time_h=yes}
ac_cv_header_unistd_h=${ac_cv_header_unistd_h=no}
ac_cv_header_utime_h=${ac_cv_header_utime_h=no}
ac_cv_header_wchar_h=${ac_cv_header_wchar_h=yes}
ac_cv_header_wctype_h=${ac_cv_header_wctype_h=yes}
ac_cv_header_winsock2_h=${ac_cv_header_winsock2_h=yes}
ac_cv_header_ws2tcpip_h=${ac_cv_header_ws2tcpip_h=yes}
ac_cv_header_xlocale_h=${ac_cv_header_xlocale_h=no}
ac_cv_member_struct_sockaddr_storage_ss_family=${ac_cv_member_struct_sockaddr_storage_ss_family=yes}
ac_cv_member_struct_stat_st_atim_st__tim_tv_nsec=${ac_cv_member_struct_stat_st_atim_st__tim_tv_nsec=no}
ac_cv_member_struct_stat_st_atim_tv_nsec=${ac_cv_member_struct_stat_st_atim_tv_nsec=no}
ac_cv_member_struct_stat_st_atimensec=${ac_cv_member_struct_stat_st_atimensec=no}
ac_cv_member_struct_stat_st_atimespec_tv_nsec=${ac_cv_member_struct_stat_st_atimespec_tv_nsec=no}
ac_cv_member_struct_stat_st_birthtim_tv_nsec=${ac_cv_member_struct_stat_st_birthtim_tv_nsec=no}
ac_cv_member_struct_stat_st_birthtimensec=${ac_cv_member_struct_stat_st_birthtimensec=no}
ac_cv_member_struct_stat_st_birthtimespec_tv_nsec=${ac_cv_member_struct_stat_st_birthtimespec_tv_nsec=no}
ac_cv_search_clock_gettime=${ac_cv_search_clock_gettime=no}
ac_cv_search_nanosleep=${ac_cv_search_nanosleep=no}
ac_cv_search_posix_spawn=${ac_cv_search_posix_spawn=no}
ac_cv_type__Bool=${ac_cv_type__Bool=yes}
ac_cv_type_long_long_int=${ac_cv_type_long_long_int=yes}
ac_cv_type_mbstate_t=${ac_cv_type_mbstate_t=yes}
ac_cv_type_mode_t=${ac_cv_type_mode_t=no}
ac_cv_type_nlink_t=${ac_cv_type_nlink_t=no}
ac_cv_type_off_t=${ac_cv_type_off_t=yes}
ac_cv_type_pid_t=${ac_cv_type_pid_t=no}
ac_cv_type_pthread_spinlock_t=${ac_cv_type_pthread_spinlock_t=no}
ac_cv_type_pthread_t=${ac_cv_type_pthread_t=no}
ac_cv_type_ptrdiff_t=${ac_cv_type_ptrdiff_t=yes}
ac_cv_type_sa_family_t=${ac_cv_type_sa_family_t=no}
ac_cv_type_sig_atomic_t=${ac_cv_type_sig_atomic_t=yes}
ac_cv_type_sighandler_t=${ac_cv_type_sighandler_t=no}
ac_cv_type_siginfo_t=${ac_cv_type_siginfo_t=no}
ac_cv_type_sigset_t=${ac_cv_type_sigset_t=no}
ac_cv_type_size_t=${ac_cv_type_size_t=yes}
ac_cv_type_socklen_t=${ac_cv_type_socklen_t=yes}
ac_cv_type_struct_sockaddr_storage=${ac_cv_type_struct_sockaddr_storage=yes}
ac_cv_type_uid_t=${ac_cv_type_uid_t=no}
ac_cv_type_unsigned_long_long_int=${ac_cv_type_unsigned_long_long_int=yes}
ac_cv_type_useconds_t=${ac_cv_type_useconds_t=no}
ac_cv_type_volatile_sig_atomic_t=${ac_cv_type_volatile_sig_atomic_t=yes}
