# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mqtt5
    REF boost-${VERSION}
    SHA512 46840ed68ab66529c2131cdc834134210e56d4e1e6c5cc73d00daf5c2c80755c9557519bc2497b77326ca105cd746acc43400497c6f7802c2ba366108c226b31
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
