# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mqtt5
    REF boost-${VERSION}
    SHA512 a4de7ba76eaa134b476a79dbfc7e0316ae9f03ed1fa70595739531376e3f4c979777f6b333cdcefb9e17bb35c8ad35be36a839be6c0ada494b63d82bd9c94c30
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
