# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/utility
    REF boost-${VERSION}
    SHA512 887f5c18b939308facf307792a240e470c2224b16741f0b13df052f2760ad4692acb5992608168dd86d7542f219d4627c6fef8b28fe2da442b4bb2c17971f84d
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
