diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0200a56df..c6accfa14 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -360,17 +360,48 @@ option(WITH_COPYSIGN_UNDEF "On Windows, in Python.h #defines copysign to be _cop
 ############################################################
 # Flat hierarchy if self-contained and on Windows
 option(WITH_SELFCONTAINED "Make the install directory self-contained" OFF)
+
+if(DEFINED LIB_PREFIX_RELATIVE)
+  set(DEF_LIB_PREFIX ${LIB_PREFIX_RELATIVE})
+else()
+  if(WITH_SELFCONTAINED OR (WIN32 AND NOT CYGWIN))
+    set(DEF_LIB_PREFIX casadi)
+  else()
+    set(DEF_LIB_PREFIX lib)
+  endif()
+endif()
+if(DEFINED BIN_PREFIX_RELATIVE)
+  set(DEF_BIN_PREFIX ${BIN_PREFIX_RELATIVE})
+else()
+  if(WITH_SELFCONTAINED OR (WIN32 AND NOT CYGWIN))
+    set(DEF_BIN_PREFIX casadi)
+  else()
+    set(DEF_BIN_PREFIX bin)
+  endif()
+endif()
+if(DEFINED INCLUDE_PREFIX_RELATIVE)
+  set(DEF_INCLUDE_PREFIX ${INCLUDE_PREFIX_RELATIVE})
+else()
+  if(WITH_SELFCONTAINED OR (WIN32 AND NOT CYGWIN))
+    set(DEF_INCLUDE_PREFIX casadi/include)
+  else()
+    set(DEF_INCLUDE_PREFIX include)
+  endif()
+endif()
+if(DEFINED CMAKE_PREFIX_RELATIVE)
+  set(DEF_CMAKE_PREFIX ${CMAKE_PREFIX_RELATIVE})
+else()
+  if(WITH_SELFCONTAINED OR (WIN32 AND NOT CYGWIN))
+    set(DEF_CMAKE_PREFIX casadi/cmake)
+  else()
+    set(DEF_CMAKE_PREFIX lib/cmake/casadi)
+  endif()
+endif()
+
 if(WITH_SELFCONTAINED OR (WIN32 AND NOT CYGWIN))
-  set(DEF_LIB_PREFIX casadi)
-  set(DEF_BIN_PREFIX casadi)
-  set(DEF_CMAKE_PREFIX casadi/cmake)
   set(DEF_PYTHON_PREFIX) # Note: Files installed in a casadi subdirectory
   set(DEF_MATLAB_PREFIX casadi)
-  set(DEF_INCLUDE_PREFIX casadi/include)
 else()
-  set(DEF_LIB_PREFIX lib)
-  set(DEF_BIN_PREFIX bin)
-  set(DEF_CMAKE_PREFIX lib/cmake/casadi)
   set(DEF_PYTHON_PREFIX python)
   if (WITH_PYTHON)
     set(PYTHON_VERSION_REQ "")
@@ -383,7 +414,6 @@ else()
     set(DEF_PYTHON_PREFIX ${PYTHON_SITE_PACKAGES})
   endif()
   set(DEF_MATLAB_PREFIX matlab)
-  set(DEF_INCLUDE_PREFIX include)
 endif()
 
 # Installation directories are cache entries that can be modified
