diff --git a/Makefile.am b/Makefile.am
index 79a3527..619a253 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -1,7 +1,7 @@
 lib_LTLIBRARIES = libcsv.la
      libcsv_la_SOURCES = libcsv.c
      libcsv_la_LDFLAGS = -version-info 3:3:0
-     libcsv_la_CFLAGS = -Wall -Wextra 
+     libcsv_la_CFLAGS = -Wall 
 libcsv_includedir = $(includedir)
 nobase_libcsv_include_HEADERS = csv.h
 dist_man_MANS = csv.3
