# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/random
    REF boost-${VERSION}
    SHA512 7e1cd0b8d2ffe682f71f6fe3558f935382dfbce24990cc99368524539ec23305ba4714b74ebb06659b8980925c2c97a51e2d7da23ea6a0a5fc18fdb1236ac5c5
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
