_find_package(libxml2 CONFIG REQUIRED)

get_target_property(LIBXML_INCLUDE_DIR LibXml2::LibXml2 INTERFACE_INCLUDE_DIRECTORIES)
set(LIBXML_INCLUDE_DIRS ${LIBXML_INCLUDE_DIR})
set(LIBXML_LIBRARY LibXml2::LibXml2)
set(LIBXML_LIBRARIES ${LIBXML_LIBRARY})