_find_package(libxml2 CONFIG REQUIRED)

set(LibXml2_FOUND 1)
set(LIBXML2_INCLUDE_DIR ${LIBXML_INCLUDE_DIRS})
set(LIBXML2_INCLUDE_DIRS ${LIBXML2_INCLUDE_DIR})
set(LIBXML2_LIBRARIES LibXml2::LibXml2)
get_target_property(LIBXML2_DEFINITIONS LibXml2::LibXml2 INTERFACE_COMPILE_DEFINITIONS)