# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/hana
    REF boost-${VERSION}
    SHA512 92367ba0587cc854516cc3f19ad994638bb88c52de875aa0cb5acb4f7bb69ab67a6b6a898dcae29b89d70ffd12ef91bdf0f84104314ac93cd1f67eb86df6ed4d
    HEAD_REF master
)

if("large-struct-macros" IN_LIST FEATURES)
    if(VCPKG_TARGET_IS_WINDOWS)
        set(BOOST_HANA_MAX_NUMBER_OF_MEMBERS 124)
    else()
        set(BOOST_HANA_MAX_NUMBER_OF_MEMBERS 200)
    endif()

    math(EXPR BOOST_HANA_GENERATOR_LIMIT "${BOOST_HANA_MAX_NUMBER_OF_MEMBERS} + 1")
    vcpkg_find_acquire_program(RUBY)
    vcpkg_execute_required_process(
        COMMAND "${RUBY}" -rerb -e "ENV['MAX_NUMBER_OF_MEMBERS'] = ARGV[0]; print ERB.new(File.read(ARGV[1])).result" "${BOOST_HANA_GENERATOR_LIMIT}" "${SOURCE_PATH}/include/boost/hana/detail/struct_macros.hpp.erb"
        WORKING_DIRECTORY "${SOURCE_PATH}"
        LOGNAME "boost-hana-generate-struct-macros"
        OUTPUT_VARIABLE _boost_hana_struct_macros
    )
    file(WRITE "${SOURCE_PATH}/include/boost/hana/detail/struct_macros.hpp" "${_boost_hana_struct_macros}")
    message(STATUS "boost-hana: generated struct_macros.hpp for up to ${BOOST_HANA_MAX_NUMBER_OF_MEMBERS} members")
endif()

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
