set(Z_VCPKG_FIRST_XCB_SEARCH OFF)
if(NOT XCB_FOUND)
    set(Z_VCPKG_FIRST_XCB_SEARCH ON)
endif()
set(z_vcpkg_xcb_args "${ARGS}") # Works since _find_package(X11) will not call _find_package(XCB)
find_package(X11 COMPONENTS Xau Xdmcp)
_find_package(${z_vcpkg_xcb_args})
if(TARGET XCB::XCB AND Z_VCPKG_FIRST_XCB_SEARCH)
    if(TARGET X11::Xdmcp)
        target_link_libraries(XCB::XCB INTERFACE X11::Xdmcp)
    endif()
    if(TARGET X11::Xau)
        target_link_libraries(XCB::XCB INTERFACE X11::Xau)
    endif()
endif()
if(TARGET XCB::IMAGE AND Z_VCPKG_FIRST_XCB_SEARCH)
    if(TARGET XCB::UTIL)
        target_link_libraries(XCB::IMAGE INTERFACE XCB::UTIL)
    endif()
endif()
unset(Z_VCPKG_FIRST_XCB_SEARCH)