# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/uuid
    REF boost-1.79.0
    SHA512 52a78598f7120906b03a6ecacf9997926c4e7f0f9696138f25ff75956b012010be5c1f212fb498b064cd94b420182857a17a750558758d82dad4b44d1bbeba47
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
