set(Boost_USE_STATIC_LIBS @BOOST_STATIC_LINKAGE@)
set(Boost_USE_MULTITHREADED ON)
set(Boost_NO_BOOST_CMAKE ON)
set(Boost_USE_STATIC_RUNTIME @BOOST_STATIC_CRT_LINKAGE@)
if("${CMAKE_VS_PLATFORM_TOOLSET}" STREQUAL "v120")
    set(Boost_COMPILER "-vc120")
else()
    set(Boost_COMPILER "-vc140")
endif()
_find_package(${ARGS})
