# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/ratio
    REF boost-1.78.0
    SHA512 2a17342379066361ef0187fc0e69734231afdc14463a26d20ed851e679989e9ee55619f1cd3694791d00dbe1c55da69d220db18c69df7493bcf7b47de563afc6
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
