# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lexical_cast
    REF boost-1.80.0.beta1
    SHA512 3128b3957aebf863b52d320885420414dfc9ef1df848972555159e11cbd368f90cebfe0ae388e22743ccb2058f74f84ed6bf6e48ccd67313fc2f315af1e1dde7
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
