# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/asio
    REF boost-1.74.0
    SHA512 2ef452044c19b9b8f8701d2d0e6db3764c925f53217f4507c8d60174bf08339188b0f793251756c0dd045cd0170fd8c89092b90ed79c31772530eeceef7639c3
    HEAD_REF master
    PATCHES windows_alloca_header.patch
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
