if(PORT STREQUAL "tbb")
    set(VCPKG_C_FLAGS "-mrtm")
    set(VCPKG_CXX_FLAGS "-mrtm")
endif()
if(PORT MATCHES "^(flint|folly|glog)$")
    # glog hardcodes builtin expected if build with clang-cl (#if 1 otehrwise #if 0)
    # TODO: Recheck flint
    message(STATUS "Falling back to cl!")
    unset(VCPKG_CHAINLOAD_TOOLCHAIN_FILE)
    unset(VCPKG_PLATFORM_TOOLSET)
    set(ENV{PATH} "${PATH_BACKUP}")
endif()