set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

if(PORT STREQUAL "xalan-c")
   set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()
if(PORT STREQUAL "xerces-c")
   set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()
