set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

#set(VCPKG_PLATFORM_TOOLSET v142)

set(VS_PLATFORM_TOOLSET "ClangCL,host=x64")

if(DEFINED VS_PLATFORM_TOOLSET)
    set(VCPKG_POLICY_SKIP_ARCHITECTURE_CHECK enabled)
endif()
