set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

set(VCPKG_BUILD_TYPE release) # save time by only building release libs
set(X_VCPKG_FORCE_VCPKG_X_LIBRARIES ON)
set(X_VCPKG_FORCE_VCPKG_WAYLAND_LIBRARIES ON)
set(X_VCPKG_FORCE_VCPKG_DRM_LIBRARIES ON) 