set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_PLATFORM_TOOLSET v140)
if(PORT MATCHES "bzip2|double-conversion|freetype|gettext|glib|harfbuzz|libffi|libiconv|libjpeg-turbo|libpng|libpq|openssl|pcre|qt5|sqlite3|zlib")
set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()
