set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_TRIPLET_PLATFORM_TOOLSET_SUFFIX xp)
set(VCPKG_TRIPLET_SUBSYSTEM Windows)
set(VCPKG_TRIPLET_SUBSYSTEM_VERSION 5.1)
