vcpkg_fail_port_install(ON_TARGET "uwp")

vcpkg_from_github(
  OUT_SOURCE_PATH SOURCE_PATH
  REPO Cisco-Talos/clamav-devel
  REF clamav-0.103.0 
  SHA512 488381202bdcea812c39d611e0a31eaf8f55c9c5d0a6400fd53dfa0da674a95672fdc9b290dc6157cb8f628d9f81846b5cc108eb1e44f6207d3c6f2659ba63c6
  HEAD_REF master
  PATCHES "build.patch"
)

vcpkg_configure_cmake(
  SOURCE_PATH ${SOURCE_PATH}
  PREFER_NINJA
)

vcpkg_install_cmake()

# Handle copyright
file(INSTALL ${SOURCE_PATH}/COPYING DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)

vcpkg_copy_tools(
    TOOL_NAMES clambc clamconf clamd clamdscan clamdtop clamscan clamsubmit freshclam sigtool
    SEARCH_DIR "${CURRENT_PACKAGES_DIR}"
)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/database")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/database")
file(MAKE_DIRECTORY "${CURRENT_PACKAGES_DIR}/lib")
file(MAKE_DIRECTORY "${CURRENT_PACKAGES_DIR}/debug/lib")
file(MAKE_DIRECTORY "${CURRENT_PACKAGES_DIR}/bin")
file(MAKE_DIRECTORY "${CURRENT_PACKAGES_DIR}/debug/bin")

if (NOT VCPKG_CMAKE_SYSTEM_NAME)
    file(RENAME "${CURRENT_PACKAGES_DIR}/clamav.lib" "${CURRENT_PACKAGES_DIR}/lib/clamav.lib")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/clambc.exe")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/clamconf.exe")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/clamd.conf.sample") 
    file(REMOVE "${CURRENT_PACKAGES_DIR}/clamd.exe")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/clamdscan.exe")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/clamdtop.exe")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/clamscan.exe")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/clamsubmit.exe")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/clamunrar.lib")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/clamunrar_iface.lib")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/freshclam.conf.sample")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/freshclam.exe")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/freshclam.lib")
    file(RENAME "${CURRENT_PACKAGES_DIR}/libclamav.dll" "${CURRENT_PACKAGES_DIR}/bin/libclamav.dll")
    file(RENAME "${CURRENT_PACKAGES_DIR}/libclamunrar.dll" "${CURRENT_PACKAGES_DIR}/bin/libclamunrar.dll")
    file(RENAME "${CURRENT_PACKAGES_DIR}/libclamunrar_iface.dll" "${CURRENT_PACKAGES_DIR}/bin/libclamunrar_iface.dll")
    file(RENAME "${CURRENT_PACKAGES_DIR}/libfreshclam.dll" "${CURRENT_PACKAGES_DIR}/bin/libfreshclam.dll")
    file(RENAME "${CURRENT_PACKAGES_DIR}/libmspack.dll" "${CURRENT_PACKAGES_DIR}/bin/libmspack.dll")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/mspack.lib")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/sigtool.exe")

    file(RENAME "${CURRENT_PACKAGES_DIR}/debug/clamav.lib" "${CURRENT_PACKAGES_DIR}/debug/lib/clamav.lib")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/clambc.exe")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/clamconf.exe")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/clamd.conf.sample")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/clamd.exe")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/clamdscan.exe")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/clamdtop.exe")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/clamscan.exe")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/clamsubmit.exe")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/clamunrar.lib")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/clamunrar_iface.lib")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/freshclam.conf.sample")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/freshclam.exe")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/freshclam.lib")
    file(RENAME "${CURRENT_PACKAGES_DIR}/debug/libclamav.dll" "${CURRENT_PACKAGES_DIR}/debug/bin/libclamav.dll")
    file(RENAME "${CURRENT_PACKAGES_DIR}/debug/libclamunrar.dll" "${CURRENT_PACKAGES_DIR}/debug/bin/libclamunrar.dll")
    file(RENAME "${CURRENT_PACKAGES_DIR}/debug/libclamunrar_iface.dll" "${CURRENT_PACKAGES_DIR}/debug/bin/libclamunrar_iface.dll")
    file(RENAME "${CURRENT_PACKAGES_DIR}/debug/libfreshclam.dll" "${CURRENT_PACKAGES_DIR}/debug/bin/libfreshclam.dll")
    file(RENAME "${CURRENT_PACKAGES_DIR}/debug/libmspack.dll" "${CURRENT_PACKAGES_DIR}/debug/bin/libmspack.dll")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/mspack.lib")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/sigtool.exe")
else()
    file(RENAME "${CURRENT_PACKAGES_DIR}/libclamav.a" "${CURRENT_PACKAGES_DIR}/lib/libclamav.a")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/clambc")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/clamconf")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/clamd.conf.sample") 
    file(REMOVE "${CURRENT_PACKAGES_DIR}/clamd")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/clamdscan")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/clamdtop")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/clamscan")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/clamsubmit")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/libclamunrar.a")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/libclamunrar_iface.a")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/freshclam.conf.sample")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/freshclam")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/libfreshclam.a")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/libmspack.a")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/sigtool")

    file(RENAME "${CURRENT_PACKAGES_DIR}/debug/libclamav.a" "${CURRENT_PACKAGES_DIR}/debug/lib/libclamav.a")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/clambc")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/clamconf")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/clamd.conf.sample")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/clamd")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/clamdscan")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/clamdtop")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/clamscan")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/clamsubmit")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/libclamunrar.a")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/libclamunrar_iface.a")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/freshclam.conf.sample")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/freshclam")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/libfreshclam.a")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/libmspack.a")
    file(REMOVE "${CURRENT_PACKAGES_DIR}/debug/sigtool")

    if(VCPKG_CMAKE_SYSTEM_NAME STREQUAL Linux)
        file(RENAME "${CURRENT_PACKAGES_DIR}/libclamav.so" "${CURRENT_PACKAGES_DIR}/bin/libclamav.so")
        file(RENAME "${CURRENT_PACKAGES_DIR}/libclamunrar.so" "${CURRENT_PACKAGES_DIR}/bin/libclamunrar.so")
        file(RENAME "${CURRENT_PACKAGES_DIR}/libclamunrar_iface.so" "${CURRENT_PACKAGES_DIR}/bin/libclamunrar_iface.so")
        file(RENAME "${CURRENT_PACKAGES_DIR}/libfreshclam.so" "${CURRENT_PACKAGES_DIR}/bin/libfreshclam.so")
        file(RENAME "${CURRENT_PACKAGES_DIR}/libmspack.so" "${CURRENT_PACKAGES_DIR}/bin/libmspack.so")
        file(RENAME "${CURRENT_PACKAGES_DIR}/debug/libclamav.so" "${CURRENT_PACKAGES_DIR}/debug/bin/libclamav.so")
        file(RENAME "${CURRENT_PACKAGES_DIR}/debug/libclamunrar.so" "${CURRENT_PACKAGES_DIR}/debug/bin/libclamunrar.so")
        file(RENAME "${CURRENT_PACKAGES_DIR}/debug/libclamunrar_iface.so" "${CURRENT_PACKAGES_DIR}/debug/bin/libclamunrar_iface.so")
        file(RENAME "${CURRENT_PACKAGES_DIR}/debug/libfreshclam.so" "${CURRENT_PACKAGES_DIR}/debug/bin/libfreshclam.so")
        file(RENAME "${CURRENT_PACKAGES_DIR}/debug/libmspack.so" "${CURRENT_PACKAGES_DIR}/debug/bin/libmspack.so")
    else()
        file(RENAME "${CURRENT_PACKAGES_DIR}/libclamav.dylib" "${CURRENT_PACKAGES_DIR}/bin/libclamav.dylib")
        file(RENAME "${CURRENT_PACKAGES_DIR}/libclamunrar.dylib" "${CURRENT_PACKAGES_DIR}/bin/libclamunrar.dylib")
        file(RENAME "${CURRENT_PACKAGES_DIR}/libclamunrar_iface.dylib" "${CURRENT_PACKAGES_DIR}/bin/libclamunrar_iface.dylib")
        file(RENAME "${CURRENT_PACKAGES_DIR}/libfreshclam.dylib" "${CURRENT_PACKAGES_DIR}/bin/libfreshclam.dylib")
        file(RENAME "${CURRENT_PACKAGES_DIR}/libmspack.dylib" "${CURRENT_PACKAGES_DIR}/bin/libmspack.dylib")
        file(RENAME "${CURRENT_PACKAGES_DIR}/debug/libclamav.dylib" "${CURRENT_PACKAGES_DIR}/debug/bin/libclamav.dylib")
        file(RENAME "${CURRENT_PACKAGES_DIR}/debug/libclamunrar.dylib" "${CURRENT_PACKAGES_DIR}/debug/bin/libclamunrar.dylib")
        file(RENAME "${CURRENT_PACKAGES_DIR}/debug/libclamunrar_iface.dylib" "${CURRENT_PACKAGES_DIR}/debug/bin/libclamunrar_iface.dylib")
        file(RENAME "${CURRENT_PACKAGES_DIR}/debug/libfreshclam.dylib" "${CURRENT_PACKAGES_DIR}/debug/bin/libfreshclam.dylib")
        file(RENAME "${CURRENT_PACKAGES_DIR}/debug/libmspack.dylib" "${CURRENT_PACKAGES_DIR}/debug/bin/libmspack.dylib")
    endif()
endif()
