vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)

vcpkg_from_github(
  OUT_SOURCE_PATH SOURCE_PATH
  REPO Cisco-Talos/clamav-devel
  REF clamav-0.104.2
  SHA512 A2439933FC023C4263BFDAB7B79D3669BC7F38DEBA40A3E1C514E4B68F00667AF025F0D6713A4B74B7AFF58CF86AFD49305A4A91991B00431040BE5CA71FFF55
  FILE_DISAMBIGUATOR 1
  HEAD_REF master
  PATCHES
      "cmakefiles.patch"
)

vcpkg_cmake_configure(
  SOURCE_PATH ${SOURCE_PATH}
  PREFER_NINJA
  OPTIONS
      -DENABLE_LIBCLAMAV_ONLY=ON
      -DENABLE_SHARED_LIB=ON
      -DENABLE_STATIC_LIB=OFF
      -DENABLE_TESTS=OFF
)

vcpkg_cmake_install()

# Handle copyright
file(INSTALL ${SOURCE_PATH}/COPYING.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/NEWS.md" "${CURRENT_PACKAGES_DIR}/debug/NEWS.md")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/README.md" "${CURRENT_PACKAGES_DIR}/debug/README.md")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/COPYING.txt" "${CURRENT_PACKAGES_DIR}/debug/COPYING.txt")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")

# On Linux, clamav will still build and install clamav-config
if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin" "${CURRENT_PACKAGES_DIR}/debug/bin")
endif()

vcpkg_copy_pdbs()
