cmake_minimum_required(VERSION 3.24)

# Use vcpkg packages without enabling eCAL's submodule dependency provider.
macro(ecal_vcpkg_dependencies method package_name)
    if("${package_name}" STREQUAL "CMakeFunctions")
        include("${CMAKE_SOURCE_DIR}/thirdparty/cmakefunctions/build-cmakefunctions.cmake")
        set(CMakeFunctions_FOUND TRUE)
    elseif("${package_name}" STREQUAL "tclap")
        find_path(TCLAP_INCLUDE_DIRS "tclap/Arg.h" REQUIRED)
        if(NOT TARGET tclap::tclap)
            add_library(tclap::tclap INTERFACE IMPORTED GLOBAL)
            set_target_properties(tclap::tclap PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${TCLAP_INCLUDE_DIRS}")
        endif()
        set(tclap_FOUND TRUE)
    elseif("${package_name}" STREQUAL "protozero")
        find_path(PROTOZERO_INCLUDE_DIRS "protozero/pbf_reader.hpp" REQUIRED)
        if(NOT TARGET protozero::protozero)
            add_library(protozero::protozero INTERFACE IMPORTED GLOBAL)
            set_target_properties(protozero::protozero PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${PROTOZERO_INCLUDE_DIRS}")
        endif()
        set(protozero_FOUND TRUE)
    else()
        find_package(${package_name} BYPASS_PROVIDER ${ARGN})
    endif()
endmacro()

cmake_language(SET_DEPENDENCY_PROVIDER ecal_vcpkg_dependencies SUPPORTED_METHODS FIND_PACKAGE)
