# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/iterator
    REF boost-1.79.0
    SHA512 26b0308126df522725887fcb9578d7e645f181cd8a6850915a5ce0c832a5f2e5521ba75a17f29a5eba788e3d8bd46d61ebb4b61fa40f233c33e99f83949516f6
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
