# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/msm
    REF boost-${VERSION}
    SHA512 5c42ff6dce21bd952d235861d1069d435ef88e59ae84a747180501d40a8c9670bc1d6938355624ad763fb7366406fd3c59f5e1a70fb30eabd49bf51a419e3058
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
