vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO realtimechris/jsonifier
    REF "v${VERSION}"
    # Auto-generated by release CI action at realtimechris/Jsonifier
    SHA512 a2c8c59afebfe5c05e6d8d83ef1481b399c13d4e5e430e5cac33c860fa7de51fbd97da5e2509ef62acf8451110779de95cd3bbbd59bf0a8777bba1dd1884502b
	HEAD_REF main
)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
)

vcpkg_cmake_install()

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug")

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/License.md")
