# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/intrusive
    REF boost-1.73.0
    SHA512 cbcb7238aee3609b2838d427fe2436915bc39f363320099592908765a1e143469e02383e0fb51c1f05f7f935fadd3738130c362bb6ba1da74a74f74daaee4d02
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
