# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/intrusive
    REF boost-1.79.0
    SHA512 4536cc104c2538d2c7a4e22882a27c47732b69ead76fd49d75592f582bc1873a0731753eb421ad67576467d731169333a1e95a39efb0e977512a58b407d59fb4
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
