# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/parameter_python
    REF boost-1.80.0.beta1
    SHA512 c12cafcf6df59ed5fe6fa1e7ebc0c0bb127423b4b8e8aad9e7e6542c8f27818a109078cc620ab3530b37ad56275047a79ee96c1b6cc7eae3169c4cd45df58d5e
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
