# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/any
    REF boost-1.74.0
    SHA512 6aa9fb5d579068909f3e6056484440a0d05459e0cc8cc740c6f8997c422451296759d3225305e07ead4d37fee7285519195c0d04bf68693944154701646972c4
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
