# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/scope_exit
    REF boost-1.69.0
    SHA512 d89d5793f1916218892e3a9c2b4b59d637a613a053be09a9f4b74d73413f98e100868ddccbfbcc7d42af154757836532a16d5301fdd9ac6878d94f8bb9ac7a0d
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
