set(VCPKG_POLICY_CMAKE_HELPER_PORT enabled)
set(FUNCTION_NAME x_vcpkg_find_fortran)
if(VCPKG_TARGET_IS_WINDOWS AND NOT VCPKG_TARGET_IS_MINGW)
    set(PORT_IMPL vcpkg-fortran-flang-classic)
    if(VCPKG_TARGET_ARCHITECTURE MATCHES "(x86|x64)")
        set(PORT_IMPL vcpkg-fortran-ifort)
    endif()
endif()
file(COPY "${CMAKE_CURRENT_LIST_DIR}/${FUNCTION_NAME}.cmake"
    DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
configure_file("${VCPKG_ROOT_DIR}/LICENSE.txt" "${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright" COPYONLY)
configure_file("${CMAKE_CURRENT_LIST_DIR}/vcpkg-port-config.cmake.in" "${CURRENT_PACKAGES_DIR}/share/${PORT}/vcpkg-port-config.cmake" @ONLY)
set(requires "${PORT_IMPL}")
configure_file("${CMAKE_CURRENT_LIST_DIR}/vcpkg-fortran.pc.in" "${CURRENT_PACKAGES_DIR}/lib/pkgconfig/vcpkg-fortran.pc" @ONLY)
if(NOT VCPKG_BUILD_TYPE)
    configure_file("${CMAKE_CURRENT_LIST_DIR}/vcpkg-fortran.pc.in" "${CURRENT_PACKAGES_DIR}/debug/lib/pkgconfig/vcpkg-fortran.pc" @ONLY)
endif()