# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/multi_array
    REF boost-1.79.0
    SHA512 5665ffa1b298320cd525b3d22a5e59c1c88a148672ed98295a00957b05316943f081821102c3881ba03b565d0c0879d11b0d3bdf1221a92fbfe4dddb98820074
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
