# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/units
    REF boost-1.76.0
    SHA512 84eff531365db19254d52ef0cdc31631a6806b766a8d2be6f01aaf0b468b367c8cd9f4979d2c28434c19c6377f8be5a42851f0e90bb876501738b1da9245ebb4
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
