# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/units
    REF boost-1.73.0
    SHA512 8137a82f4fdc3b204cc2879b2fc929b5c6937235bc3cdcda6419e84cc0b69ac523e6d18024c00bbff643a1f8561db4a46c00d3247314ad229c2b30f16676bc82
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
