vcpkg_from_github(
	OUT_SOURCE_PATH SOURCE_PATH
	REPO RealTimeChris/DiscordCoreAPI
	REF 40c918ed3cc36c7877493bf7fe03e3970a9fc9c5
	SHA512 4125eaac2fdabf9d3e509c6d4e559263d2714cbf31cdb064c278aed70490afdfb2890650b05d3d3f4a342269f196771fc9ff4b5ee101166f95437a9311396ff3
	HEAD_REF main
)


vcpkg_cmake_install()

add_subdirectory(Executable/Library)
install(TARGETS DiscordCoreAPI CONFIGURATIONS Debug RUNTIME DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" PUBLIC_HEADER DESTINATION "${CMAKE_INSTALL_PREFIX}/include/discordcoreapi")
install(TARGETS DiscordCoreAPI CONFIGURATIONS Release RUNTIME DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" PUBLIC_HEADER DESTINATION "${CMAKE_INSTALL_PREFIX}/include/discordcoreapi")
install(TARGETS DiscordCoreAPI CONFIGURATIONS Debug ARCHIVE DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" PUBLIC_HEADER DESTINATION "${CMAKE_INSTALL_PREFIX}/include/discordcoreapi")
install(TARGETS DiscordCoreAPI CONFIGURATIONS Release ARCHIVE DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" PUBLIC_HEADER DESTINATION "${CMAKE_INSTALL_PREFIX}/include/discordcoreapi")
install(FILES $<$<PLATFORM_ID:Windows>:$<TARGET_PDB_FILE:DiscordCoreAPI>> DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" OPTIONAL)
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/bin" "${CURRENT_PACKAGES_DIR}/bin")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")

file(
	INSTALL "${SOURCE_PATH}/License"
	DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}"
	RENAME copyright
)
