vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO rkriad585/Abscom
    REF v${VERSION}
    SHA512 F575902B215F31618191735E741D6C8DD41E84D2F0799A4C137FEAB0BD39C78D65A432FCBDB1F85E4620367B498ACDD593FE0FDF5EB6EA4D460D370A866D6C0B
    HEAD_REF main
)

string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "static" ABSCOM_BUILD_STATIC)
string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "dynamic" ABSCOM_BUILD_SHARED)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DABSCOM_BUILD_STATIC=${ABSCOM_BUILD_STATIC}
        -DABSCOM_BUILD_SHARED=${ABSCOM_BUILD_SHARED}
        -DABSCOM_BUILD_TESTS=OFF
        -DABSCOM_BUILD_EXAMPLES=OFF
)

vcpkg_cmake_install()
vcpkg_cmake_config_fixup(CONFIG_PATH "lib/cmake/Abscom")
vcpkg_fixup_pkgconfig()

file(REMOVE_RECURSE
    "${CURRENT_PACKAGES_DIR}/debug/include"
    "${CURRENT_PACKAGES_DIR}/debug/share"
)
if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/bin")
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/bin")
endif()
file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
vcpkg_copy_pdbs()
