vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO rkriad585/Abscom
    REF v${VERSION}
    SHA512 C8AE5351EBDCE00A059EDFDAA6367CAA6AFF65F10C08E3649E321F2799F12D401335AA1A54C69752BC53361CBDF30ACAFFDE8DBE2F0B87641C6CC7925C0F5F68
    HEAD_REF main
)

string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "static" ABSCOM_BUILD_STATIC)
string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "dynamic" ABSCOM_BUILD_SHARED)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DABSCOM_BUILD_STATIC=${ABSCOM_BUILD_STATIC}
        -DABSCOM_BUILD_SHARED=${ABSCOM_BUILD_SHARED}
        -DABSCOM_BUILD_TESTS=OFF
        -DABSCOM_BUILD_EXAMPLES=OFF
)

vcpkg_cmake_install()
vcpkg_cmake_config_fixup(CONFIG_PATH "lib/cmake/Abscom")
vcpkg_fixup_pkgconfig()

file(REMOVE_RECURSE
    "${CURRENT_PACKAGES_DIR}/debug/include"
    "${CURRENT_PACKAGES_DIR}/debug/share"
)
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/bin")
file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
vcpkg_copy_pdbs()
