# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/crc
    REF boost-1.80.0.beta1
    SHA512 72cbba80c7b05c9c44b3d238b0ad9b407c7f7504280eb23a2c3a9d1724785ea80edf448fb5e68b280cb283a2f478ffaa3266f4f7fb0ca2182eea21912f6e8a95
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
