# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/format
    REF boost-${VERSION}
    SHA512 9b38df8153c1bce2d44ef46858f09629fff6ed9e6665ae2c70ab34e6b607cdeeb1b0cbc29e80308246e531cea87acd0394ac535a3043f19c31dd048809675516
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
