# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/proto
    REF boost-${VERSION}
    SHA512 e50abc145858793dd9b23381b1c9e8c79763eae6d45a70f166b1c29f008a114911861f12ec3101da0e77f714e8805ec3ef97184c166a9e547e9eb3332e1c7296
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
