# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/proto
    REF boost-${VERSION}
    SHA512 39c4e11d3d87bdc0e533b55029ac0a3d2359984f1fdf94877552f1229fa3a6a34f53602f1ae3e55157ca0df1f59f35a026f58c258dae21180a370cd1d344fe21
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
