# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/proto
    REF boost-${VERSION}
    SHA512 54536923d229f49b8dc19a57ed2e1d2b275c9b618485f41d688dd183272e6e668e8602ba597de7a831bb5e312d966cf90627f35702886fbf5db46e74586a8eae
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
