include(SelectLibraryConfigurations)

find_path(UNRAR_INCLUDE_DIR NAMES unrar.h PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include" NO_DEFAULT_PATH)
find_library(UNRAR_LIBRARY_RELEASE NAMES unrar PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib" NO_DEFAULT_PATH)
find_library(UNRAR_LIBRARY_DEBUG   NAMES unrar PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug/lib" NO_DEFAULT_PATH)

select_library_configurations(UNRAR)
set(UNRAR_LIBRARIES ${UNRAR_LIBRARY})
