# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/leaf
    REF boost-1.80.0.beta1
    SHA512 897fbd076be27df399ca54bbfb41405cfb147d7a5651f50d8642024dee33679979f1ec3d81218db7c91137b9611395b31ee88334739b6f4491d6c99ea5bc012c
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
