# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/leaf
    REF boost-${VERSION}
    SHA512 6dfea8d8da748020c13392a1206aadd2558195c9bcd62a34ddc650be29544b075fe45a0d7ffebbd72223ece29faaf95b80a1efa1b2ce556dc9026c1eb7025219
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
