# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/xpressive
    REF boost-${VERSION}
    SHA512 f71251c77a4f9fea8e28ae74140369f51c2bf820385094e2111d2341d34fbff62c34031885196bf8f26db0618119a00a70c9664502cfb1c38f3d9ea018ebdcd9
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
