# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/cobalt
    REF boost-${VERSION}
    SHA512 fa280b607729f6f0cb9af77bbf9d5aae9add62474ff7916f0a9738a1ada527fecf050f85dd193912373133c813e4421e571e12ecde1085be1824fb25f3512073
    HEAD_REF master
    PATCHES
        fail-on-compiler-not-supported.patch
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
