# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/cobalt
    REF boost-${VERSION}
    SHA512 167e1d48eefe2517b9cd3796602798cb3d8d14655e30cb175b468f667fb8ae132aba508fc96987c4518d0a364aa9b70461d368c56b62d18fcd0f923cd6525e7f
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
