# This file is a shell script that caches the results of configure
ac_cv_c_compiler_gnu=${ac_cv_c_compiler_gnu=yes}
ac_cv_c_flexmember=${ac_cv_c_flexmember=yes}
ac_cv_c_restrict=${ac_cv_c_restrict=__restrict__}
ac_cv_c_undeclared_builtin_options=${ac_cv_c_undeclared_builtin_options='none needed'}
ac_cv_c_vararrays=${ac_cv_c_vararrays=yes}
ac_cv_cxx_compiler_gnu=${ac_cv_cxx_compiler_gnu=yes}
ac_cv_exeext=${ac_cv_exeext=.exe}
ac_cv_func__NSGetExecutablePath=${ac_cv_func__NSGetExecutablePath=no}
ac_cv_func___fsetlocking=${ac_cv_func___fsetlocking=no}
ac_cv_func__set_invalid_parameter_handler=${ac_cv_func__set_invalid_parameter_handler=yes}
ac_cv_func_alloca_works=${ac_cv_func_alloca_works=yes}
ac_cv_func_asprintf=${ac_cv_func_asprintf=yes}
ac_cv_func_atexit=${ac_cv_func_atexit=yes}
ac_cv_func_canonicalize_file_name=${ac_cv_func_canonicalize_file_name=no}
ac_cv_func_duplocale=${ac_cv_func_duplocale=no}
ac_cv_func_faccessat=${ac_cv_func_faccessat=no}
ac_cv_func_fcntl=${ac_cv_func_fcntl=no}
ac_cv_func_freelocale=${ac_cv_func_freelocale=no}
ac_cv_func_getcwd=${ac_cv_func_getcwd=yes}
ac_cv_func_getdtablesize=${ac_cv_func_getdtablesize=no}
ac_cv_func_getegid=${ac_cv_func_getegid=no}
ac_cv_func_geteuid=${ac_cv_func_geteuid=no}
ac_cv_func_getexecname=${ac_cv_func_getexecname=no}
ac_cv_func_getgid=${ac_cv_func_getgid=no}
ac_cv_func_getopt_long_only=${ac_cv_func_getopt_long_only=yes}
ac_cv_func_getpagesize=${ac_cv_func_getpagesize=yes}
ac_cv_func_getprogname=${ac_cv_func_getprogname=no}
ac_cv_func_getuid=${ac_cv_func_getuid=no}
ac_cv_func_iswblank=${ac_cv_func_iswblank=yes}
ac_cv_func_iswcntrl=${ac_cv_func_iswcntrl=yes}
ac_cv_func_lstat=${ac_cv_func_lstat=no}
ac_cv_func_malloc_0_nonnull=${ac_cv_func_malloc_0_nonnull=yes}
ac_cv_func_mbrtowc=${ac_cv_func_mbrtowc=yes}
ac_cv_func_mbsinit=${ac_cv_func_mbsinit=yes}
ac_cv_func_mbslen=${ac_cv_func_mbslen=no}
ac_cv_func_memmove=${ac_cv_func_memmove=yes}
ac_cv_func_mempcpy=${ac_cv_func_mempcpy=yes}
ac_cv_func_mmap=${ac_cv_func_mmap=no}
ac_cv_func_mmap_fixed_mapped=${ac_cv_func_mmap_fixed_mapped=no}
ac_cv_func_mprotect=${ac_cv_func_mprotect=yes}
ac_cv_func_munmap=${ac_cv_func_munmap=no}
ac_cv_func_newlocale=${ac_cv_func_newlocale=no}
ac_cv_func_putenv=${ac_cv_func_putenv=yes}
ac_cv_func_raise=${ac_cv_func_raise=yes}
ac_cv_func_rawmemchr=${ac_cv_func_rawmemchr=no}
ac_cv_func_readlink=${ac_cv_func_readlink=no}
ac_cv_func_readlinkat=${ac_cv_func_readlinkat=no}
ac_cv_func_realloc_0_nonnull=${ac_cv_func_realloc_0_nonnull=yes}
ac_cv_func_reallocarray=${ac_cv_func_reallocarray=no}
ac_cv_func_realpath=${ac_cv_func_realpath=no}
ac_cv_func_setdtablesize=${ac_cv_func_setdtablesize=no}
ac_cv_func_setenv=${ac_cv_func_setenv=no}
ac_cv_func_setlocale=${ac_cv_func_setlocale=yes}
ac_cv_func_snprintf=${ac_cv_func_snprintf=yes}
ac_cv_func_stpcpy=${ac_cv_func_stpcpy=no}
ac_cv_func_strcasecmp=${ac_cv_func_strcasecmp=yes}
ac_cv_func_strerror_r_char_p=${ac_cv_func_strerror_r_char_p=no}
ac_cv_func_strnlen=${ac_cv_func_strnlen=yes}
ac_cv_func_strnlen_working=${ac_cv_func_strnlen_working=yes}
ac_cv_func_strtoul=${ac_cv_func_strtoul=yes}
ac_cv_func_symlink=${ac_cv_func_symlink=no}
ac_cv_func_tsearch=${ac_cv_func_tsearch=yes}
ac_cv_func_uselocale=${ac_cv_func_uselocale=no}
ac_cv_func_wcrtomb=${ac_cv_func_wcrtomb=yes}
ac_cv_func_wcslen=${ac_cv_func_wcslen=yes}
ac_cv_func_wcsnlen=${ac_cv_func_wcsnlen=yes}
ac_cv_func_wcwidth=${ac_cv_func_wcwidth=no}
ac_cv_func_wprintf=${ac_cv_func_wprintf=yes}
ac_cv_gnu_library_2=${ac_cv_gnu_library_2=no}
ac_cv_have_decl___argv=${ac_cv_have_decl___argv=yes}
ac_cv_have_decl__snprintf=${ac_cv_have_decl__snprintf=yes}
ac_cv_have_decl__snwprintf=${ac_cv_have_decl__snwprintf=yes}
ac_cv_have_decl_clearerr_unlocked=${ac_cv_have_decl_clearerr_unlocked=no}
ac_cv_have_decl_ecvt=${ac_cv_have_decl_ecvt=yes}
ac_cv_have_decl_execvpe=${ac_cv_have_decl_execvpe=yes}
ac_cv_have_decl_fcloseall=${ac_cv_have_decl_fcloseall=yes}
ac_cv_have_decl_fcvt=${ac_cv_have_decl_fcvt=yes}
ac_cv_have_decl_feof_unlocked=${ac_cv_have_decl_feof_unlocked=no}
ac_cv_have_decl_ferror_unlocked=${ac_cv_have_decl_ferror_unlocked=no}
ac_cv_have_decl_fflush_unlocked=${ac_cv_have_decl_fflush_unlocked=no}
ac_cv_have_decl_fgets_unlocked=${ac_cv_have_decl_fgets_unlocked=no}
ac_cv_have_decl_fputc_unlocked=${ac_cv_have_decl_fputc_unlocked=no}
ac_cv_have_decl_fputs_unlocked=${ac_cv_have_decl_fputs_unlocked=no}
ac_cv_have_decl_fread_unlocked=${ac_cv_have_decl_fread_unlocked=no}
ac_cv_have_decl_fwrite_unlocked=${ac_cv_have_decl_fwrite_unlocked=no}
ac_cv_have_decl_gcvt=${ac_cv_have_decl_gcvt=yes}
ac_cv_have_decl_getc_unlocked=${ac_cv_have_decl_getc_unlocked=no}
ac_cv_have_decl_getchar_unlocked=${ac_cv_have_decl_getchar_unlocked=no}
ac_cv_have_decl_getdtablesize=${ac_cv_have_decl_getdtablesize=no}
ac_cv_have_decl_iswblank=${ac_cv_have_decl_iswblank=yes}
ac_cv_have_decl_program_invocation_name=${ac_cv_have_decl_program_invocation_name=no}
ac_cv_have_decl_program_invocation_short_name=${ac_cv_have_decl_program_invocation_short_name=no}
ac_cv_have_decl_putc_unlocked=${ac_cv_have_decl_putc_unlocked=no}
ac_cv_have_decl_putchar_unlocked=${ac_cv_have_decl_putchar_unlocked=no}
ac_cv_have_decl_setenv=${ac_cv_have_decl_setenv=no}
ac_cv_have_decl_strerror_r=${ac_cv_have_decl_strerror_r=no}
ac_cv_have_decl_strnlen=${ac_cv_have_decl_strnlen=yes}
ac_cv_have_decl_wcsdup=${ac_cv_have_decl_wcsdup=yes}
ac_cv_have_decl_wcwidth=${ac_cv_have_decl_wcwidth=no}
ac_cv_header_crtdefs_h=${ac_cv_header_crtdefs_h=yes}
ac_cv_header_dlfcn_h=${ac_cv_header_dlfcn_h=no}
ac_cv_header_features_h=${ac_cv_header_features_h=no}
ac_cv_header_getopt_h=${ac_cv_header_getopt_h=yes}
ac_cv_header_iconv_h=${ac_cv_header_iconv_h=yes}
ac_cv_header_inttypes_h=${ac_cv_header_inttypes_h=yes}
ac_cv_header_langinfo_h=${ac_cv_header_langinfo_h=no}
ac_cv_header_limits_h=${ac_cv_header_limits_h=yes}
ac_cv_header_mach_o_dyld_h=${ac_cv_header_mach_o_dyld_h=no}
ac_cv_header_minix_config_h=${ac_cv_header_minix_config_h=no}
ac_cv_header_pthread_h=${ac_cv_header_pthread_h=yes}
ac_cv_header_sdkddkver_h=${ac_cv_header_sdkddkver_h=yes}
ac_cv_header_search_h=${ac_cv_header_search_h=yes}
ac_cv_header_stat_broken=${ac_cv_header_stat_broken=no}
ac_cv_header_stdbool_h=${ac_cv_header_stdbool_h=no}
ac_cv_header_stddef_h=${ac_cv_header_stddef_h=yes}
ac_cv_header_stdint_h=${ac_cv_header_stdint_h=yes}
ac_cv_header_stdio_h=${ac_cv_header_stdio_h=yes}
ac_cv_header_stdlib_h=${ac_cv_header_stdlib_h=yes}
ac_cv_header_string_h=${ac_cv_header_string_h=yes}
ac_cv_header_strings_h=${ac_cv_header_strings_h=yes}
ac_cv_header_sys_cdefs_h=${ac_cv_header_sys_cdefs_h=yes}
ac_cv_header_sys_mman_h=${ac_cv_header_sys_mman_h=no}
ac_cv_header_sys_param_h=${ac_cv_header_sys_param_h=yes}
ac_cv_header_sys_single_threaded_h=${ac_cv_header_sys_single_threaded_h=no}
ac_cv_header_sys_socket_h=${ac_cv_header_sys_socket_h=no}
ac_cv_header_sys_stat_h=${ac_cv_header_sys_stat_h=yes}
ac_cv_header_sys_time_h=${ac_cv_header_sys_time_h=yes}
ac_cv_header_sys_types_h=${ac_cv_header_sys_types_h=yes}
ac_cv_header_threads_h=${ac_cv_header_threads_h=no}
ac_cv_header_unistd_h=${ac_cv_header_unistd_h=yes}
ac_cv_header_wchar_h=${ac_cv_header_wchar_h=yes}
ac_cv_header_wctype_h=${ac_cv_header_wctype_h=yes}
ac_cv_header_winsock2_h=${ac_cv_header_winsock2_h=yes}
ac_cv_header_xlocale_h=${ac_cv_header_xlocale_h=no}
ac_cv_lib_error_at_line=${ac_cv_lib_error_at_line=no}
ac_cv_lib_pthread_pthread_kill=${ac_cv_lib_pthread_pthread_kill=yes}
ac_cv_member_struct_stat_st_atim_st__tim_tv_nsec=${ac_cv_member_struct_stat_st_atim_st__tim_tv_nsec=no}
ac_cv_member_struct_stat_st_atim_tv_nsec=${ac_cv_member_struct_stat_st_atim_tv_nsec=no}
ac_cv_member_struct_stat_st_atimensec=${ac_cv_member_struct_stat_st_atimensec=no}
ac_cv_member_struct_stat_st_atimespec_tv_nsec=${ac_cv_member_struct_stat_st_atimespec_tv_nsec=no}
ac_cv_member_struct_stat_st_birthtim_tv_nsec=${ac_cv_member_struct_stat_st_birthtim_tv_nsec=no}
ac_cv_member_struct_stat_st_birthtimensec=${ac_cv_member_struct_stat_st_birthtimensec=no}
ac_cv_member_struct_stat_st_birthtimespec_tv_nsec=${ac_cv_member_struct_stat_st_birthtimespec_tv_nsec=no}
ac_cv_safe_to_define___extensions__=${ac_cv_safe_to_define___extensions__=yes}
ac_cv_should_define__xopen_source=${ac_cv_should_define__xopen_source=no}
ac_cv_sys_file_offset_bits=${ac_cv_sys_file_offset_bits=64}
ac_cv_sys_largefile_CC=${ac_cv_sys_largefile_CC=no}
ac_cv_type__Bool=${ac_cv_type__Bool=yes}
ac_cv_type_long_long_int=${ac_cv_type_long_long_int=yes}
ac_cv_type_mbstate_t=${ac_cv_type_mbstate_t=yes}
ac_cv_type_mode_t=${ac_cv_type_mode_t=yes}
ac_cv_type_nlink_t=${ac_cv_type_nlink_t=no}
ac_cv_type_pid_t=${ac_cv_type_pid_t=yes}
ac_cv_type_ptrdiff_t=${ac_cv_type_ptrdiff_t=yes}
ac_cv_type_sighandler_t=${ac_cv_type_sighandler_t=no}
ac_cv_type_sigset_t=${ac_cv_type_sigset_t=no}
ac_cv_type_size_t=${ac_cv_type_size_t=yes}
ac_cv_type_uid_t=${ac_cv_type_uid_t=no}
ac_cv_type_unsigned_long_long_int=${ac_cv_type_unsigned_long_long_int=yes}
ac_cv_type_volatile_sig_atomic_t=${ac_cv_type_volatile_sig_atomic_t=yes}
ac_cv_working_alloca_h=${ac_cv_working_alloca_h=no}
acl_cv_hardcode_direct=${acl_cv_hardcode_direct=no}
acl_cv_hardcode_libdir_flag_spec=${acl_cv_hardcode_libdir_flag_spec='-L$libdir'}
acl_cv_hardcode_libdir_separator=${acl_cv_hardcode_libdir_separator=}
acl_cv_hardcode_minus_L=${acl_cv_hardcode_minus_L=no}
acl_cv_libdirstems=${acl_cv_libdirstems=lib,lib,lib}
acl_cv_libext=${acl_cv_libext=a}
acl_cv_libname_spec=${acl_cv_libname_spec='lib$name'}
acl_cv_libpath=${acl_cv_libpath=PATH}
acl_cv_library_names_spec=${acl_cv_library_names_spec='$libname.dll.a $libname.lib'}
acl_cv_prog_gnu_ld=${acl_cv_prog_gnu_ld=yes}
acl_cv_rpath=${acl_cv_rpath=done}
acl_cv_shlibext=${acl_cv_shlibext=dll}
acl_cv_shlibpath_var=${acl_cv_shlibpath_var=PATH}
acl_cv_wl=${acl_cv_wl=-Wl,}
am_cv_CC_dependencies_compiler_type=${am_cv_CC_dependencies_compiler_type=none}
am_cv_CXX_dependencies_compiler_type=${am_cv_CXX_dependencies_compiler_type=none}
am_cv_func_iconv=${am_cv_func_iconv=yes}
am_cv_func_iconv_works=${am_cv_func_iconv_works=yes}
am_cv_langinfo_codeset=${am_cv_langinfo_codeset=no}
am_cv_lib_iconv=${am_cv_lib_iconv=yes}
am_cv_make_support_nested_variables=${am_cv_make_support_nested_variables=yes}
am_cv_prog_cc_c_o=${am_cv_prog_cc_c_o=yes}
gl_cv___builtin_expect=${gl_cv___builtin_expect=yes}
gl_cv_c_amsterdam_compiler=${gl_cv_c_amsterdam_compiler=no}
gl_cv_c_multiarch=${gl_cv_c_multiarch=no}
gl_cv_cc_vis_werror=${gl_cv_cc_vis_werror=yes}
gl_cv_cc_visibility=${gl_cv_cc_visibility=yes}
gl_cv_compiler_check_decl_option=${gl_cv_compiler_check_decl_option=none}
gl_cv_compiler_clang=${gl_cv_compiler_clang=no}
gl_cv_decl_null_works=${gl_cv_decl_null_works=yes}
gl_cv_double_slash_root=${gl_cv_double_slash_root=yes}
gl_cv_elf=${gl_cv_elf=no}
gl_cv_func_dup2_works=${gl_cv_func_dup2_works=no}
gl_cv_func_free_preserves_errno=${gl_cv_func_free_preserves_errno=no}
gl_cv_func_iswcntrl_works=${gl_cv_func_iswcntrl_works=yes}
gl_cv_func_lstat_dereferences_slashed_symlink=${gl_cv_func_lstat_dereferences_slashed_symlink=no}
gl_cv_func_malloc_0_nonnull=${gl_cv_func_malloc_0_nonnull=1}
gl_cv_func_malloc_posix=${gl_cv_func_malloc_posix=no}
gl_cv_func_mbrtowc_C_locale_sans_EILSEQ=${gl_cv_func_mbrtowc_C_locale_sans_EILSEQ=yes}
gl_cv_func_mbrtowc_empty_input=${gl_cv_func_mbrtowc_empty_input=yes}
gl_cv_func_mbrtowc_incomplete_state=${gl_cv_func_mbrtowc_incomplete_state='guessing yes'}
gl_cv_func_mbrtowc_nul_retval=${gl_cv_func_mbrtowc_nul_retval='guessing yes'}
gl_cv_func_mbrtowc_null_arg1=${gl_cv_func_mbrtowc_null_arg1='guessing yes'}
gl_cv_func_mbrtowc_null_arg2=${gl_cv_func_mbrtowc_null_arg2='guessing yes'}
gl_cv_func_mbrtowc_retval=${gl_cv_func_mbrtowc_retval=no}
gl_cv_func_mbrtowc_sanitycheck=${gl_cv_func_mbrtowc_sanitycheck='guessing yes'}
gl_cv_func_mbrtowc_stores_incomplete=${gl_cv_func_mbrtowc_stores_incomplete=no}
gl_cv_func_memchr_works=${gl_cv_func_memchr_works=yes}
gl_cv_func_printf_attribute_flavor=${gl_cv_func_printf_attribute_flavor=gnu}
gl_cv_func_realpath_works=${gl_cv_func_realpath_works=no}
gl_cv_func_setlocale_null_all_mtsafe=${gl_cv_func_setlocale_null_all_mtsafe=yes}
gl_cv_func_setlocale_null_one_mtsafe=${gl_cv_func_setlocale_null_one_mtsafe=yes}
gl_cv_func_strerror_0_works=${gl_cv_func_strerror_0_works=yes}
gl_cv_func_strtoul_works=${gl_cv_func_strtoul_works=no}
gl_cv_func_wcwidth_macro=${gl_cv_func_wcwidth_macro=no}
gl_cv_have_include_next=${gl_cv_have_include_next=yes}
gl_cv_header_errno_h_EMULTIHOP=${gl_cv_header_errno_h_EMULTIHOP=no}
gl_cv_header_errno_h_EOVERFLOW=${gl_cv_header_errno_h_EOVERFLOW=yes}
gl_cv_header_errno_h_complete=${gl_cv_header_errno_h_complete=no}
gl_cv_header_inttypes_h=${gl_cv_header_inttypes_h=yes}
gl_cv_header_limits_width=${gl_cv_header_limits_width=no}
gl_cv_header_locale_h_needs_xlocale_h=${gl_cv_header_locale_h_needs_xlocale_h=no}
gl_cv_header_locale_h_posix2001=${gl_cv_header_locale_h_posix2001=no}
gl_cv_header_locale_has_locale_t=${gl_cv_header_locale_has_locale_t=no}
gl_cv_header_signal_h_SIGPIPE=${gl_cv_header_signal_h_SIGPIPE=no}
gl_cv_header_stdint_h=${gl_cv_header_stdint_h=yes}
gl_cv_header_stdint_width=${gl_cv_header_stdint_width=no}
gl_cv_header_stdint_without_STDC_macros=${gl_cv_header_stdint_without_STDC_macros=yes}
gl_cv_header_working_fcntl_h=${gl_cv_header_working_fcntl_h=no}
gl_cv_header_working_stdalign_h=${gl_cv_header_working_stdalign_h=yes}
gl_cv_header_working_stdint_h=${gl_cv_header_working_stdint_h=yes}
gl_cv_iconv_nonconst=${gl_cv_iconv_nonconst=yes}
gl_cv_ld_autoimport=${gl_cv_ld_autoimport=no}
gl_cv_macro_O_CLOEXEC=${gl_cv_macro_O_CLOEXEC=no}
gl_cv_member_st_size_64=${gl_cv_member_st_size_64=no}
gl_cv_minmax_in_limits_h=${gl_cv_minmax_in_limits_h=no}
gl_cv_minmax_in_sys_param_h=${gl_cv_minmax_in_sys_param_h=no}
gl_cv_time_h_has_TIME_UTC=${gl_cv_time_h_has_TIME_UTC=no}
gl_cv_type_max_align_t=${gl_cv_type_max_align_t=yes}
gl_cv_type_off_t_64=${gl_cv_type_off_t_64=yes}
gl_cv_type_sigset_t=${gl_cv_type_sigset_t=no}
gl_cv_type_time_t_y2038=${gl_cv_type_time_t_y2038=yes}
gl_cv_type_wctrans_t=${gl_cv_type_wctrans_t=yes}
gl_cv_type_wctype_t=${gl_cv_type_wctype_t=yes}
gl_cv_type_wint_t_large_enough=${gl_cv_type_wint_t_large_enough=no}
gt_cv_c_intmax_t=${gt_cv_c_intmax_t=yes}
gt_cv_c_wchar_t=${gt_cv_c_wchar_t=yes}
gt_cv_c_wint_t=${gt_cv_c_wint_t=yes}
gt_cv_func_CFLocaleCopyPreferredLanguages=${gt_cv_func_CFLocaleCopyPreferredLanguages=no}
gt_cv_func_CFPreferencesCopyAppValue=${gt_cv_func_CFPreferencesCopyAppValue=no}
gt_cv_func_printf_posix=${gt_cv_func_printf_posix=no}
gt_cv_func_uselocale_works=${gt_cv_func_uselocale_works=no}
gt_cv_int_divbyzero_sigfpe=${gt_cv_int_divbyzero_sigfpe=yes}
gt_cv_ssize_t=${gt_cv_ssize_t=yes}
gt_cv_val_LC_MESSAGES=${gt_cv_val_LC_MESSAGES=no}
gt_cv_var_environ_declaration=${gt_cv_var_environ_declaration=yes}
nls_cv_force_use_gnu_gettext=${nls_cv_force_use_gnu_gettext=yes}
nls_cv_use_gnu_gettext=${nls_cv_use_gnu_gettext=yes}
