message(STATUS "Using VCPKG Findxaudio2redist")
set(XAUDIO2_PREV_MODULE_PATH ${CMAKE_MODULE_PATH})
list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})

list(REMOVE_ITEM ARGS "NO_MODULE")
list(REMOVE_ITEM ARGS "CONFIG")
list(REMOVE_ITEM ARGS "MODULE")

_find_package(${ARGS})

set(CMAKE_MODULE_PATH ${XAUDIO2_PREV_MODULE_PATH})
