# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/io
    REF boost-1.80.0.beta1
    SHA512 90f1e947266e7a61fb68dacd5c67f935629a5d21613ff91273f7f980f5c7eee803ebcda1e75b7b2a6f44ab748f5ff3b100e933bc846a64939db617a98976e184
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
