# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/assign
    REF boost-${VERSION}
    SHA512 f8d19f9b7873e09a39f2635925f9184136e2961c2508e019979dbd477e7858239e07d4fa67ec38a364e7ddaf52c09d8fa30e823997b7423d7c024ff6e79a9fb8
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
