# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/assign
    REF boost-1.79.0
    SHA512 0db0b6f4a93f8bd6d86a4db6390b7edc7717a490323121418c120e2d2b20322b73a6c7d9b18a4d7df357c7d36e111b548e78c72d32888089b460956476b8360b
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
