include(vcpkg_common_functions)

if(NOT VCPKG_TARGET_ARCHITECTURE STREQUAL "x64")
  message(FATAL_ERROR "Apache Arrow only supports x64")
endif()

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO apache/arrow
    REF apache-arrow-0.9.0
    SHA512 789d0948eee3af20eb922e09c14eb721f20fa041ca3c0cf57bd869718fc9919b45590bd72714efafdf19196f35abb6bdbe0a3972ca74fcc2af92c1f9ade8fa00
    HEAD_REF master
)

set(CPP_SOURCE_PATH "${SOURCE_PATH}/cpp")

vcpkg_apply_patches(
    SOURCE_PATH ${SOURCE_PATH}
    PATCHES
    "${CMAKE_CURRENT_LIST_DIR}/all.patch"
)

string(COMPARE EQUAL ${VCPKG_LIBRARY_LINKAGE} "dynamic" ARROW_BUILD_SHARED)
string(COMPARE EQUAL ${VCPKG_LIBRARY_LINKAGE} "static" ARROW_BUILD_STATIC)

vcpkg_configure_cmake(
    SOURCE_PATH ${CPP_SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
    -DARROW_BUILD_TESTS=off
    -DRAPIDJSON_HOME=${CURRENT_INSTALLED_DIR}
    -DFLATBUFFERS_HOME=${CURRENT_INSTALLED_DIR}
    -DARROW_ZLIB_VENDORED=ON
    -DBROTLI_HOME=${CURRENT_INSTALLED_DIR}
    -DLZ4_HOME=${CURRENT_INSTALLED_DIR}
    -DZSTD_HOME=${CURRENT_INSTALLED_DIR}
    -DSNAPPY_HOME=${CURRENT_INSTALLED_DIR}
    -DBOOST_ROOT=${CURRENT_INSTALLED_DIR}
    -DGFLAGS_HOME=${CURRENT_INSTALLED_DIR}
    -DZLIB_HOME=${CURRENT_INSTALLED_DIR}
    -DARROW_BUILD_STATIC=${ARROW_BUILD_STATIC}
    -DARROW_BUILD_SHARED=${ARROW_BUILD_SHARED}
)

vcpkg_install_cmake()

if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
    file(RENAME ${CURRENT_PACKAGES_DIR}/lib/arrow_static.lib ${CURRENT_PACKAGES_DIR}/lib/arrow.lib)
    file(RENAME ${CURRENT_PACKAGES_DIR}/debug/lib/arrow_static.lib ${CURRENT_PACKAGES_DIR}/debug/lib/arrow.lib)
    file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/bin ${CURRENT_PACKAGES_DIR}/bin)
else()
    file(REMOVE ${CURRENT_PACKAGES_DIR}/lib/arrow_static.lib ${CURRENT_PACKAGES_DIR}/debug/lib/arrow_static.lib)
endif()

file(INSTALL ${SOURCE_PATH}/LICENSE.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/arrow RENAME copyright)

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)
