
string(APPEND VCPKG_C_FLAGS " -DVCPKG_LET_ME_PASS")
string(APPEND VCPKG_CXX_FLAGS " -DVCPKG_LET_ME_PASS")

vcpkg_cmake_configure(
    SOURCE_PATH "${CMAKE_CURRENT_LIST_DIR}"
)

set(VCPKG_POLICY_EMPTY_PACKAGE enabled)