_find_package(${ARGS})
foreach(T brotlicommon brotlidec brotlienc)
    if(TARGET unofficial::brotli::${T} AND NOT TARGET unofficial::brotli::${T}-static)
        _add_library(unofficial::brotli::${T}-static INTERFACE IMPORTED)
        set_target_properties(unofficial::brotli::${T}-static PROPERTIES INTERFACE_LINK_LIBRARIES "unofficial::brotli::${T}")
    endif()
    if(NOT TARGET unofficial::brotli::${T} AND TARGET unofficial::brotli::${T}-static)
        _add_library(unofficial::brotli::${T} INTERFACE IMPORTED)
        set_target_properties(unofficial::brotli::${T} PROPERTIES INTERFACE_LINK_LIBRARIES "unofficial::brotli::${T}-static")
    endif()
endforeach()
