# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/fusion
    REF boost-1.80.0.beta1
    SHA512 49e095a4e9004b9a783b1a12bed73e702f21316aeb626f11637c7d4e70ade42d5b4c32365d8010ba970558801a1b47d75925ec41523ce5a9fd77cafa99791bba
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
