# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/hof
    REF boost-${VERSION}
    SHA512 828e7a51be0d24edc5401adb7d40ca868538cc7b16e30de817f196e5e98869bd8cb43580a34854bd004628a6137181d7ee8eb166e5c9d45ab979db53cd0a0747
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
