# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/hof
    REF boost-1.76.0
    SHA512 40d70bd531c1c69bcefe0105001ff9c423e23029197a60e46c163abf2b66c726e7d8411503c1201946a1d6d0aa8aef5caded9942968b7844023fbe023a1509c8
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
