include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/../vcpkg-cmake-get-vars/vcpkg-port-config.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/../vcpkg-pkgconfig-get-modules/vcpkg-port-config.cmake" OPTIONAL)
include("${CMAKE_CURRENT_LIST_DIR}/z_vcpkg_msbuild_create_props.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/vcpkg_msbuild_install.cmake")
