# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/redis
    REF boost-${VERSION}
    SHA512 797ae657ada8515778da71ff58c87b8bd45b3236423e433c535b8789e546c90905b9b5475c785307ebaf9b400fb9ec3d3255b5b323f0a17b275a0af92c708ba1
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
