# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/redis
    REF boost-${VERSION}
    SHA512 cf1deb15a25b30610faf01909ef3578b69edc00a4e87228fadb113569395ea9df7b1a31a1a4642944f26eb87e114412687d25782f8485b15ec1746408444cd18
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
