# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/log
    REF boost-${VERSION}
    SHA512 8acb1655e070429b025c3252d223c4e539c208d6f7a57b40acfdd5d01cfdcedf724b2ef34b70a458b64118e133b6a62802196398891987c17bd018908827fd16
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
