# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/log
    REF boost-${VERSION}
    SHA512 a5e4c5085bdfe2c0802a84561570075708cfbb11425b1bbd22179792862f0b65e22b7f6beb1967f45ba9a2798c84da1caf9acf4fc7e215fedb4d1467569a9476
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
