# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/histogram
    REF boost-${VERSION}
    SHA512 4b6dca9215918df054b0bc75351df578d56c451a150c503a01d166892da6a0842387f9df0679e5ec6eb6a7381b8746f05f3ff01433587619c07eed5dd7d27800
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
