# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/histogram
    REF boost-1.70.0
    SHA512 0eb1b9c64de27e0364c965710208d85ce2e19c009d88c4969a53f11dfb774c38bcfe1ed48bdc896e6e695bb536879e0ef1ce3ed2c7e72e15c3e480c7b625623f
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
