# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/outcome
    REF boost-1.80.0
    SHA512 0ee69623ddfda236dee7c6a07ed251cc5a2e17523078fd4006a5fd46a06e670fdfe833ab48bc46f4859144b42ce8da269d5ea941094e2eb5207ea1533939ae26
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
