# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/outcome
    REF boost-1.75.0
    SHA512 838c4a0a698cf3250891ef02184669d14e0891f366c52e646e76b25727be5d2fc0596a3ed95ac18f5d180ea35a1c24db3b8e8913277d62683908900d0394b9b1
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
