include(FindPackageHandleStandardArgs)
include(SelectLibraryConfigurations)

find_path(READOSM_INCLUDE_DIR NAMES readosm.h HINTS ${CURRENT_INSTALLED_DIR}/include)

find_library(READOSM_LIBRARY_DEBUG NAMES readosm_d readosm_i_d readosm NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug" NO_DEFAULT_PATH REQUIRED)
find_library(READOSM_LIBRARY_RELEASE NAMES readosm_i readosm NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" NO_DEFAULT_PATH REQUIRED)

select_library_configurations(READOSM)

set(READOSM_INCLUDE_DIRS ${READOSM_INCLUDE_DIR})
set(READOSM_LIBRARIES ${READOSM_LIBRARY})
