# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/detail
    REF boost-1.80.0.beta1
    SHA512 1a0be4502873146d6f2c3dca9ad7c05026ef02abe7a6e0a33d02edef5b406c342923b4cafbb90b03ffa7a36212fcd134f115a7957b2be912258d687f40064c25
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
