if("@WITH_STATIC_LIBRARIES@")
    include(CMakeFindDependencyMacro)
    find_dependency(OpenSSL)
    if(WIN32 AND NOT MINGW)
        find_dependency(Pthreads4W)
    else()
        find_dependency(Threads)
    endif()
endif()
include("${CMAKE_CURRENT_LIST_DIR}/unofficial-mosquitto-targets.cmake")
