# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/spirit
    REF boost-${VERSION}
    SHA512 19ef06bca34dc6f59db26674848c78531b2971cf651efab8768dfac0e4f6b1417749536fc13f9371465a944cff9feeaaa3f1254a35b3d663c79e0163e2d34d41
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
