_find_package(${ARGS})
if(NOT TARGET RocksDB::rocksdb AND TARGET RocksDB::rocksdb-shared)
    add_library(RocksDB::rocksdb INTERFACE IMPORTED)
    set_target_properties(RocksDB::rocksdb PROPERTIES INTERFACE_LINK_LIBRARIES "RocksDB::rocksdb-shared")
endif()
if(TARGET RocksDB::rocksdb AND NOT TARGET RocksDB::rocksdb-shared)
    add_library(RocksDB::rocksdb-shared INTERFACE IMPORTED)
    set_target_properties(RocksDB::rocksdb-shared PROPERTIES INTERFACE_LINK_LIBRARIES "RocksDB::rocksdb")
endif()
