# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mysql
    REF boost-${VERSION}
    SHA512 d2e77a06232caebc5320f46fe7308e2588b1a1684525388fe053912703eff4f85a6d5a5d49c73f5e033df75459a45a3c17919339d16dc91e4b5c97bca3132b86
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
