# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mysql
    REF boost-${VERSION}
    SHA512 3e6b7045a0e4637abd79138d2e4a89c3d62a3a4df382aac13baf729cfe68274401390e7da480b8a48a190bcb24f2fd56ec9561217f5fedbfc9f546d3b8ab9d2d
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
