# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/url
    REF boost-${VERSION}
    SHA512 79ffcbae46bcc99e65d144f861dd135d97839a4ff2094c2d4d00dbbd5d17661d6243e4de2ba26db190a3f307e45c005df2f8f1355347de65b804c0b157c2528c
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
