# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/url
    REF boost-${VERSION}
    SHA512 17b433f3e4f8362a7fef4e1f0c8ae279c98bff1aebf513011823a746da287229af1605b7e248a9b317bb539e3295c4e18600d89595c5972868de50e314f38cd1
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
