# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lambda
    REF boost-${VERSION}
    SHA512 0cfd5465b8f18a67155936273bc5488c19543b12e54f6e7975bb7d769a9909f2359b9cdf24d5aa459ef9ff64f367ca26799f175ce16dbf7544c5871cdea1b1f9
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
