# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/logic
    REF boost-${VERSION}
    SHA512 e15a258e91e1179aaeccb4d5ce023380ca051038752b47e1fd94d9905cb3893610dd56ad9707cde9a1c7ff1627b54f8c3f7dc8a124f8f6f4c94080571ad6c078
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
