# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/logic
    REF boost-1.70.0
    SHA512 6cf4e2fa0c63de2c226a2f57ed57d07ab73cc359ebf23711b636badb9a6924992ea9edc0f9bfeefd15531ca2d06bdb3667b49bcc2f9deec64af6eafd52e944d5
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
