vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO microsoft/cpp_client_telemetry
    REF v3.10.281.1
    SHA512 934ac980096f571aa4eaeba5159ee87a687e32e174c548190c3926c5c29c1054f7b7924647457c8bcc97a78dd216651577dbb958a7895175d49a97784fb3bf51
    HEAD_REF main
)

vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
        device-id MATSDK_ENABLE_DEVICE_ID
        android-capi-http-client MATSDK_ENABLE_CAPI_HTTP_CLIENT
)

set(MATSDK_BUILD_APPLE_HTTP OFF)
if(VCPKG_TARGET_IS_OSX OR VCPKG_TARGET_IS_IOS)
    set(MATSDK_BUILD_APPLE_HTTP ON)
endif()
set(MATSDK_ANDROID_HTTP_CLIENT AUTO)
if(VCPKG_TARGET_IS_ANDROID)
    set(MATSDK_ANDROID_HTTP_CLIENT JAVA)
endif()
set(MATSDK_BUILD_SHARED_LIBS OFF)
if(VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
    set(MATSDK_BUILD_SHARED_LIBS ON)
endif()
set(MATSDK_PLATFORM_OPTIONS)
if(VCPKG_TARGET_IS_IOS)
    list(APPEND MATSDK_PLATFORM_OPTIONS -DCMAKE_OSX_DEPLOYMENT_TARGET=13.0)
endif()

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        ${FEATURE_OPTIONS}
        ${MATSDK_PLATFORM_OPTIONS}
        -DBUILD_SHARED_LIBS=${MATSDK_BUILD_SHARED_LIBS}
        -DBUILD_VERSION=${VERSION}
        -DMATSDK_BUILD_HEADERS=ON
        -DMATSDK_BUILD_LIBRARY=ON
        -DMATSDK_BUILD_TEST_TOOL=OFF
        -DMATSDK_BUILD_UNIT_TESTS=OFF
        -DMATSDK_BUILD_FUNC_TESTS=OFF
        -DMATSDK_BUILD_PACKAGE=OFF
        -DMATSDK_BUILD_JNI_WRAPPER=OFF
        -DMATSDK_BUILD_OBJC_WRAPPER=OFF
        -DMATSDK_BUILD_SWIFT_WRAPPER=OFF
        -DMATSDK_BUILD_APPLE_HTTP=${MATSDK_BUILD_APPLE_HTTP}
        -DMATSDK_USE_WININET=OFF
        -DMATSDK_ANDROID_HTTP_CLIENT=${MATSDK_ANDROID_HTTP_CLIENT}
        -DMATSDK_SQLITE_PROVIDER=SYSTEM
        -DMATSDK_ZLIB_PROVIDER=SYSTEM
        -DMATSDK_CURL_PROVIDER=SYSTEM
)

vcpkg_cmake_install()
vcpkg_cmake_config_fixup(PACKAGE_NAME MSTelemetry CONFIG_PATH lib/cmake/MSTelemetry)
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
