FIND_PATH(LIBUSB_INCLUDE_DIR
    NAMES
        lusb0_usb.h
    PATH_SUFFIXES
        "include"
)

FIND_LIBRARY(LIBUSB_LIBRARY
    NAMES
        libusb0
    PATH_SUFFIXES
        "lib"
)

set(LIBUSB_LIBRARIES ${LIBUSB_LIBRARY})
set(LIBUSB_INCLUDE_DIRS ${LIBUSB_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    LIBUSB DEFAULT_MSG
    LIBUSB_LIBRARIES LIBUSB_LIBRARY LIBUSB_INCLUDE_DIRS LIBUSB_INCLUDE_DIR
)
