# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/integer
    REF boost-${VERSION}
    SHA512 36f8d41dee86a1f24208dfcb58f83c51104cd7651e47ad78f428027c4d869b8b557c9adf89b34bbeb7514e1d383917f6107b05d19277b6142202cd1f72b0952e
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
