# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/parser
    REF boost-${VERSION}
    SHA512 1c46cb2b8e88971e4825a89c77a42bbcaf2084fcf40c303aee9973b40c5633e4914ee682cff2c34baed368c4c687ba1ef6d9d79feb5e5846073a8bc4ae5b7285
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
