# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/parser
    REF boost-${VERSION}
    SHA512 24644b716e17f98f4f54b5bf07784a20e586fc6af74573f712424ac0225ffdeb89efef8ece3ad0b8527e84acc7d16cd4c751dc960a0fa6e8010fec3a601a1ef7
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
