# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/parser
    REF boost-${VERSION}
    SHA512 5f42f4f67ac1fab9f606a5daacf37247aa7991e764c0f617e51f4a5b79539ffff5dad09a720eed7633f4edb59c50b7c5f386b718c6ab2e34df51bc81de259e71
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
