# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/decimal
    REF boost-${VERSION}
    SHA512 4af06bfe1c6fe73b8dea0cd80eec804084e3c04ae2e6b4eaf49e2a6944a9ba98b20bc814f982c908b020dd264f0d060f95cd0051d30b0b03d5ed0d18295c6166
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
