# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/decimal
    REF boost-${VERSION}
    SHA512 e6617127ec8d8b352619735f2f2e355178a6299a6552558aa12be437523784205bd2ca346c06bca10de2a559cf3131acfcb8c844c78f416442dbaf7e836d83d5
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
