# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/poly_collection
    REF boost-${VERSION}
    SHA512 9285f3d92838568234447adacebea60de55f3ec74cac0bd210926708901cc9c853c9da31232eabf5ca75ab70b0e506cf3ea770e663268f6333f2c4f3baf55300
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
