# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/winapi
    REF boost-1.74.0
    SHA512 650b860d622f2e0949f97801367ba1d321bacbda306dc18b4f30d0ff7dff1f33a270479116d72a52d094962b9ee7fea2d5715cb594d63603939ba566a3901b5e
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
