# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lockfree
    REF boost-${VERSION}
    SHA512 734df3871117f5b7ba854ece95be46528d1489764fc7d24b67a37b40b06702a8dea41957a92318d0929346389ff6f99a38a9dbeb056c0d8f759a4deb54179fb5
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
