# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/gil
    REF boost-1.78.0
    SHA512 6f8b94bb75cf5a1e8781454490d6873bf8c91e85ba7c98f81ece382000051c42512dc76939c693b9b24e97a3496f5fd97581a5665508bdb2ba11e570bc77bdfe
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
