# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/json
    REF boost-${VERSION}
    SHA512 32518027522a27645aa84536efc34eec7ccaa9dba0b0b95e745f83c423055080891529fbc8e8735b5ee8d486f2b6a7be87fbf34db45fd2ec86d20a9ad77e57d1
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
