# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/nowide
    REF boost-1.82.0
    SHA512 f27382299303244be0bb922767cb673e4c46d9a3468c912af7827c4bd5420b79d36d83a7da42affdbbb2d36d2ee051d0e4ffa257d5762c2c429fd076fc09b44c
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
