# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/optional
    REF boost-1.76.0
    SHA512 4802a27da00446384ae4c91075593f0d67628192d9f9cbc2378a190d1ef5491979c40934b3ac0e72145522847d0abbd1afd44345696cd936875189ab0013138c
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
