# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/bind
    REF boost-${VERSION}
    SHA512 4f45018ed44d6df23e8d1bad3dd4d43ca59ec1da1252743330be5a146f5b51ef77d30e811f130d2726f1881af357d9859b727a805e5db91b70f7a3440b87957a
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
