# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/bind
    REF boost-${VERSION}
    SHA512 ed511869c831674e805db7104177a6e121a5c722b9d279c695bc9b46187dc0a734d198c29cb431794c93052a8adc1a6bd7f76a48a4fff6391264ea5e413fcc1f
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
