include(FindPackageHandleStandardArgs)
include(SelectLibraryConfigurations)

find_path(OPENVDB_INCLUDE_DIR openvdb.h PATH_SUFFIXES openvdb)
get_filename_component(OPENVDB_INCLUDE_DIR ${OPENVDB_INCLUDE_DIR} DIRECTORY)

find_library(OPENVDB_LIBRARY_DEBUG NAMES openvdb libopenvdb NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug" NO_DEFAULT_PATH REQUIRED)
find_library(OPENVDB_LIBRARY_RELEASE NAMES openvdb libopenvdb NAMES_PER_DIR PATH_SUFFIXES lib PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" NO_DEFAULT_PATH REQUIRED)

select_library_configurations(OPENVDB)

set(OPENVDB_INCLUDE_DIRS ${OPENVDB_INCLUDE_DIR})
set(OPENVDB_LIBRARIES ${OPENVDB_LIBRARY})
