vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO redboltz/mqtt_cpp
    REF v10.0.0
    SHA512 fc082f2d7416723db9b01bef8878b422f6717148bec28e2b4a3b8993cfa5ff4531f187ff7de556c5087d43010cf7e76e9fd3c8423e22dc7bf7f05d0f644e2923
    HEAD_REF master
)

if ("log" IN_LIST FEATURES)
	set(CMAKE_ENABLE_PACKAGE_LOG ON)
else()
	set(CMAKE_ENABLE_PACKAGE_LOG OFF)
endif()

if ("tls" IN_LIST FEATURES)
	set(CMAKE_ENABLE_PACKAGE_TLS ON)
else()
	set(CMAKE_ENABLE_PACKAGE_TLS OFF)
endif()

if ("ws" IN_LIST FEATURES)
	set(CMAKE_ENABLE_PACKAGE_WS ON)
else()
	set(CMAKE_ENABLE_PACKAGE_WS OFF)
endif()

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
	-DMQTT_USE_LOG=${CMAKE_ENABLE_PACKAGE_LOG}
	-DMQTT_USE_TLS=${CMAKE_ENABLE_PACKAGE_TLS}
	-DMQTT_USE_WS=${CMAKE_ENABLE_PACKAGE_WS}
	-DMQTT_USE_STR_CHECK=ON
        -DMQTT_BUILD_EXAMPLES=OFF
        -DMQTT_BUILD_TESTS=OFF
        -DCMAKE_DISABLE_FIND_PACKAGE_Doxygen=ON
)

vcpkg_install_cmake()

vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/mqtt_cpp_iface)

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/lib)
file(INSTALL ${SOURCE_PATH}/LICENSE_1_0.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
