# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/rational
    REF boost-1.79.0
    SHA512 9192f72442d5b7037a0386cce26d412e6f576eb6352f259bd626ebeace472037a2363be235e1f1675f4fa5ab41212eca58045a584e81c36782b77d6965032106
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
