# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/wave
    REF boost-${VERSION}
    SHA512 8bb19ac89004f06ffb9ac7dc67759bc7a149042000023660cb4b18a0a75157d7e38a8fad1dad2a7ceba2f9b624dcb8b5a032543976d85ef9736220c9e9d0eb9d
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
