# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/wave
    REF boost-${VERSION}
    SHA512 1584862e014cebccdc4721f64ff5b9981da77decc03be3d7caecfcdc8b6ea8bbc5a53ec38cf24e32c4098de8ed2b9de8f2fd2385fe37771c2083a071e9a65eda
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
