set(OPENIMAGEIO_PREV_MODULE_PATH ${CMAKE_MODULE_PATH})
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/../OpenImageIO")

_find_package(${ARGS})

set(CMAKE_MODULE_PATH ${OPENIMAGEIO_PREV_MODULE_PATH})
