# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/polygon
    REF boost-1.80.0
    SHA512 2b6751c422e9cbc5369389017dcf38f2c113ea321f2b534a40fed23ea12b5e8897e67780656525f72661e3514eb13918928f6697dac49e338433f53d5816d4f7
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
