# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/hash2
    REF boost-${VERSION}
    SHA512 98af7bf7c265c0f03afaa970826cac92c49bc8a3e343a44e88df0f4dc76700fd7db0b15aafa15c4862752379a3891bf9a970ede98c6f41a2558365a1eb5cbcf8
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
