# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/hash2
    REF boost-${VERSION}
    SHA512 e4aee2d58e201fc1e0bacaa1d5005d6fa095a016ceaf7056510bb091ae77adf495ece0678ecd64ba0187e3677f29ca3edb6322a65434e696940b652b09ccc3f3
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
