# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/hash2
    REF boost-${VERSION}
    SHA512 1555de1c8c0e206f7ebb1aca5994feb381dcaf64bed42e2b4a44df5d814cea9e462d4e38cbe8d6da7f3c56b557c17d946977c647ab882b7fef3c9c8a01da17ef
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
