include(${CURRENT_INSTALLED_DIR}/share/qt5/qt_port_functions.cmake)
if (NOT VCPKG_CMAKE_SYSTEM_NAME STREQUAL "Darwin" AND NOT QT_UPDATE_VERSION)
    message(FATAL_ERROR "qt5-macextras only support OSX.")
endif()
qt_submodule_installation()