# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/static_string
    REF boost-${VERSION}
    SHA512 5d4510534831d7902d1d41160b4031c6e03d431e856718631542934a890ee4c4298048b1826b187747b79847060e2a10abf62a05bbab8d708f0a02836efc0403
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
