vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO ClarkWain/WhatsCanvas
    REF "v${VERSION}"
    SHA512 fb186c954cac650c325100e7e788911472f4178f0d0c1e27ea034b877e577f19797808d01ae3b6a02d2e1cb9053727431d164056ac8691c48c9a7057af317b6b
    HEAD_REF master
)

vcpkg_check_features(
    OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
        opengl WHATSCANVAS_BUILD_OPENGL
        software WHATSCANVAS_BUILD_SOFTWARE
)

# vcpkg requires the core feature set to be independently buildable. Use the
# dependency-free software renderer when no renderer feature was requested.
if(NOT "opengl" IN_LIST FEATURES AND NOT "software" IN_LIST FEATURES)
    list(APPEND FEATURE_OPTIONS -DWHATSCANVAS_BUILD_SOFTWARE=ON)
endif()

if("text" IN_LIST FEATURES)
    set(WHATSCANVAS_TEXT_RASTERIZER ON)
    set(WHATSCANVAS_TEXT_SHAPING ON)
else()
    set(WHATSCANVAS_TEXT_RASTERIZER OFF)
    set(WHATSCANVAS_TEXT_SHAPING OFF)
endif()

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        ${FEATURE_OPTIONS}
        -DWHATSCANVAS_BUILD_OPENGLES=OFF
        -DWHATSCANVAS_ENABLE_VULKAN=OFF
        -DWHATSCANVAS_ENABLE_FREETYPE_RASTERIZER=${WHATSCANVAS_TEXT_RASTERIZER}
        -DWHATSCANVAS_ENABLE_OPENTYPE_SHAPING=${WHATSCANVAS_TEXT_SHAPING}
        -DWHATSCANVAS_USE_SYSTEM_DEPENDENCIES=ON
        -DWHATSCANVAS_INSTALL_TEXT_DEPENDENCIES=OFF
        -DWHATSCANVAS_BUILD_DEMO=OFF
        -DWHATSCANVAS_BUILD_BENCHMARKS=OFF
        -DWHATSCANVAS_ENABLE_SCRIPT_TESTS=OFF
        -DWHATSCANVAS_INSTALL=ON
        -DBUILD_TESTING=OFF
)

vcpkg_cmake_install()
vcpkg_cmake_config_fixup(
    PACKAGE_NAME WhatsCanvas
    CONFIG_PATH lib/cmake/WhatsCanvas
)
vcpkg_copy_pdbs()

file(REMOVE_RECURSE
    "${CURRENT_PACKAGES_DIR}/debug/include"
    "${CURRENT_PACKAGES_DIR}/debug/share"
)

file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage"
    DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}"
)
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
