vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO ClarkWain/WhatsCanvas
    REF "v${VERSION}"
    SHA512 7453912f51e5c0163068857b80433f6ae07742b270e23d3586480139f8de2f896c46c24d199bc30f1747ebe334f3adba18f123f53a3927d14da937f7c99d95b8
    HEAD_REF master
)

vcpkg_check_features(
    OUT_FEATURE_OPTIONS FEATURE_OPTIONS
    FEATURES
        opengl WHATSCANVAS_BUILD_OPENGL
)

if("text" IN_LIST FEATURES)
    set(WHATSCANVAS_TEXT_RASTERIZER ON)
    set(WHATSCANVAS_TEXT_SHAPING ON)
else()
    set(WHATSCANVAS_TEXT_RASTERIZER OFF)
    set(WHATSCANVAS_TEXT_SHAPING OFF)
endif()

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        ${FEATURE_OPTIONS}
        -DWHATSCANVAS_BUILD_SOFTWARE=ON
        -DWHATSCANVAS_BUILD_OPENGLES=OFF
        -DWHATSCANVAS_ENABLE_VULKAN=OFF
        -DWHATSCANVAS_X11=OFF
        -DWHATSCANVAS_ENABLE_FREETYPE_RASTERIZER=${WHATSCANVAS_TEXT_RASTERIZER}
        -DWHATSCANVAS_ENABLE_OPENTYPE_SHAPING=${WHATSCANVAS_TEXT_SHAPING}
        -DWHATSCANVAS_USE_SYSTEM_DEPENDENCIES=ON
        -DWHATSCANVAS_INSTALL_TEXT_DEPENDENCIES=OFF
        -DWHATSCANVAS_BUILD_DEMO=OFF
        -DWHATSCANVAS_BUILD_BENCHMARKS=OFF
        -DWHATSCANVAS_ENABLE_SCRIPT_TESTS=OFF
        -DWHATSCANVAS_INSTALL=ON
        -DBUILD_TESTING=OFF
)

vcpkg_cmake_install()
vcpkg_cmake_config_fixup(
    PACKAGE_NAME WhatsCanvas
    CONFIG_PATH lib/cmake/WhatsCanvas
)
vcpkg_copy_pdbs()

file(REMOVE_RECURSE
    "${CURRENT_PACKAGES_DIR}/debug/include"
    "${CURRENT_PACKAGES_DIR}/debug/share"
)

file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage"
    DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}"
)
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
