vcpkg_fail_port_install(MESSAGE "bgfx currently only supports Linux, Windows, and Mac platforms" ON_TARGET "WindowsStore" "Android" "FreeBSD")

vcpkg_from_github(
  OUT_SOURCE_PATH BGFX_SOURCE_DIR
  REPO bkaradzic/bgfx
  REF a4930fa1a0c6407ccf997d7e58811cb811ad5b04
  SHA512 c8f370cc7f454606368eccca9d8152096e59c891dac1c5cab0ac0ffd2d99d51f49c621e5347c86dd4bc2fac47a13709ab1c24b0a14ebf9fb76387253475de289
)

vcpkg_from_github(
  OUT_SOURCE_PATH BIMG_SOURCE_DIR
  REPO bkaradzic/bimg
  REF ed5fec9e82f975b2b37641e238f6f78d51c5b82c
  SHA512 1e1be1ffe5bf9d651eb57e72443e6b07bdd53c60cce494d397a29781c9d3b9461d88a95fea8bc064c767a1983b8ba09919ea6f151765a4b10568bba5655623d5
)

vcpkg_from_github(
  OUT_SOURCE_PATH BX_SOURCE_DIR
  REPO bkaradzic/bx
  REF 4a7aa1eb412f389524e0499327a17bef4c8dbdd3
  SHA512 a6e028d4ca7162e30dc37efa50d5f093c53923c63ace4780d2ab97471b2faa7d67bc7bb4a0df89b43ce76bbf3706901b8cd5f76556f68374c9a9cd4b1f08b246
)

set(ENV{BX_DIR} ${BX_SOURCE_DIR})
set(ENV{BIMG_DIR} ${BIMG_SOURCE_DIR})

if(VCPKG_TARGET_ARCHITECTURE STREQUAL "x64")
  set(MAKE_TARGET_ARCH 64)
  set(MSBUILD_PLATFORM "x64")
elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL "x86")
  set(MAKE_TARGET_ARCH 32)
  set(MSBUILD_PLATFORM "Win32")
endif()

if(VCPKG_TARGET_IS_WINDOWS)
  set(MAKE_TARGET_PLATFORM vs2017)
  set(EXECUTABLE_SUFFIX ".exe")
elseif(VCPKG_TARGET_IS_LINUX)
  set(MAKE_TARGET_PLATFORM linux)
  set(EXECUTABLE_SUFFIX "")
elseif(VCPKG_TARGET_IS_OSX)
  set(MAKE_TARGET_PLATFORM osx)
  set(EXECUTABLE_SUFFIX "")
endif()

set(MAKE_TARGET_REL ${MAKE_TARGET_PLATFORM}-release${MAKE_TARGET_ARCH})
set(MAKE_TARGET_DBG ${MAKE_TARGET_PLATFORM}-debug${MAKE_TARGET_ARCH})

vcpkg_configure_make(SOURCE_PATH ${BGFX_SOURCE_DIR} SKIP_CONFIGURE)

if(VCPKG_TARGET_IS_WINDOWS)
  vcpkg_build_make(WORKING_DIRECTORY ${BGFX_SOURCE_DIR})
  vcpkg_build_msbuild(PROJECT_PATH ${BGFX_SOURCE_DIR}/.build/projects/vs2017/bgfx.sln PLATFORM ${MSBUILD_PLATFORM})
else()
  vcpkg_build_make(WORKING_DIRECTORY ${BGFX_SOURCE_DIR} RELEASE_TARGET ${MAKE_TARGET_REL} DEBUG_TARGET ${MAKE_TARGET_DBG})
endif()

file(GLOB_RECURSE DEBUG_LIBRARIES   "${CURRENT_BUILDTREES_DIR}" *Debug${VCPKG_TARGET_STATIC_LIBRARY_SUFFIX})
file(GLOB_RECURSE RELEASE_LIBRARIES "${CURRENT_BUILDTREES_DIR}" *Release${VCPKG_TARGET_STATIC_LIBRARY_SUFFIX})
file(GLOB_RECURSE SHADERC_RELEASE   "${CURRENT_BUILDTREES_DIR}" shadercRelease${EXECUTABLE_SUFFIX})
file(GLOB_RECURSE TEXTUREC_RELEASE  "${CURRENT_BUILDTREES_DIR}" texturecRelease${EXECUTABLE_SUFFIX})
file(GLOB_RECURSE GEOMETRYC_RELEASE "${CURRENT_BUILDTREES_DIR}" geometrycRelease${EXECUTABLE_SUFFIX})
file(GLOB_RECURSE SHADERC_DEBUG     "${CURRENT_BUILDTREES_DIR}" shadercDebug${EXECUTABLE_SUFFIX})
file(GLOB_RECURSE TEXTUREC_DEBUG    "${CURRENT_BUILDTREES_DIR}" texturecDebug${EXECUTABLE_SUFFIX})
file(GLOB_RECURSE GEOMETRYC_DEBUG   "${CURRENT_BUILDTREES_DIR}" geometrycDebug${EXECUTABLE_SUFFIX})

file(COPY ${BGFX_SOURCE_DIR}/LICENSE       DESTINATION "${CURRENT_PACKAGES_DIR}/share/bgfx/copyright")
file(COPY ${BGFX_SOURCE_DIR}/include/bgfx  DESTINATION "${CURRENT_PACKAGES_DIR}/include")
file(COPY ${BIMG_SOURCE_DIR}/include/bimg  DESTINATION "${CURRENT_PACKAGES_DIR}/include")
file(COPY ${BX_SOURCE_DIR}/include/bx      DESTINATION "${CURRENT_PACKAGES_DIR}/include")
file(COPY ${BX_SOURCE_DIR}/include/compat  DESTINATION "${CURRENT_PACKAGES_DIR}/include")
file(COPY ${BX_SOURCE_DIR}/include/tinystl DESTINATION "${CURRENT_PACKAGES_DIR}/include")
file(COPY ${DEBUG_LIBRARIES}               DESTINATION "${CURRENT_PACKAGES_DIR}/debug/lib")
file(COPY ${RELEASE_LIBRARIES}             DESTINATION "${CURRENT_PACKAGES_DIR}/lib")
file(COPY ${SHADERC_RELEASE}               DESTINATION "${CURRENT_PACKAGES_DIR}/tools")
file(COPY ${TEXTUREC_RELEASE}              DESTINATION "${CURRENT_PACKAGES_DIR}/tools")
file(COPY ${GEOMETRYC_RELEASE}             DESTINATION "${CURRENT_PACKAGES_DIR}/tools")
file(COPY ${SHADERC_DEBUG}                 DESTINATION "${CURRENT_PACKAGES_DIR}/debug/tools")
file(COPY ${TEXTUREC_DEBUG}                DESTINATION "${CURRENT_PACKAGES_DIR}/debug/tools")
file(COPY ${GEOMETRYC_DEBUG}               DESTINATION "${CURRENT_PACKAGES_DIR}/debug/tools")
