# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/assert
    REF boost-${VERSION}
    SHA512 ef6f7f8d4f7826df15134f4ffbd117f534b5d4ebf278de9f2ea3a5f81fe64727f98892bc4d6094700cca694970093f8f1c7991da0c47d1a415bbc0294d56b847
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
