# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/foreach
    REF boost-${VERSION}
    SHA512 24420e72b7a0e5f09887099626a8da616e2582f87fa5cba28514929aff670e56da5e783bdd1459ecc4b38cf352aaef68907dc53db149fa9ebca5e59048e0bf94
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
