_find_package(${ARGS})

if("@VCPKG_LIBRARY_LINKAGE@" STREQUAL "static")
    if(NOT TARGET GeographicLib::GeographicLib AND TARGET GeographicLib::GeographicLib_STATIC)
        add_library(GeographicLib::GeographicLib INTERFACE IMPORTED)
        set_target_properties(GeographicLib::GeographicLib PROPERTIES INTERFACE_LINK_LIBRARIES GeographicLib::GeographicLib_STATIC)
    elseif(NOT TARGET GeographicLib::GeographicLib_STATIC AND TARGET GeographicLib::GeographicLib)
        add_library(GeographicLib::GeographicLib INTERFACE IMPORTED)
        set_target_properties(GeographicLib::GeographicLib_STATIC PROPERTIES INTERFACE_LINK_LIBRARIES GeographicLib::GeographicLib)
    endif()
endif()

if("@VCPKG_LIBRARY_LINKAGE@" STREQUAL "dynamic")
    if(NOT TARGET GeographicLib::GeographicLib AND TARGET GeographicLib::GeographicLib_SHARED)
        add_library(GeographicLib::GeographicLib INTERFACE IMPORTED)
        set_target_properties(GeographicLib::GeographicLib PROPERTIES INTERFACE_LINK_LIBRARIES GeographicLib::GeographicLib_SHARED)
    elseif(NOT TARGET GeographicLib::GeographicLib_SHARED AND TARGET GeographicLib::GeographicLib)
        add_library(GeographicLib::GeographicLib INTERFACE IMPORTED)
        set_target_properties(GeographicLib::GeographicLib_SHARED PROPERTIES INTERFACE_LINK_LIBRARIES GeographicLib::GeographicLib)
    endif()
endif()