set(ENV_WHITELIST
  "PATH"
#    "USERPROFILE"
  "ALLUSERSPROFILE"
  "CommandPromptType"
  "CommonProgramFiles"
  "CommonProgramFiles(x86)"
  "CommonProgramW6432"
#    "COMPUTERNAME"
  "ComSpec"
#    "HOMEDRIVE"
#    "HOMEPATH"
  "ALLUSERSPROFILE"
  "LOCALAPPDATA" # Needs for CI to be allowed.
  "APPDATA"
#    "LOGONSERVER"
  "OS"
  "PATHEXT"
  "PROCESSOR_ARCHITECTURE"
  "PROCESSOR_IDENTIFIER"
  "PROCESSOR_LEVEL"
  "PROCESSOR_REVISION"
  "ProgramData"
  "ProgramFiles"
  "ProgramFiles(x86)"
  "ProgramW6432"
  "PROMPT"
  "PSModulePath"
  "PUBLIC"
  "SystemDrive"
  "SystemRoot"
  "TEMP"
  "TMP"
#    "USERDOMAIN"
#    "USERDOMAIN_ROAMINGPROFILE"
#    "USERNAME"
    "USERPROFILE"
  "windir"
  "GIT_ASKPASS"
  "GIT_CEILING_DIRECTORIES"
  "VSCMD_SKIP_SENDTELEMETRY"
  "VCPKG_COMMAND"
  "VCPKG_TOOLCHAIN_ENV_ALREADY_SET"
  "X_VCPKG_RECURSIVE_DATA"
  "HTTP_PROXY"
  "HTTPS_PROXY"
)