if(NOT TARGET unofficial::iconv::libcharset)
    add_library(unofficial::iconv::libcharset INTERFACE IMPORTED)
endif()
if(NOT TARGET unofficial::iconv::libiconv)
    add_library(unofficial::iconv::libiconv INTERFACE IMPORTED)
endif()
if(APPLE)
    set_property(TARGET unofficial::iconv::libcharset PROPERTY INTERFACE_LINK_LIBRARIES "charset;unofficial::iconv::libiconv")
    set_property(TARGET unofficial::iconv::libiconv PROPERTY INTERFACE_LINK_LIBRARIES "iconv")
endif()