if(APPLE)
    if(NOT TARGET unofficial::iconv::libcharset)
        add_library(unofficial::iconv::libcharset INTERFACE IMPORTED GLOBAL)
    endif()
    if(NOT TARGET unofficial::iconv::libiconv)
        add_library(unofficial::iconv::libiconv INTERFACE IMPORTED GLOBAL)
    endif()
    set_property(TARGET unofficial::iconv::libcharset PROPERTY INTERFACE_LINK_LIBRARIES "charset;unofficial::iconv::libiconv")
    set_property(TARGET unofficial::iconv::libiconv PROPERTY INTERFACE_LINK_LIBRARIES "iconv")
else()
    include("${CMAKE_CURRENT_LIST_DIR}/unofficial-iconv-targets.cmake")
endif()

set_target_properties(unofficial::iconv::libcharset PROPERTIES IMPORTED_GLOBAL TRUE)
set_target_properties(unofficial::iconv::libiconv PROPERTIES IMPORTED_GLOBAL TRUE)
