# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/headers
    REF boost-1.82.0
    SHA512 a7fdeeb2fdbac1476ac72c09e3e065af2d564535113b10e52d4f0dc34239be34e7a4c00b6802e160248fc387d7a3ba067c6c39e0b0919f676f60ddcc28146693
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug")