include("${CMAKE_CURRENT_LIST_DIR}/../vcpkg-cmake-get-vars/vcpkg-port-config.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/vcpkg_make_configure.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/vcpkg_make_install.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/vcpkg_make_common.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/vcpkg_make.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/vcpkg_scripts.cmake")
