# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/statechart
    REF boost-1.76.0
    SHA512 3b9476d1b59ecaf867c19f106c4e6ff9e66c5b26f9793256a52b8dc47c26ca63dfd67dfef374b20596287764589d7b274bf88e079fc191ff186321946ae3050d
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
