# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/ublas
    REF boost-${VERSION}
    SHA512 c1deabca2f5474aa6d8223565b14f77b0a481a17c8c2a5069af03cbef72653318f0e885a681aa11aadf9cb16648bdfc536a14f744ff76d7ad5f9fd2110cbc7ec
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
