find_package(CURL CONFIG QUIET)

if(CURL_FOUND)
    set(LIBCURL_INCLUDE_DIRS ${CURL_INCLUDE_DIRS})
    set(LIBCURL_LIBRARIES CURL::libcurl)
    set(LIBCURL_FOUND TRUE)
    message(STATUS "Found libcurl: ${LIBCURL_LIBRARIES}")
else()
    set(LIBCURL_FOUND FALSE)
    message(STATUS "Could not find libcurl")
endif()
