#
#  Windows Makefile for FastCGI development kit
#
#  $Id: Makefile.nt,v 1.4 2001/11/27 14:02:54 robs Exp $
#

!IF "$(CFG)" == ""
CFG=release
!ENDIF

all: "include\fcgi_config.h"
	cd ".\libfcgi"
	$(MAKE) $(MAKEFLAGS) /NOLOGO /F libfcgi.mak     CFG=$(CFG) $@

	cd ".\.."

"include\fcgi_config.h": "include\fcgi_config_x86.h"
	copy "include\fcgi_config_x86.h" "include\fcgi_config.h"

clean:
	cd ".\libfcgi"
	$(MAKE) $(MAKEFLAGS) /NOLOGO /F libfcgi.mak     CFG=$(CFG) $@

	cd ".\.."
	
install:
	@echo "Sorry, the install target hasn't been written yet"
