vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO chenjunfu2/NBT_CPP
    REF "v${VERSION}"
    HEAD_REF master
    SHA512 a9c8184f336c7e418da64cc2bf767b0234cf417c64394d9532208b94f906b5922890647fc003d6e6ec5644b617dfab1793351b8a20ee556180ef2a768250a035
)

# install
file(INSTALL "${SOURCE_PATH}/include/nbt_cpp/"
     DESTINATION "${CURRENT_PACKAGES_DIR}/include/nbt_cpp"
     FILES_MATCHING
     PATTERN "*.hpp"
     PATTERN "*.h"
     PATTERN "vcpkg_config.h" EXCLUDE
)

# vcpkg_config
set(CONFIG_HEADER_CONTENT "#pragma once\n\n")
set(CONFIG_HEADER_CONTENT "${CONFIG_HEADER_CONTENT}//Auto-generated by vcpkg - DO NOT EDIT\n\n")

if("zlib" IN_LIST FEATURES)
    set(CONFIG_HEADER_CONTENT "${CONFIG_HEADER_CONTENT}//use zlib\n")
    set(CONFIG_HEADER_CONTENT "${CONFIG_HEADER_CONTENT}#define CJF2_NBT_CPP_USE_ZLIB\n\n")
endif()

if("xxhash" IN_LIST FEATURES)
    set(CONFIG_HEADER_CONTENT "${CONFIG_HEADER_CONTENT}//use xxhash\n")
    set(CONFIG_HEADER_CONTENT "${CONFIG_HEADER_CONTENT}#define CJF2_NBT_CPP_USE_XXHASH\n\n")
endif()

file(WRITE "${CURRENT_PACKAGES_DIR}/include/nbt_cpp/vcpkg_config.h" "${CONFIG_HEADER_CONTENT}")

# copyright
file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
