vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO chenjunfu2/NBT_CPP
    REF "v${VERSION}"
    HEAD_REF master
    SHA512 df45f004398f9159a730fd0992a86595c58e0e17cd6378b55749e7a5d64748545aa727455fca43047893a42e937c0020d64b072fa9f248ccfefc47110763754f
)

# install
file(INSTALL "${SOURCE_PATH}/include/nbt_cpp/"
     DESTINATION "${CURRENT_PACKAGES_DIR}/include/nbt_cpp"
     FILES_MATCHING
     PATTERN "*.hpp"
     PATTERN "*.h"
     PATTERN "vcpkg_config.h" EXCLUDE
)

# vcpkg_config
set(CONFIG_HEADER_CONTENT "#pragma once\n\n")
set(CONFIG_HEADER_CONTENT "${CONFIG_HEADER_CONTENT}//Auto-generated by vcpkg - DO NOT EDIT\n\n")

if("zlib" IN_LIST FEATURES)
    set(CONFIG_HEADER_CONTENT "${CONFIG_HEADER_CONTENT}//use zlib\n")
    set(CONFIG_HEADER_CONTENT "${CONFIG_HEADER_CONTENT}#define CJF2_NBT_CPP_USE_ZLIB\n\n")
endif()

if("xxhash" IN_LIST FEATURES)
    set(CONFIG_HEADER_CONTENT "${CONFIG_HEADER_CONTENT}//use xxhash\n")
    set(CONFIG_HEADER_CONTENT "${CONFIG_HEADER_CONTENT}#define CJF2_NBT_CPP_USE_XXHASH\n\n")
endif()

file(WRITE "${CURRENT_PACKAGES_DIR}/include/nbt_cpp/vcpkg_config.h" "${CONFIG_HEADER_CONTENT}")

# copyright
file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
