# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/scope
    REF boost-${VERSION}
    SHA512 aff0195480e54b6eb752a8decb992be2ce6a5f170c35ab3d37dd516d5d9dded15d56e1f2bbd135c936df58e7c34a29389c26c63e7f1af4aef87a68e0f648c036
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
