vcpkg_from_github(
  OUT_SOURCE_PATH SOURCE_PATH
  REPO alicevision/AliceVision
  REF v3.2.0
  SHA512 448e20b2bb6623034ab89ea56b0c7fdf09af34d7d0d47740590fa9cd9aa2b6864f3950c4e968d260c660a41a2f5877c10edf8cfd0dcdd18e58ce289b7336e9ec
  HEAD_REF master
  PATCHES fix-dynamic-boost.patch
)

vcpkg_check_features(
  OUT_FEATURE_OPTIONS FEATURE_OPTIONS
  FEATURES
    sfm ALICEVISION_BUILD_SFM
)

# MeshSDFilter
vcpkg_from_github(
  OUT_SOURCE_PATH MESHSDFILTER_SOURCE_PATH
  REPO bldeng/MeshSDFilter
  REF 71c3028eda6fc29517e658c54833e280f9abad51
  SHA512  61367aab7117922b6f0f56d58e95cd328ac8177b184add11530b2ce9a8474be4947c7b27de135d7ad2980d6d49cc8a44b066eb673784dd553e1b9e78e994b3bb
  HEAD_REF master
)

file(REMOVE_RECURSE "${SOURCE_PATH}/src/dependencies/MeshSDFilter")
file(RENAME "${MESHSDFILTER_SOURCE_PATH}" "${SOURCE_PATH}/src/dependencies/MeshSDFilter")

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        ${FEATURE_OPTIONS}
        -DALICEVISION_BUILD_MVS=ON
        -DALICEVISION_BUILD_HDR=ON
        -DALICEVISION_BUILD_SEGMENTATION=ON
        -DALICEVISION_BUILD_STEREOPHOTOMETRY=ON
        -DALICEVISION_BUILD_PANORAMA=ON
        -DALICEVISION_BUILD_SOFTWARE=ON
        -DALICEVISION_BUILD_COVERAGE=OFF
        -DALICEVISION_BUILD_DOC=OFF
        -DALICEVISION_USE_OPENMP=OFF
        -DALICEVISION_USE_CCTAG=OFF
        -DALICEVISION_USE_APRILTAG=OFF
        -DALICEVISION_USE_POPSIFT=OFF
        -DALICEVISION_USE_OPENGV=OFF
        -DALICEVISION_USE_ALEMBIC=OFF
        -DALICEVISION_USE_UNCERTAINTYTE=OFF
        -DALICEVISION_USE_ONNX=OFF
        -DALICEVISION_USE_ONNX_GPU=OFF
        -DALICEVISION_USE_CUDA=OFF
        -DALICEVISION_USE_NVTX_PROFILING=OFF
        -DALICEVISION_NVCC_WARNINGS=OFF
        -DALICEVISION_USE_OPENCV=OFF
        -DALICEVISION_USE_OPENCV_CONTRIB=OFF
        -DALICEVISION_USE_OCVSIFT=OFF
        -DALICEVISION_USE_MESHSDFILTER=ON
        -DALICEVISION_REQUIRE_CERES_WITH_SUITESPARSE=ON
        -DALICEVISION_USE_RPATH=ON
        -DALICEVISION_BUILD_TESTS=OFF
        -DBOOST_NO_CXX11=OFF
)

vcpkg_cmake_install()

vcpkg_cmake_config_fixup(PACKAGE_NAME AliceVision CONFIG_PATH share/aliceVision/cmake)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include"
                    "${CURRENT_PACKAGES_DIR}/include/aliceVision/image/image_test"
                    "${CURRENT_PACKAGES_DIR}/include/aliceVision/image/share"
                    "${CURRENT_PACKAGES_DIR}/include/aliceVision/sfmDataIO/compatibilityData"
                    "${CURRENT_PACKAGES_DIR}/debug/share")

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/COPYING.md")
