set(SEAL_VERSION_MAJOR 3)
set(SEAL_VERSION_MINOR 5)
set(SEAL_VERSION_MICRO 9)

string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "static" SEAL_BUILD_STATIC)
string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "dynamic" SEAL_BUILD_DYNAMIC)

if (SEAL_BUILD_STATIC)
    set(SEAL_BUILD_SHARED_LIB "OFF")
endif ()

if (SEAL_BUILD_DYNAMIC)
    set(SEAL_BUILD_SHARED_LIB "OFF")
endif ()

string(TOUPPER ${PORT} PORT_UPPER)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO microsoft/SEAL
    REF e3ad13edf7e5b4dc8a59fd2cd6235ad9d7428cab
    SHA512 9d52a51bd1d3141e45fd1f92134433a9eb7458e125140501952535c67ea49e0c66ccd4a80f7473c31db1963afcd7e690c716ea32d195cb07ba6fa60847168a91
    HEAD_REF master
    PATCHES vcpkg_fix.patch
)

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    DISABLE_PARALLEL_CONFIGURE
    OPTIONS
        -DALLOW_COMMAND_LINE_BUILD=ON
        -DBUILD_SHARED_LIBS=${SEAL_BUILD_SHARED_LIB} 
        -DSEAL_BUILD_EXAMPLES=OFF 
        -DSEAL_BUILD_TESTS=OFF 
        -DSEAL_BUILD_SEAL_C=OFF
        -DSEAL_USE_MSGSL=ON 
        -DSEAL_USE_ZLIB=ON
)

vcpkg_install_cmake()
vcpkg_copy_pdbs()

vcpkg_fixup_cmake_targets(CONFIG_PATH lib/cmake/${PORT_UPPER}-${SEAL_VERSION_MAJOR}.${SEAL_VERSION_MINOR})

file(REMOVE_RECURSE
    ${CURRENT_PACKAGES_DIR}/debug/include
    ${CURRENT_PACKAGES_DIR}/debug/share)

# Handle copyright
file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
