# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/bimap
    REF boost-${VERSION}
    SHA512 39ace5043a65d0f3fd1275e5dbb1a8efc443b019fd49f7f460bc9aca0f9d04d0e6dc40f2c5b90898cf3c1b5b6c91fa6c94eee960ff1dffd58442a98b1a314db6
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
