# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/bimap
    REF boost-1.79.0
    SHA512 85e6c549433027a43f99e18d422be70055aa59e9548785c9ab1d166e49c21702b1d939070187c58b296ea20635a6ef6fa4d1040c9746eba96790f26200de7201
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
