# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/compute
    REF boost-${VERSION}
    SHA512 5e90e88b07492dae3b76d8dc1b5dcce2a2038122d5e91c48e9491810ec15d7581e3f69e6b58b5d01508c2595b0a1762f1e552fe5d0c90dd14f8453d15e52518d
    HEAD_REF master
    PATCHES
        opt-filesystem.diff
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
