# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/vmd
    REF boost-1.80.0.beta1
    SHA512 d6d39194083ea4bcda293250a227b4c509985e3ad673b8ea5234fbb319c78aad1071e188a63bc5e96e405e39b3c50ff37f6eb2a3906126b25ab6817d0d0eca48
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
