# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/vmd
    REF boost-1.73.0
    SHA512 84c693988230f1f0e77d098157ed3d47b7c196a26515f4d0a7f8884affa206a5f9baee46a8e1c611dc34d1b6b2675cadd5aa25f97c11421404d1ea6e4473ba09
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
