# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/accumulators
    REF boost-${VERSION}
    SHA512 1aa5e9d811aa91843d59b9f7bdee1de78979b94c9a4dc60cd55071c5f4fbe81a08091b7de08c8fbc42b24efe17484635f5cadddf969cec7e2b306109c6a82b69
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
