# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/accumulators
    REF boost-${VERSION}
    SHA512 595806acd2b62e7fa9fd10baa080640b4fc080a1954b0208767a688943a5b5469311941fbb4dba5726a8fc0d400eb8ae206048ad3a60ff246fa345720f201a60
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
