set(FOLLY_PREV_MODULE_PATH ${CMAKE_MODULE_PATH})
list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR})

z_vcpkg_underlying_find_package(${ARGS})

set(CMAKE_MODULE_PATH ${FOLLY_PREV_MODULE_PATH})