function(z_vcpkg_get_visual_studio_generator)
    cmake_parse_arguments(PARSE_ARGV 0 arg "" "OUT_GENERATOR;OUT_ARCH" "")
    
    if (NOT DEFINED arg_OUT_GENERATOR)
        message(FATAL_ERROR "OUT_GENERATOR must be defined.")
    endif()
    if(NOT DEFINED arg_OUT_ARCH)
        message(FATAL_ERROR "OUT_ARCH must be defined.")
    endif()
    if(DEFINED arg_UNPARSED_ARGUMENTS)
            message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION} was passed extra arguments: ${arg_UNPARSED_ARGUMENTS}")
    endif()
    
    if("${VCPKG_PLATFORM_TOOLSET}" STREQUAL "v120" AND NOT "${VCPKG_TARGET_ARCHITECTURE}" STREQUAL "arm64")
        set(generator "Visual Studio 12 2013")
    elseif("${VCPKG_PLATFORM_TOOLSET}" STREQUAL "v140" AND NOT "${VCPKG_TARGET_ARCHITECTURE}" STREQUAL "arm64")
        set(generator "Visual Studio 14 2015")
    elseif("${VCPKG_PLATFORM_TOOLSET}" STREQUAL "v141")
        set(generator "Visual Studio 15 2017")
    elseif("${VCPKG_PLATFORM_TOOLSET}" STREQUAL "v142")
        set(generator "Visual Studio 16 2019")
    elseif("${VCPKG_PLATFORM_TOOLSET}" STREQUAL "v143")
        set(generator "Visual Studio 17 2022")
    endif()

    if(DEFINED VCPKG_VS_CMAKE_GENERATOR)
        set(generator "${VCPKG_VS_CMAKE_GENERATOR}")
    endif()

    if("${VCPKG_TARGET_ARCHITECTURE}" STREQUAL "x86")
        set(generator_arch "Win32")
    elseif("${VCPKG_TARGET_ARCHITECTURE}" STREQUAL "x64")
        set(generator_arch "x64")
    elseif("${VCPKG_TARGET_ARCHITECTURE}" STREQUAL "arm")
        set(generator_arch "ARM")
    elseif("${VCPKG_TARGET_ARCHITECTURE}" STREQUAL "arm64")
        set(generator_arch "ARM64")
    endif()
    set(${arg_OUT_GENERATOR} "${generator}" PARENT_SCOPE)
    set(${arg_OUT_ARCH} "${generator_arch}" PARENT_SCOPE)
endfunction()

