# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/lambda2
    REF boost-${VERSION}
    SHA512 d841e40e299c6b9ffb50ad369432078b967c459fa7ebfcd9d023210efd779a80f18152f4021916d4ae1d64c23566bd456a3a62632dfeb5e86a3693ec6d162457
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
