# ImageMagick CMake config — generated by vcpkg overlay port.
# Provides IMPORTED targets:
#   ImageMagick::MagickCore
#   ImageMagick::MagickWand
#   ImageMagick::Magick++

# Guard against multiple inclusions.
if(TARGET ImageMagick::MagickCore)
    return()
endif()

get_filename_component(_im_prefix "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(_im_incdir "${_im_prefix}/include/ImageMagick-7")

# Helper: create an INTERFACE IMPORTED target wrapping a library.
macro(_im_add_target _target _libname)
    add_library(${_target} INTERFACE IMPORTED)
    set_target_properties(${_target} PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${_im_incdir}"
        INTERFACE_COMPILE_DEFINITIONS "MAGICKCORE_QUANTUM_DEPTH=@_im_qdepth@;MAGICKCORE_HDRI_ENABLE=@_im_hdri_val@"
    )
    # Use generator expressions for debug/release libs.
    set_property(TARGET ${_target} APPEND PROPERTY INTERFACE_LINK_LIBRARIES
        "$<$<CONFIG:Debug>:${_im_prefix}/debug/lib/${_libname}>"
        "$<$<NOT:$<CONFIG:Debug>>:${_im_prefix}/lib/${_libname}>"
    )
endmacro()

_im_add_target(ImageMagick::MagickCore  "MagickCore-7.@_im_qsuffix@.lib")
_im_add_target(ImageMagick::MagickWand  "MagickWand-7.@_im_qsuffix@.lib")
_im_add_target(ImageMagick::Magick++    "Magick++-7.@_im_qsuffix@.lib")

# Chain dependencies: Magick++ → MagickWand → MagickCore
set_property(TARGET ImageMagick::MagickWand APPEND PROPERTY
    INTERFACE_LINK_LIBRARIES ImageMagick::MagickCore)
set_property(TARGET ImageMagick::Magick++ APPEND PROPERTY
    INTERFACE_LINK_LIBRARIES ImageMagick::MagickWand)

unset(_im_incdir)
unset(_im_prefix)
