# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/preprocessor
    REF boost-1.80.0.beta1
    SHA512 4995ae0f858c1d570388067b92ab0018a195fc2abe81aa252bddbed067a22e361538fbce565f1995cca569abfa74f94a88f32f6e57ff79561a0a5d29b6378b5f
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
