include(vcpkg_common_functions)

set(LIBSODIUM_VERSION 1.0.15)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO jedisct1/libsodium
    REF ${LIBSODIUM_VERSION}
    SHA512 ec497cb0007597efaeae0aecaa7484d6dcc53367607ec3fd28a98c6209f0cdecd5a6f560c15badd3a69b8da7d63676b11fb395ef4ed4da9b80467dbdc5f65a72
    HEAD_REF master
)

if (VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
	set(LIBSODIUM_RELEASE_CONFIGURATION ReleaseDLL)
	set(LIBSODIUM_DEBUG_CONFIGURATION DebugDLL)
else()
	set(LIBSODIUM_RELEASE_CONFIGURATION Release)
	set(LIBSODIUM_DEBUG_CONFIGURATION Debug)
endif()

vcpkg_build_msbuild(
	PROJECT_PATH ${SOURCE_PATH}/libsodium.vcxproj
	RELEASE_CONFIGURATION ${LIBSODIUM_RELEASE_CONFIGURATION}
	DEBUG_CONFIGURATION ${LIBSODIUM_DEBUG_CONFIGURATION}
)

IF(VCPKG_TARGET_ARCHITECTURE MATCHES "x86")
	SET(BUILD_ARCH "Win32")
ELSE()
	SET(BUILD_ARCH ${VCPKG_TARGET_ARCHITECTURE})
ENDIF()


file(GLOB LIBSODIUM_HEADERS "${SOURCE_PATH}/src/libsodium/include/sodium/*.h")
file(INSTALL
	${LIBSODIUM_HEADERS}
	DESTINATION ${CURRENT_PACKAGES_DIR}/include/sodium
)

if (VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
	file(INSTALL
		${SOURCE_PATH}/Build/${LIBSODIUM_RELEASE_CONFIGURATION}/${BUILD_ARCH}/libsodium.dll
		DESTINATION ${CURRENT_PACKAGES_DIR}/bin
	)
	file(INSTALL
	${SOURCE_PATH}/Build/${LIBSODIUM_DEBUG_CONFIGURATION}/${BUILD_ARCH}/libsodium.dll
	DESTINATION ${CURRENT_PACKAGES_DIR}/debug/bin
	)
endif()

file(INSTALL
	${SOURCE_PATH}/Build/${LIBSODIUM_RELEASE_CONFIGURATION}/${BUILD_ARCH}/libsodium.lib
	DESTINATION ${CURRENT_PACKAGES_DIR}/lib
)
file(INSTALL
	${SOURCE_PATH}/Build/${LIBSODIUM_DEBUG_CONFIGURATION}/${BUILD_ARCH}/libsodium.lib
	DESTINATION ${CURRENT_PACKAGES_DIR}/debug/lib
)

vcpkg_copy_pdbs()

file(INSTALL
	${SOURCE_PATH}/LICENSE
	DESTINATION ${CURRENT_PACKAGES_DIR}/share/libsodium
	RENAME copyright
)
