# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/geometry
    REF boost-${VERSION}
    SHA512 ab61388b4f783cb819fcd3b935078952bda0cca739376237402d65e273f567acd4f92564e3915530e418865d2b55806a273605592ff42c987c955fd82c1d1634
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
