# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/geometry
    REF boost-${VERSION}
    SHA512 9ff6d0fb10db6118a719f2fe4155a8cd88aaab45719e61c58930f1cc1063248cda5778115690afc241aea941639708d130863e3a2a0d4d4e9a922f4bd70a9b0b
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
