# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/coroutine
    REF boost-${VERSION}
    SHA512 3009414cc3940268a04f34e3d8d70c2cf9cbb8b90874267bd45bfe5c0f58ae3538ae7ea41c1256157808975af3195b29c8f6e1e1d20a2aba60b7e14a7ebaadaa
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
