# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/convert
    REF boost-1.71.0
    SHA512 53e89b20e7a2f49a43429a856968893f35cdad098c1cbd7542dfbee1d08908382d5dba4489e57f701d62cae06d630daeb9fbd2624f40324fde204354de002a04
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
