cmake_policy(PUSH)
cmake_policy(SET CMP0057 NEW)
if(NOT "COMPONENTS" IN_LIST ARGS)
    vcpkg_underlying_find_package(${ARGS} COMPONENTS data)
else()
    vcpkg_underlying_find_package(${ARGS})
endif()
cmake_policy(POP)
