# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/typeof
    REF boost-1.79.0
    SHA512 ba0cfecb8c4ed750c46a9803350cc9e3e5a9493ef8b5f528003128039d57b13c10ec24ec31fa3e8d3d97a39a1d2381515ff340a471354a9fc8551268ca34aec5
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
