if(NOT DEFINED ENV{MKLROOT})
    set(z_vcpkg_blas_ignore_path "${CMAKE_IGNORE_PATH}")
    get_filename_component(z_vcpkg_installed "${CMAKE_CURRENT_LIST_DIR}" PATH)
    get_filename_component(z_vcpkg_installed "${z_vcpkg_installed}" PATH)
    list(APPEND CMAKE_IGNORE_PATH "${z_vcpkg_installed}/lib/intel64")
endif()
_find_package(${ARGS})
if(NOT DEFINED ENV{MKLROOT})
    set(CMAKE_IGNORE_PATH "${z_vcpkg_blas_ignore_path}")
endif()
