if(NOT DEFINED ENV{MKLROOT})
    set(z_vcpkg_blas_ignore_path "${CMAKE_IGNORE_PATH}")
    list(APPEND CMAKE_IGNORE_PATH "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/intel64")
endif()
_find_package(${ARGS})
if(NOT DEFINED ENV{MKLROOT})
    set(CMAKE_IGNORE_PATH "${z_vcpkg_blas_ignore_path}")
    unset(z_vcpkg_blas_ignore_path)
endif()
