# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/pool
    REF boost-${VERSION}
    SHA512 93dddbf90bc86b4ba9fd9aec318eb472b4f3c7e7421c8132bc7e523ebfd023abed0cf55ab33c80875016223a254431a9dda2359deb9653f3e565c46c1a051c1a
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
