# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/pool
    REF boost-1.80.0.beta1
    SHA512 fa8806e436a8ed594d6b036c24d04caa84567fd3d2dd3334127e61fca6be27759383b21ac1a5511f7c1313db5d5b95fd52d20cf9df6fb8f01971f8ad4d325cb7
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
