# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/bloom
    REF boost-${VERSION}
    SHA512 b1e146cf8e80531a73ffb793add3b60d92f7a1bc34564a48de7a6b63a80be7d62f44ddde494d8532d4fac2d2383225b12a7e39ecea3fb2ce597fad9233679d7e
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
