# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/bloom
    REF boost-${VERSION}
    SHA512 ebc45de0218a1de60c606a7ac439479688c713eeee6f726a277297e85c1235ed2ffed1192f786909b2505d91c923bf3112aa1d60ec01c8d0f04f654d60aea5f2
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
