# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/bloom
    REF boost-${VERSION}
    SHA512 54988a6754d2e28d30e64feda29970e6e945faae25a68e6881167709c6e64136fb8cb8f586cc444bf654aa08c37363a042a0ca2b6b64d59d2124ea6d3d315a45
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
