get_filename_component(_DIR "${CMAKE_CURRENT_LIST_DIR}/../../" ABSOLUTE)
if(NOT SOCKPP_FIND_COMPONENTS)
    set(SOCKPP_FIND_COMPONENTS sockpp)
    if(SOCKPP_FIND_REQUIRED)
        set(SOCKPP_FIND_REQUIRED_sockpp TRUE)
    endif()
    set(SOCKPP_FOUND TRUE)
endif()

set(SOCKPP_INCLUDE_DIRS ${_DIR}/include)
set(SOCKPP_LIBRARIES)
if (EXISTS ${_DIR}/lib/libsockpp.a)
    list(APPEND SOCKPP_LIBRARIES optimized ${_DIR}/lib/libsockpp.a)
endif()
if (EXISTS ${_DIR}/debug/lib/libsockpp.a)
    list(APPEND SOCKPP_LIBRARIES debug ${_DIR}/debug/lib/libsockpp.a)
endif()
if (EXISTS ${_DIR}/lib/sockpp.lib)
    list(APPEND SOCKPP_LIBRARIES optimized ${_DIR}/lib/sockpp.lib)
endif()
if (EXISTS ${_DIR}/debug/lib/sockpp.lib)
    list(APPEND SOCKPP_LIBRARIES debug ${_DIR}/debug/lib/sockpp.lib)
endif()
