get_filename_component(_DIR "${CMAKE_CURRENT_LIST_DIR}/../../" ABSOLUTE)
if(NOT SOCKPP_FIND_COMPONENTS)
    set(SOCKPP_FIND_COMPONENTS sockpp)
    if(SOCKPP_FIND_REQUIRED)
        set(SOCKPP_FIND_REQUIRED_sockpp TRUE)
    endif()
    set(SOCKPP_FOUND TRUE)
endif()

set(SOCKPP_INCLUDE_DIRS ${_DIR}/include)
set(SOCKPP_LIBRARIES)
if (EXISTS ${_DIR}/lib/libsockpp.so)
    list(APPEND SOCKPP_LIBRARIES ${_DIR}/lib/libsockpp.so)
endif()
