vcpkg_check_features(
  OUT_FEATURE_OPTIONS
    FEATURE_OPTIONS
  FEATURES
    "c99-tr1" BOOST_MATH_BUILD_WITH_C99_AND_TR1_FUNCTIONS
)

if(NOT BOOST_MATH_BUILD_WITH_C99_AND_TR1_FUNCTIONS)
    set(Z_VCPKG_BOOST_FORCE_HEADER_ONLY ON)
endif()
