vcpkg_check_features(
  OUT_FEATURE_OPTIONS
    FEATURE_OPTIONS
  FEATURES
    "legacy" BOOST_MATH_BUILD_WITH_LEGACY_FUNCTIONS
)

if(NOT BOOST_MATH_BUILD_WITH_LEGACY_FUNCTIONS)
    set(Z_VCPKG_BOOST_FORCE_HEADER_ONLY ON)
endif()
