# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/function_types
    REF boost-${VERSION}
    SHA512 ad13dcb150123aa75315d5aff754d38d9b084c7526c1e9d88923c21072307ab0ca7678635ee41f24943a8dda99f73e670c612cec5ee8055956337cff48dc5fd5
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
