find_package(capstone CONFIG REQUIRED)

if(capstone_FOUND)
    message(STATUS "Capstone target found: capstone::capstone.")
    return()
else()
    message(STATUS "Trying to find capstone by PkgConfig.")
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(CAPSTONE REQUIRED IMPORTED_TARGET capstone)
    add_library(capstone::capstone ALIAS PkgConfig::CAPSTONE)
endif()
