# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mpl
    REF boost-1.77.0
    SHA512 8f43a32281aa33749fef93be450adb7ccc2774589afbb498bac335ff1cd95ad21e5899cb4c26cbdc2836764ca7264e1408e3d0c15a21d1488a56579304a29ba4
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
