list(REMOVE_ITEM ARGS "CONFIG")

set(IMGUI_PREV_MODULE_PATH ${CMAKE_MODULE_PATH})
list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})

if(NOT LIBPROXY_LIBRARIES)
  _find_package(${ARGS})
endif()

set(CMAKE_MODULE_PATH ${IMGUI_PREV_MODULE_PATH})
