vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO ladislav-zezula/StormLib
    REF "v${VERSION}"
    SHA512 8646b152f894d4f2d920b73007522b0d7508fbb2cac7c9439e7f5033228c33e09db587c46ffc18d6ce788d0d5f0b5a832aad528cf0dda87d082516ce4c6b55bf
    HEAD_REF master
    PATCHES
        disable-autolinking.patch
)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
)

vcpkg_cmake_install()
vcpkg_cmake_config_fixup(PACKAGE_NAME StormLib)
vcpkg_replace_string(
    "${CURRENT_PACKAGES_DIR}/share/StormLib/StormLibConfig.cmake"
    "# Generated by CMake"
    "# Generated by CMake\n\ninclude(CMakeFindDependencyMacro)\nfind_dependency(ZLIB)\nfind_dependency(BZip2)"
)
vcpkg_copy_pdbs()

vcpkg_install_copyright(
    FILE_LIST
        "${SOURCE_PATH}/LICENSE"
        "${SOURCE_PATH}/src/libtomcrypt/src/pk/asn1/der_encode_utf8_string.c"
        "${SOURCE_PATH}/src/libtommath/bn_mp_abs.c"
)
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")
