# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/flyweight
    REF boost-${VERSION}
    SHA512 0f9083fed4115bd987e738bc164902b3f88d6a953fad04c477e854d2d7d6937712bda6381132d7699f02596dd081aa5cdf843e88b8563f8b7a850b8b8e2f8f45
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
