# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/charconv
    REF boost-${VERSION}
    SHA512 6d4deb5a3fbff19c11eb12aa289c486f775a87e01e430ac18ca959937f9a2e1e76d4dbe5a5dddae45af893358cb2c2fe1d7b3737b0b00102fb9bca13b9a4b566
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux" AND VCPKG_TARGET_IS_MINGW)
    # when cross compile, cmake generates the error try_run() invoked in cross-compiling mode
    list(APPEND FEATURE_OPTIONS "-DBOOST_CHARCONV_QUADMATH_FOUND_EXITCODE=0")
endif()
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
