# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/yap
    REF boost-1.73.0
    SHA512 f228ba3255f91cdd503a8fdf9f881dc608f1730bda685aca0e1638cd96add9194a250da154b4ce1ae3438ba92c88572f666eda2893ac9d53e6a4b1827d55a06b
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
