# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/mp11
    REF boost-1.80.0.beta1
    SHA512 259c5e54db5e98ac110967e2f24b77befe2ff3ee518d196bf4d7555a394bcd7524f7000d371ddc6f49d11ff3bdc0ad4a4443bc2508ebb627d9cee6d1cb8fb06d
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
