# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/property_tree
    REF boost-${VERSION}
    SHA512 494bff050a1fea18f43d6db260b47fd4419cd61ec7a9c7275ca1517a20be096cb648f463a9bc3cbeb5d7af1753f125b2ea2b2ac37617931d99b27e2f87ab076f
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
