# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/property_tree
    REF boost-${VERSION}
    SHA512 12383123d98fed71822a17246502928b9806fd00f81f0ef51e59b0ce49f292271978f359e74f399d444264f6cade69254209d89c6675ec6f495a51a9101a41f2
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
