_find_package(${ARGS})

if("@VCPKG_LIBRARY_LINKAGE@" STREQUAL "static")
    if(NOT "@VCPKG_TARGET_IS_WINDOWS@")
        find_package(Iconv REQUIRED)
    endif()
    if("@EXIV2_ENABLE_NLS@")
        find_package(Intl REQUIRED)
    endif()
    if("@EXIV2_ENABLE_BMFF@")
        find_package(unofficial-brotli CONFIG REQUIRED)
    endif()
    if("@EXIV2_ENABLE_XMP@") 
        find_package(expat CONFIG REQUIRED)
    endif()
    if("@EXIV2_ENABLE_PNG@")
        find_package( ZLIB REQUIRED )
    endif()
    find_package(unofficial-inih CONFIG REQUIRED)
    if(TARGET exiv2lib)
        if(NOT "@VCPKG_TARGET_IS_WINDOWS@")
            set_property(TARGET exiv2lib APPEND PROPERTY INTERFACE_LINK_LIBRARIES Iconv::Iconv)
        endif()
        if("@EXIV2_ENABLE_NLS@")
            set_property(TARGET exiv2lib APPEND PROPERTY INTERFACE_LINK_LIBRARIES
                "\$<\$<NOT:\$<CONFIG:DEBUG>>:${Intl_LIBRARY_RELEASE}>"
                "\$<\$<CONFIG:DEBUG>:${Intl_LIBRARY_DEBUG}>"
            )
        endif()
    endif()
endif()
