if(EMSCRIPTEN)
  vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
endif()
vcpkg_from_github(
  OUT_SOURCE_PATH SOURCE_PATH
  REPO ethindp/prism
  REF v0.16.2
  SHA512 c18da8d6e0ded885ab55093442eae0bb7c74361441473eff787983050f7483e6455bf284b3ecadc4f2a04e1d41e6bd765e735a90496351365992fb1eb8c9ac88
  HEAD_REF master
)
vcpkg_check_features(
  OUT_FEATURE_OPTIONS FEATURE_OPTIONS
  FEATURES
    orca PRISM_VCPKG_WANTS_ORCA_BACKEND
    speech-dispatcher PRISM_VCPKG_WANTS_SPEECH_DISPATCHER_BACKEND
)
vcpkg_cmake_configure(
  SOURCE_PATH "${SOURCE_PATH}"
  OPTIONS
    -DPRISM_ENABLE_TESTS=OFF
    -DPRISM_ENABLE_DEMOS=OFF
    -DPRISM_ENABLE_LINTING=OFF
    -DPRISM_ENABLE_GDEXTENSION=OFF
    -DPRISM_ENABLE_VCPKG_SPECIFIC_OPTIONS=ON
    -DPRISM_ENABLE_LEGACY_BACKENDS=ON
    ${FEATURE_OPTIONS}
)
vcpkg_cmake_install()
if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")
  file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/bin" "${CURRENT_PACKAGES_DIR}/bin")
endif()
vcpkg_cmake_config_fixup(PACKAGE_NAME prism CONFIG_PATH share/prism)
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
vcpkg_copy_pdbs()
vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
