# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/property_map_parallel
    REF boost-1.80.0.beta1
    SHA512 856b50f7ceb498ee1e244a731857a1d0b124accaa360253090e49d0ad501505aee82acbeedaaf284f8f959969acd285f982fa36eda284a6955cd185c0fa015db
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
