# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/openmethod
    REF boost-${VERSION}
    SHA512 56e63f56255c889d4fdfc0c2a7a86852f54c00bd4643a2d483bea93904af00510265b2de8eefe64973cc1d3632d89fe17b498309666f693a5ae60f19f258820b
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
