# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/openmethod
    REF boost-${VERSION}
    SHA512 bdf59497f264760a800dde5b73013764acb80997bc458e47aafc10d3ba3cbbc84bd14db46da7c476610b3edeeabf6eee05fb8241e7be621fb3d71a3df7a05577
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
