include("${CMAKE_CURRENT_LIST_DIR}/ANGLETargets.cmake")

if(NOT TARGET ANGLE::EGL)
  add_library(ANGLE::EGL INTERFACE IMPORTED)
  set_target_properties(ANGLE::EGL PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/../../include"
    INTERFACE_LINK_LIBRARIES ANGLE::libEGL)
endif()

if(NOT TARGET ANGLE::GLESv2)
  add_library(ANGLE::GLESv2 INTERFACE IMPORTED)
  set_target_properties(ANGLE::GLESv2 PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/../../include"
    INTERFACE_LINK_LIBRARIES ANGLE::libGLESv2)
endif()
