# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/multi_index
    REF boost-${VERSION}
    SHA512 eaeef6c35f07cb07a1e1db8805f5df8456c9faf45bafbf2bde177a0b8f9452c94f6d29900848e437e3a64a69844998f7b50468285e5b12e3da7e3965f0bc3de0
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
