if(Z_VCPKG_LIBTOOL_GUARD)
    return()
endif()
set(Z_VCPKG_LIBTOOL_GUARD ON CACHE INTERNAL "guard variable")

function(z_vcpkg_libtool_setup)
    cmake_path(SET z_vcpkg_libtool_dir NORMALIZE "${CMAKE_CURRENT_LIST_DIR}/../..")
    set(LIBTOOL_EXECUTABLE "${z_vcpkg_libtool_dir}/tools/@PORT@/bin/libtool" CACHE PATH "The libtool executable")
    set(LIBTOOLIZE_EXECUTABLE "${z_vcpkg_libtool_dir}/tools/@PORT@/bin/libtoolize" CACHE PATH "The libtoolize executable")
    # VCPKG_HOST_PATH_SEPARATOR is not defined when this function is called.
    if(CMAKE_HOST_WIN32)
        set(VCPKG_HOST_PATH_SEPARATOR ";")
    else()
        set(VCPKG_HOST_PATH_SEPARATOR ":")
    endif()
    vcpkg_host_path_list(PREPEND ENV{PATH} "${z_vcpkg_libtool_dir}/tools/@PORT@/bin")
    vcpkg_host_path_list(PREPEND ENV{ACLOCAL_PATH} "${z_vcpkg_libtool_dir}/share/@PORT@/aclocal")
endfunction()
z_vcpkg_libtool_setup()

include("${CMAKE_CURRENT_LIST_DIR}/x_vcpkg_update_libtool.cmake")
