# Automatically generated by boost-vcpkg-helpers/generate-ports.ps1

include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/interprocess
    REF boost-1.69.0
    SHA512 1bad3bb5e9fa59c48607ea2d668b61fdc15d60ab0e9f6cd04d1fcd972932b2466e94203062a65142b1b810e26b0cb59fd0890aaa4b764ac03d16ab3c95454d73
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
