# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/icl
    REF boost-${VERSION}
    SHA512 7ea1fabb500faddc6ffe32fedf3e26f5654a2f1376658b758246330a58382bc2cd7f95159fe4d9472a63e8bbd275e537da595d88052221b9ac4d712a9e291139
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
