# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/icl
    REF boost-1.82.0
    SHA512 d808e3961b8f84445294f063c8f3d65220ed23410978d76171e505817a19b472c3052b02c270bca114da7d9d03d958510173df17d724c3533ae6927409eede9d
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
