# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/heap
    REF boost-${VERSION}
    SHA512 01587877c799768113fb1e405dcf0fcd2d60cad67efd81a55974f29292b30e3415adeefffd70e2f6f1063800cd9e925620541a84fcabc8a5ce8827645c7c123d
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
