name: Check vcpkg Tools SHA

on:
  pull_request:
    paths:
      - "scripts/vcpkg-tools.json"

permissions:
  contents: read

jobs:
  check-tools-sha:
    runs-on: ubuntu-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Bootstrap vcpkg
        run: ./bootstrap-vcpkg.sh

      - name: Run vcpkg x-check-tools-sha
        run: vcpkg z-check-tools-sha scripts/vcpkg-tools.json || echo "Run 'vcpkg z-check-tools-sha scripts/vcpkg-tools.json --fix' to update the SHA values"
