# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/unordered
    REF boost-${VERSION}
    SHA512 c28cc7c7bbb9fa04634f9fa4d371e31df084a64177e9d6b0395e82084f513aac3ec01cdb3b0fa7019902c963dce6cfac65da5e66d444932c005b0430e69471cf
    HEAD_REF master
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
