# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/ptr_container
    REF boost-1.80.0.beta1
    SHA512 9e59812ad90023cfc6b45fbd3d6eb9dae9afb1777545f6d4217a2dc029da2be2f7a39816bc34c65fb70d0a9a97bf238c3274a53a6c570ed99c6e0fd2ec23f827
    HEAD_REF master
)

include(${CURRENT_INSTALLED_DIR}/share/boost-vcpkg-helpers/boost-modular-headers.cmake)
boost_modular_headers(SOURCE_PATH ${SOURCE_PATH})
